- gpytorch/__init__.py
- gpytorch/inference/posterior_models/exact_gp_posterior.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
This adds 3 methods to `gpytorch/__init__.py` and LazyVariables:
- `posterior_alpha` - create a cache for the mean
- `posterior_mean` - calculates the mean (given the alpha cache)
- `posterior_covar` - calculates the covariance
With this in place, we can remove `_exact_predict` from `gpytorch/__init__.py`, and the logic for `forward` in `ExactGPPosterior` is super simple.
I plan on doing the same thing for the variational case as well.
cc/ @jrg365 @wrh14
> Refactor out _exact_predict

- gpytorch/__init__.py
`_variational_predict` as written explicitly forms the inducing point variational covariance matrix before multiplying by W_left and W_right. This PR just splits it in to `W_left*L^{\top}` and `L*W_right^{\top}`, and then multiplies these together. The end result is an `O(pm+pm^2)` running time, where p is the number of test points, down from `O(pm^2+m^3)`.
I am making this a PR because I know I promised I would only touch LinearCG ;-).
> Simple fix to improve running time of variational predict.

- gpytorch/__init__.py
- gpytorch/inference/posterior_models/variational_gp_posterior.py
- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/utils/function_factory.py
- test/examples/spectral_mixture_gp_regression_test.py
- test/functions/inv_matmul_test.py
- test/functions/matmul_test.py
- test/util/function_factory_test.py
@gpleiss @jrg365 
This new branch is for implementations of `Inv_matmul`,  `Matmul` and `ExactGPMLL` in `function_factory.py`.
Also I did some small modifications. 
1. I pass the `inducing_covar` rather than `train_covar` into  `gpytorch.mvn_kl_divergence` in `marginal_log_likelihood` in `variational_gp_posterior`, which should be more reasonable according to the definition.
2. I rewrite `_derivative_quadratic_form_factory` for LazyVariable, which was only for Toeplitz matrix before and is for total LazyVariable now (Add the consideration for interpolated part).
> Inv_matmul, Matmul and ExactGPMLL

- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- test/lazy/kronecker_product_lazy_variable_test.py
- test/lazy/toeplitz_lazy_variable_test.py
We no longer use these functions, and they are dangerously slow functions to use.
> Remove `explicit_interpolate_T` and `explicit_interpolate_K`

- gpytorch/lazy/toeplitz_lazy_variable.py
- test/lazy/toeplitz_lazy_variable_test.py
Allows for product kernels with KISS-GP, i.e. k(x,x') = \prod_{i} k_{i}(x_{i},x_{i}')
> Implement product kernels for ToeplitzLazyVariables

- gpytorch/functions/add_diag.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/means/mean.py
- gpytorch/utils/__init__.py
- gpytorch/utils/function_factory.py
- gpytorch/utils/lanczos_quadrature.py
- gpytorch/utils/lincg.py
- gpytorch/utils/trace.py
- test/examples/simple_gp_regression_test.py
- test/util/trace_test.py
New util: `gpytorch.utils.trace_components`.
Given a matrix `A^T B` that we want to compute the trace for, this function returns `A'` and `B'` such that `tr(A^T B) = sum(A * B) = sum(A' * B')`.
This function can also be used for efficiently computing the diagonal elements of a matrix, as well as the left and right vectors for derivative quad form (which has been refactored).
@wrh14 @jrg365
> Stochatic trace refactor

- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/mul_lazy_variable.py
- gpytorch/lazy/non_lazy_variable.py
- gpytorch/lazy/sum_lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/random_variables/bernoulli_random_variable.py
- gpytorch/random_variables/categorical_random_variable.py
- gpytorch/random_variables/dirichlet_random_variable.py
- gpytorch/random_variables/gaussian_random_variable.py
- gpytorch/random_variables/mixture_random_variable.py
- gpytorch/random_variables/random_variable.py
- gpytorch/random_variables/samples_random_variable.py
Lazy variables and random variables must now call `super(<Class>, self).__init__(*args, **kwargs)`, but this allows us easily to construct cpu and cuda versions of these objects, using the same interface as for Variables and Tensors.
> Lazy variables and random variables can be cuda/cpu'd

- gpytorch/random_variables/gaussian_random_variable.py
Removes some seemingly old checks in `gaussian_random_variable.py` for variational strategies -- I think this is holdover code from before one of the recent refactors. I don't think `RandomVariables` have variational strategies now.
#58 
@gpleiss
> Remove variational strategy checks from gaussian_random_variable (Fix for #58)

- build.py
- gpytorch/functions/log_normal_cdf.py
- gpytorch/lazy/interpolated_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/utils/__init__.py
- gpytorch/utils/fft.py
- gpytorch/utils/function_factory.py
- gpytorch/utils/sparse.py
- test/util/function_factory_test.py
- test/util/interp_test.py
- test/util/test_function_factory.py
- test/util/test_interp.py
This retains compatiblity with PyTorch 0.3.
The file gpytorch/utils/function_factory.py deserves some attention: The
`t_matmul_closure_factory` does not always return the correct shape for
the gradient. This is a bug: gradients should have the exact same shape
as the differnetiated variable. PyTorch is missing some checks for this
behavior, but future versions of PyTorch are likely to raise an
exception if shapes don't exactly match.
(This depends on https://github.com/pytorch/pytorch/pull/5643 in PyTorch)
> Fixes to gpytorch to be compatible with PyTorch master

- gpytorch/kernels/__init__.py
- gpytorch/kernels/additive_grid_interpolation_kernel.py
- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- test/kernels/test_additive_kernel.py
- test/kernels/test_linear_kernel.py
- test/kernels/test_periodic_kernel.py
- test/kernels/test_rbf_kernel.py
This has two new features:
* You can now add two kernels using `+` and `*` and an AdditiveKernel or ProductKernel is returned. 
* `active_dims` can be sent via the constructor to subset dimensions, mirroring the capabilities of GPy
Small items: adding linear and periodic kernel, and adding `six` imports to make sure there aren't python 2.x / 3.x discrepancies
> Add ability to take sum and product of kernels directly, add linear and periodic kernels, create `active_dims`

- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- test/kernels/test_rbf_kernel.py
Implements ARD on the level of the Kernel class. See https://github.com/cornellius-gp/gpytorch/issues/82 for details. 
In the process, simplify computation of RBFKernel. Previous computation was somewhat messy to get to work for different length scales. Turns out there isn't really a perf hit from doing this (see below).
```python
import math
import torch
from gpytorch.kernels import RBFKernel
from torch.autograd import Variable
from gpytorch.kernels import Kernel, RBFKernel
```
```python
class RBFKernel_NEW(Kernel):
def __init__(
self,
ard_num_dims=None,
log_lengthscale_bounds=(-10000, 10000),
eps=1e-5,
active_dims=None,
):
super(RBFKernel_NEW, self).__init__(
has_lengthscale=True,
ard_num_dims=ard_num_dims,
log_lengthscale_bounds=log_lengthscale_bounds,
active_dims=active_dims,
) …
```
> Implement ARD, simplify RBF Kernel

- gpytorch/__init__.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/mlls/variational_marginal_log_likelihood.py
- gpytorch/utils/__init__.py
- gpytorch/utils/function_factory.py
- gpytorch/variational/mvn_variational_strategy.py
- test/lazy/test_constant_mul_lazy_variable.py
- test/lazy/test_sum_lazy_variable.py
- test/util/test_function_factory.py
This commit simplifies the functions in function factory.
- Remove `exact_gp_mll` and `trace_log_det_quad_form`
- MLL computations (exact and variational) now use new function factory function: `inv_quad_log_det`
- Introduce new functions: `inv_quad` and `log_det`.
This PR removes the two functions that were specific to marginal log likelihood computations (`exact_gp_mll`, `trace_log_det_quad_form`) and adds a more generic function: `inv_quad_log_det`.
`inv_quad_log_det` computes an inverse quadratic form `tr( A^T K^{-1} A)` and a log determinant `K^{-1}`. These two functions are grouped together to minimize the number of calls to LinearCG. Using this function, marginal log likelihood computations for exact and variational inference only require one round of LinearCG for both forward and …
> Marginal log likelihood (and function factory) refactor

- build.py
`python setup.py install` now looks for anaconda installations of fftw when building.
Fixes #89 and #91
> Fix installation issues with anaconda

- test/util/test_function_factory.py
On PyTorch master (0.4-alpha), Indexing a zero-dimensional tensor does not return a numeric value anymore, but a tensor. This caused test failures with assertAlmostEqual of the kind TypeError: type Variable doesn't define __round__ method.
This PR fixes these assertion errors, so they work on stable PyTorch (0.3) and PyTorch master.
> Function factory tests work on pytorch 0.3 and 0.4

- gpytorch/lazy/__init__.py
- gpytorch/lazy/added_diag_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/non_lazy_variable.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/settings.py
- gpytorch/utils/function_factory.py
- gpytorch/utils/pivoted_cholesky.py
- test/util/test_pivoted_cholesky.py
This pull request implements a (currently optional) preconditioning feature for linear solves, using a pivoted Cholesky decomposition as a preconditioner. 
Preconditioning can significantly reduce the number of CG iterations required to get accurate solves. While this may not substantially affect training (other than a potential speed improvement), this can significantly improve test accuracy / speed where previously a significant number of CG iterations were required.
Preconditioning can now be enabled for linear solves by using the context
```python
with gpytorch.settings.max_preconditioner_size(value)
```
with value > 0 (default is 0, which disables preconditioning). 
- `LazyVariable` now defines a `_preconditioner()` method, which by default returns `None`. For certain …
> Implement Preconditioning

- gpytorch/mlls/variational_marginal_log_likelihood.py
- gpytorch/module.py
- gpytorch/random_variables/categorical_random_variable.py
- gpytorch/random_variables/samples_random_variable.py
This branch has a number of small fixes
This allows the use of more complicated likelihoods. Imagine a likelihood that requires additional inputs, besides the gp output and target: `def log_likelihood(gp_output, target, extra_input_1, extra_input_2)`. This PR modifies the variational MLL to allow for the extra inputs as kwargs:
```python
mll(gp_output, target, extra_input_1=extra_input_1, extra_input_2=extra_input_2)
```
As currently implemented, samples of categorical random variables do not produce a gradient. Now, these variables can produce "soft" back-propable samples using the [gumbel-softmax estimator](https://arxiv.org/abs/1611.01144).
If you call `random_variable.sample(n_samples=10, gumbel_softmax_temp=1.5)`, this produces gumbel-softmax estimated samples, with temperature of …
> Small fixes

- gpytorch/lazy/__init__.py
- gpytorch/lazy/chol_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/sum_lazy_variable.py
- gpytorch/mlls/variational_marginal_log_likelihood.py
- gpytorch/models/abstract_variational_gp.py
- gpytorch/models/grid_inducing_variational_gp.py
- gpytorch/utils/pivoted_cholesky.py
- gpytorch/utils/toeplitz.py
- gpytorch/variational/mvn_variational_strategy.py
- test/lazy/test_chol_lazy_variable.py
Some small fixes/refactors to variational inference:
- The Variational MLL object has an optional `combine_terms` attribute (default true). If you set it to false, the loss returns the two terms (the expected NLL and the KL term) separately.
- MVN KL divergence can now take a lazy variable for the variational covariance. (For now, we're always using a cholesky lazy variable, but it allows for other LV options in the future).
- The AddedDiagLazyVariable is used for the variational diagonal correction
- Remove the old MLL functions from lazy variables
- Fix a transpose issue in SumLazyVariable
> Fixes to variational inference

- gpytorch/models/exact_gp.py
This is useful e.g. for "fantasizing", i.e. performing posterior prediction under different realizations of the training target, without re-fitting the model parameters (see example below).
Note that this is written under pytorch 0.4+ and may not work under pytorch 0.3.1 (feel free to make that compatible)
```
def posterior_mean(gp, X):
return gp(X).mean()
def fantasize(gp, fun, X, Ydist, nsamp):
Ybase = gp.train_targets.clone()
for i in range(nsamp):
gp.set_train_targets(Ydist.sample())
yield fun(gp, X)
gp.set_train_targets(Ybase)
Ydist = Normal(
loc=training_data.Y[metric],
scale=training_data.Y_sem[metric],
)
gp.train_targets[:2]
0.1653
0.3505
[torch.FloatTensor of size (2,)]
for m in evaluate_fantasies(gp, posterior_mean, training_data.X[metric], Ydist, 2):
print(m[:2])
-0.4004
0.6623 …
```
> Allow to change training targets for exact GP after fitting

- test/examples/test_kissgp_kronecker_product_regression.py
Previously this test would fail with assertion errors.
> Change seed of TestKissGPKroneckerProductRegression

- gpytorch/kernels/rbf_kernel.py
- gpytorch/utils/__init__.py
- test/examples/test_kissgp_kronecker_product_classification.py
- test/kernels/test_additive_kernel.py
- test/kernels/test_rbf_kernel.py
- test/util/test_pivoted_cholesky.py
Previous: `k(x, y) = exp(-|x-y|^2 / l)`
Now: `k(x,y) = exp(-0.5 * |(x-y)/l|^2)`
This doesn't really change any functionality whatsoever, but makes the definition consistent with some of the literature (e.g. Rasmussen & Williams) and the implementations in other packages (e.g. scipy and GPy)
Also, making baby steps towards getting rid of variables #110
> Change definition of RBF Kernel

- gpytorch/kernels/matern_kernel.py
Before: `distance_over_rho = |x-y|^2 / l`
Now: `distance_over_rho = |(x-y) / l|^2`
As with the RBF changes, this doesn't affect functionality, but adheres to a more common definition in the literature / in other software.
> Change definition of Matern lengthscales

- gpytorch/kernels/linear_kernel.py
expand_as(prod) errors out now, because it checks that the input is a Tensor, and the check fails because it's of type MatmulLazyVariable. So instead move to expand(size)
> modify expand_as  to expand for 0.4

- gpytorch/functions/_add_diag.py
`batch_indices` and `diag_indices` need to be long() to be used in the `__getitem__` call for `grad_output`.
> Indices should be long, not float

- test/examples/test_kissgp_additive_regression.py
Looks like some changes upstream on the pytorch master branch are causing this test to fail (AssertionError: 0.18641792237758636 not less than 0.15)
Seems to be fine with this new seed
> Change seed for TestKISSGPAdditiveRegression

- gpytorch/kernels/rbf_kernel.py
A few changes:
1. We divide the lengthscale by 2 before summing the squared dimension-wise distances. This seems to be more numerically stable than dividing by 2 afterwards.
1. Rather than adding 1e-5 to the lengthscale (to prevent division by zero errors), we're instead using a clamp operation.
Fixes #119
> RBF stability improvements

- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/constant_mul_lazy_variable.py
- gpytorch/lazy/lazy_evaluated_kernel_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/lazy_variable_representation_tree.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/models/abstract_variational_gp.py
- gpytorch/utils/pivoted_cholesky.py
- test/kernels/test_additive_kernel.py
- test/kernels/test_periodic_kernel.py
- test/kernels/test_rbf_kernel.py
- test/util/test_pivoted_cholesky.py
Working on fixing #135. So far, simple GPs and the 1D KISS-GP tests pass.
My initial solution to this is to make the `__call__` method of `Kernel` directly create the new `LazyEvaluatedKernelVariable`, which basically supports a `__getitem__` method (so we can subindex in to a kernel matrix before evaluating the kernel, which is the point of this PR) and an `evaluate()` method. This is a meta lazy variable, in that the `evaluate()` method can return another `LazyVariable` if the kernel call does.
The reason I am obviously unhappy with this is that if the user does anything in forward other than call a kernel and return the `LazyEvaluatedKernelVariable`, we now call `evaluate()` in the model, which is obviously a Bad Thing if the covariance is, for example, already an …
> Lazily evaluate kernel functions

- gpytorch/kernels/spectral_mixture_kernel.py
SpectralMixtureKernel has an .initialize() function that overrides the function fo the same name of the superclass Module, but these functions have different purposes. This is confusing and has created hard to debug issues.
Since this function is used nowhere in the code, this simply renames it to initialize_from_data as suggested in #149.
> Rename SpectralMixtureKernel's initialize to initialize_from_data

- gpytorch/kernels/__init__.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/white_noise_kernel.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/lazy_evaluated_kernel_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/sum_lazy_variable.py
- gpytorch/lazy/zero_lazy_variable.py
- gpytorch/module.py
- test/examples/test_kissgp_white_noise_regression.py
- test/examples/test_white_noise_regression.py
Here's my take on implementing the white noise kernel (#113), and two simple unit tests for it that show it works in at least the simple GP regression case and the 1D KISS-GP regression case.
I changed things a bit so that kernels can return `None`, and `LazyVariables` treat adding `None` as a no-op. If we think this is unsafe or would make debugging more difficult in some cases, we could equivalently make a `ZeroLazyVariable` that behaves the same way.
With that in mind, the white noise kernel returns a `DiagLazyVariable` containing `self.variances` if it believes it is dealing with training data, and returns `None` otherwise. 
There are some changes to `AddedDiagLazyVariable` I'd like to make to make things even more efficient when dealing with this kind of kernel, but that can be a …
> Implement white noise kernel

- gpytorch/kernels/kernel.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/means/constant_mean.py
- gpytorch/means/mean.py
- gpytorch/models/exact_gp.py
- test/examples/test_batch_gp_regression.py
Exact GPs support batch predictions, which addresses #134. I'll open up another issue for batch training, which shouldn't be that hard (it looks like someone wanted to support this at some point: the `ConstantMean` class has an optional `batch_mode` argument that reshapes the constant parameter appropriately). Now, you can do something like:
```python
batch_train_x = train_x.repeat(3, 1, 1)
batch_train_y = train_y.repeat(3, 1)
batch_test_x = test_x.repeat(3, 1, 1)
model.set_train_data(batch_train_x, batch_train_y, strict=False)
batch_preds = model(batch_test_x)
```
and you'll get batch predictions on each batch of test data, using the corresponding train input and label batches as the input data for that GP.
Basically, this just involved bringing prior and posterior means up to speed with …
> Support batch GP predictions (Fixes #134)

- gpytorch/kernels/__init__.py
- gpytorch/kernels/kernel.py
- test/kernels/test_additive_kernel.py
This was blocking some implementation a student was working on here. 
`AdditiveKernel` and `ProductKernel` now operate on a list of kernels, and accept several kernels in their constructors.
> AdditiveKernel and ProductKernel now accept several kernels to compose

- test/examples/test_batch_gp_regression.py
This seems to have fixed the flakiness in the batch GP test -- I just initialize the log_outputscale closer to the ground truth. Not sure why it failed 1/50 times before, but I ran it for ~300 times without it failing #162 .
If this doesn't work, we can either lock down the seed or change the test to not do optimization at all and just test with hard coded hyperparameters.
> batch gp test - initialize log lengthscale closer to ground truth

- test/lazy/test_interpolated_lazy_variable.py
Fixes #169, as well as removes `Variable` from the test entirely.
> Update test_interpolated_lazy_variable to PyTorch 0.4, 0.5

- gpytorch/module.py
- test/examples/test_kissgp_gp_classification.py
It seems like this was easy enough -- I think these really only existed to stop people from creating parameters without bounds. Since bounds are now handled exclusively as priors, none of the functionality in those methods accomplished anything necessary.
Travis, what do you think?
#180
> Remove custom __getattr__ and __setattr__ from gpytorch.Module (addresses #180)

- gpytorch/priors/wishart_prior.py
With `A`, `B` positive definite we have `trace(AB^-1) = trace(B^-1A)`.
For 3x3 matrices:
```
%timeit torch.trace(A.matmul(B.inverse()))
35.5 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit torch.trace(torch.gesv(A, B)[0])
24.9 µs ± 436 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
> Speed up eval of log_prob for InverseWishartPrior

- gpytorch/kernels/index_kernel.py
- gpytorch/lazy/interpolated_lazy_variable.py
This should allow the use of index kernels (for multitask gps) with any of the scalable methods.
I'll also update the multitask notebook (or create a new notebook) that shows how to do scalable kronecker methods.
> Index kernel returns a lazy variable

- test/examples/test_spectral_mixture_gp_regression.py
I tried a few different seeds and the test passes more reliably. It also passes with the default seed (4) on machines that don't have FMA3 instructions.
See #200
> Use SGD in test_spectral_mixture_gp_regression.py

- gpytorch/functions/__init__.py
- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/lazy/lazy_evaluated_kernel_variable.py
Since introducing `LazyEvaluatedKernelVariables`, it turns out we've always used the default `LazyVariable.exact_predictive_mean` and covar method. 
This made predictions a bit slower for SKI since we weren't taking full advantage of the caching abilities, and it also made LOVE predictions and sampling slower for SKI than it should have been / was in the paper.
This PR patches this by allowing kernels to specify that whatever they return has custom prediction code (which at the moment only applies to SKI). If we write another kernel with this property, then perhaps we can come up with a better solution then; for the moment, I'm going to merge this if everything passes, however, since it's a pretty serious performance bug for SKI.
@gpleiss
> Use InterpolatedLazyVariable prediction methods

- gpytorch/lazy/matmul_lazy_variable.py
- gpytorch/lazy/root_lazy_variable.py
- test/lazy/test_matmul_lazy_variable.py
- test/lazy/test_root_lazy_variable.py
- When calling `get_indices` with many indices, explicitly evaluate the LazyVariable.
- Remove old Variable references
`_get_indices` is called during the diag method for variational inference. If we want `m` indices, and the RootLazyVariable is a `n x r` matrix, then the standard `_get_indices` call requires `m * r` memory. If `m` is large (which is usually the case for variational), then this will be extremely memory intensive.
Fix: do whatever requires the least amount of memory:
- If `m * r` > `n x n`, then explicitly evaluate the LazyVariable and then call `_get_indices`.
- Otherwise, use the original `_get_indices` routine.
> Speed up Root/Matmul LV get_indices

- gpytorch/functions/__init__.py
- gpytorch/models/exact_gp.py
- gpytorch/settings.py
- test/examples/test_multitask_gp_regression.py
- test/examples/test_simple_gp_classification.py
- test/examples/test_simple_gp_regression.py
Can now construct an exact GP with `train_inputs=None, train_targets=None`.
That GP in `eval()` mode will return the prior
That GP in `train()` mode will return an error
Also introduces a debug mode, which suppresses warnings in exact GPs.
Cleans up some old pytorch 0.3 references in tests as well
Closes #173
> Prior mode for exact GPs

- .gitignore
- gpytorch/priors/__init__.py
- gpytorch/priors/lkj_prior.py
LKJCovariancePrior is added as prior for ICM kernel. It uses an LKJPrior over correlation matrices along with a prior for marginal standard deviations.
There is also an implementation of LKJCholeskyFactorPrior, which is basically the LKJPrior but over the Cholesky decompoosition, and it is unused currently.
> Added LKJCovariancePrior implementation

- gpytorch/lazy/lazy_variable.py
This PR detaches the mean and covariance caches computed at test time. This has two effects:
First and most importantly, backpropagating through GP predictions is bugged on master for things like BayesOpt. Specifically, a pattern like:
```python
from batch_acquisition import batch_expected_improvement
x = torch.tensor([0.25], requires_grad=True)
optimizer = torch.optim.Adam([x], lr=0.1)
for i in range(50):
optimizer.zero_grad()
loss = -batch_expected_improvement(x, model, 0)
print('Iter {}, loss = {}'.format(i, loss))
loss.backward()
optimizer.step()
```
throws a runtime error on master (technically the gpytorchopt branch), because the caches require grad due to the model parameters but aren't created by the call to the acquisition function. Therefore, when `backward()` is called, …
> Detach mean and covar caches at test time

- gpytorch/kernels/kernel.py
I think the requested changes are relatively straightforward. I ran into this when trying to evaluate individual components of an `AdditiveKernel` instance.
In the current master branch, if `x2_` is `None` when `active_dims` is set, `x2` never gets set, so the conditional at [line 112](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/kernel.py#L112) gets skipped over.
`AdditiveKernel` doesn't trigger this behavior because it passes `x1` and `x2` explicitly.
My proposed solution is to move the default case up to the front of the method, before the `active_dims` check.
> fix conditional in gpytorch.kernels.Kernel.__call__ when active_dims is set

- gpytorch/lazy/constant_mul_lazy_variable.py
`ConstantMulLazyVariable` now uses a torch scalar for its constant if there is only one element in the constant (e.g., not batch mode).
This fixes some bugs when back-propagating through samples on pytorch master. 
cc @Balandat
> ConstantMulLazyVariable now uses a scalar when appropriate

- gpytorch/lazy/root_lazy_variable.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/likelihoods/test_general_multitask_gaussian_likelihood.py
Updates:
- Changed parameter of MultitaskGaussianLikelihood to include a rank = `rank` noise covariance matrix, parameterized by its covariance factor `task_noise_covar_factor`. 
- The full covariance matrix is the `v v' + e`, where `v` is `task_noise_covar_factor` and `e` is the diagonal matrix whose elements are `log_noise.exp()`. This is computed in `_eval_covar_matrix`.
The purpose of these updates is to make the cross-task noise covariance matrix general, and not just diagonal.
> Generalized MultitaskGaussianLikelihood to include off-diagonal covariances for task noise

- gpytorch/priors/lkj_prior.py
This fixes the issue reported by @rajkumarkarthik offline. Not sure why this behavior before this change was different between CPU and GPU. I tried to dig a little to see whether the `torch.tensor` constructor works differently for the two, or if there are weird interactions between the device and registering buffers, but didn't find anything.
> Register eta paramerter in LKJ prior as float

- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/sum_lazy_variable.py
Fixes a small issue where detaching the LOVE cache for sum lazy variables needed to be special cased. We now detach in the correct method rather than in `exact_predictive_covar` directly.
> Fix cache detach for sum lazy variables

- gpytorch/kernels/rbf_kernel.py
- gpytorch/lazy/lazy_tensor.py
Pytorch 0.4.0 made some positive changes towards making writing device-agnostic code more convenient, as discussed in their migration guide. `LazyTensor.to` is intended to mirror `torch.Tensor.to`.
> Added device-agnostic .to method to specify LazyTensor device

- gpytorch/kernels/scale_kernel.py
On master, ScaleKernel's behavior in batch mode when getting only the diagonal of the kernel is broken for the same reason that other kernels are (see e.g. #249).
Here's some simple code that reproduces the error this PR fixes:
```python
covar_module = ScaleKernel(RBFKernel(batch_size=5), batch_size=5)
covar = covar_module(torch.randn(5, 20, 1))
diag = covar.diag() # fails because it returns a torch.Size(5, 20, 5) tensor
```
While we wait for the kernel refactor @gpleiss is working on, this PR fixes this issue by implementing a `forward_diag` method for ScaleKernel. An alternative fix would be to let outputscales be `torch.Size(5, 1, 1)` and allow `ConstantMulLazyTensors` to take batches of constants for batch lazy tensors.
> Fix diag calls to ScaleKernel in batch mode

- pyproject.toml
This allows to run black without having to specify the line length as an argument. 
The `pyproject.toml` file is more generally useful for setting other stuff as well.
> Add pyproject.toml with black linelength spec

- gpytorch/lazy/non_lazy_tensor.py
On master, `NonLazyTensors` don't benefit from preconditioning because they define a custom `add_diag` that returns a new `NonLazyTensor`. This turns out to be really really bad in some cases (most often the very low noise setting):
```python
M = RBFKernel()(torch.randn(1000, 1)).evaluate().cuda()
rhs = torch.randn(1000).cuda()
lv = NonLazyTensor(M).add_diag(torch.tensor(1e-3).cuda())
print(lv) # NonLazyTensor
solve_cg = lv.inv_matmul(rhs)
print(torch.norm((M + 1e-3 * torch.eye(1000).cuda()).matmul(solve_cg) - rhs).item()) # ~100 sometimes!
```
```python
M = RBFKernel()(torch.randn(1000, 1)).evaluate().cuda()
rhs = torch.randn(1000).cuda()
lv = NonLazyTensor(M).add_diag(torch.tensor(1e-3).cuda())
print(lv) # AddedDiagLazyTensor
solve_cg = lv.inv_matmul(rhs)
print(torch.norm((M + 1e-3 * …
```
> Use preconditioning for NonLazyTensors

- docs/source/kernels.rst
- gpytorch/kernels/additive_grid_interpolation_kernel.py
- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/utils/__init__.py
- gpytorch/utils/grid.py
- test/examples/test_kissgp_additive_regression.py
- test/examples/test_kissgp_dkl_regression.py
- test/examples/test_kissgp_gp_regression.py
- test/examples/test_kissgp_kronecker_product_regression.py
- test/examples/test_kissgp_multiplicative_regression.py
- test/examples/test_kissgp_white_noise_regression.py
- test/examples/test_kronecker_multitask_ski_gp_regression.py
- test/util/test_grid.py
For `GridInterpolationKernel` (and its variants), it is no longer necessary to pass in `grid_bounds`. They can be automatically determined by the data.
```python
grid_size = gpytorch.utils.grid.choose_grid_size(x, ratio=1.5)  # Simple helper function
kernel = GridInterpolationKernel(rbf_kernel, grid_size=grid_size, num_dim=1)
```
**Note** this probably will require some back-filled unit tests and some updated examples. I'll open a separate issue for those if it looks like we like this new interface
> Automatically determine grid bounds for SKI regression

- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/utils/__init__.py
- test/lazy/test_block_diag_lazy_tensor.py
- test/lazy/test_interpolated_lazy_tensor.py
- test/lazy/test_sum_batch_lazy_tensor.py
- test/lazy/test_toeplitz_lazy_tensor.py
- test/lazy/test_zero_lazy_tensor.py
This fixes #159, and is a step towards #236.
__getitem__ would fail for batch LazyTensors if you supplied two or more tensor-based indices. E.g. `lazy_tensor[torch.tensor([0, 0, 1]), torch.tensor([2, 1, 2]), :]`.
This fixes the default LT.__getitem__, all custom LT.__getitem__s, and adds a lot of unit tests.
> Fix LazyTensor.__getitem__

- gpytorch/priors/lkj_prior.py
- gpytorch/priors/smoothed_box_prior.py
- test/priors/test_lkj_prior.py
Makes sure LKJCovariancePrior works properly in batch mode.
Also adds the ability to have heterogeneous priors over the different
marginal variances (e.g. can use a sd_prior with event_shape that is
either 1 or n if the covariance matrices are n x n)
> Make LKJCovariancePrior work properly in batch mode

- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/models/exact_gp.py
- gpytorch/priors/lkj_prior.py
- test/examples/test_batch_gp_regression.py
- test/examples/test_batch_multitask_gp_regression.py
- test/examples/test_kissgp_variational_regression.py
- test/examples/test_spectral_mixture_gp_regression.py
- test/likelihoods/test_general_multitask_gaussian_likelihood.py
The following models work for ExactGPs and MultitaskGPs:
- Train on non-batch, test on batch
- Train on batch, test on batch (share hyperparameters across all batches)
- Train on batch, test on batch (different hyperparameters across batches)
This includes the following updates:
- IndexKernel and MultitaskKernel are now designed to work on batched data
- GaussianLikelihood now takes in a `batch_size` argument, which will (optionally) use different noise values for different batches
- MultitaskGaussianLikelihood also takes a `batch_size` argument, which also uses different noise values
Fixes #236
> Batch mode for (exact) regression model

- gpytorch/functions/_root_decomposition.py
This caused issues when computing the gradients of a function computed from the samples drawn from the posterior of a MTGP at a single point.
I'm kind of surprised that (at least locally) all tests pass, but oh well.
> Do not squeeze non-batch results in RootDecomposition backward

- gpytorch/distributions/multitask_multivariate_normal.py
- gpytorch/distributions/multivariate_normal.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/variational/mvn_variational_strategy.py
- test/distributions/test_multitask_multivariate_normal.py
- test/distributions/test_multivariate_normal.py
This moves the fast `log_prob` (previously in `ExactMarginalLogLikelihood`) and `kl_divergence` (previously in `MVNVariationalStrategy`) into `gpytorch.distributions.MultivariateNormal`.
> Use custom KL div and log_prob with gpytorch.distributions.MultivarateNormal

- gpytorch/lazy/matmul_lazy_tensor.py
On master, `MatmulLazyTensor.quad_form_derivative` fails if the sub lazy tensors return derivatives with mutliple components. This fixes the return value to merge the two derivative components in to a single tuple.
cc @Balandat
> Fix bug in MatmulLazyTensor derivative return

- gpytorch/lazy/lazy_tensor.py
- test/examples/test_svgp_gp_classification.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_interpolated_lazy_tensor.py
- test/lazy/test_matmul_lazy_tensor.py
- test/lazy/test_mul_lazy_tensor.py
Alright, this is going to be a fun one. 
This PR implements a default implementation of `LazyTensor._quad_form_derivative`. After playing around with it, this will have two huge advantages:
1. **Simplicity.** By far the most difficult method to implement when implementing a LazyTensor is the derivative portion. See for example the giant mess that is things like https://github.com/cornellius-gp/gpytorch/blob/9ebbf05e8ea70132dbcce25671bb06fa1721eb81/gpytorch/lazy/kronecker_product_lazy_tensor.py#L97
With this approach, implementing this from scratch becomes optional. Thus, we truly only need the end user to define a matmul if they want to implement a new LazyTensor.
2. **Speed.** I've been playing around with this for a bit, and initial results suggest that relying on `torch.autograd.grad` …
> [WIP] Default LazyTensor._quad_form_derivative implementation

- gpytorch/utils/interpolation.py
Fixes #250 . The issue has to do with what I think is strange behavior with calling `torch.nonzero` on scalars:
```python
test_scalar = torch.tensor(1.)
test_vec = torch.tensor([1.])
torch.nonzero(scalar) # Returns an empty tensor that can't be used for indexing
torch.nonzero(test_vec) # Returns torch.tensor([0], dtype=torch.int64)
```
Just trying to work through our back log of issues.
> Fix interpolation boundary with one test point

- gpytorch/functions/__init__.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/exact_gp.py
Mostly solves #340, with the one exception that I couldn't get it so that we don't have to replicate the caches for batch multitask. Specifically, batch multitask fails without: https://github.com/cornellius-gp/gpytorch/blob/85c4907cc9a8c49cc440d9c19bf7e788fd00ea1c/gpytorch/models/exact_gp.py#L132
Basically this PR makes two changes:
1. Two of the error checks in LazyTensor.matmul were outright wrong, in the sense that matmul with those sizes works perfectly fine on both standard tensors and lazy tensors. For example this works just fine for both tensors and lazy tensors, despite what the error check said:
```python
mat1 = torch.randn(3, 51, 100)
mat2 = torch.randn(100)
res = mat1.matmul(mat2) # Works fine
```
2. `exact_predictive_*` now just takes in `non_batch_train` if the train inputs …
> Fix batch vs standard prediction inconsistencies

- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- test/kernels/test_grid_kernel.py
GridKernel and GridInterpolationKernel both constructed the full dimensional grid of points despite clearly not needing them to function. I think this was an artifact from back when variational inference needed to know these things?
Either way, we obviously shouldn't be doing this because it requires O(dm^d) storage to store `inducing_points` compared to O(dm) storage to store `grid`.
Related to #344, this also dramatically simplifies usage of `GridKernel` for data that exactly lies on a grid by requiring a user to only specify the grid in each dimension.
> Improve GridKernel

- examples/02_Simple_GP_Classification/Simple_GP_Classification.ipynb
- examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Kronecker_Classification.ipynb
- gpytorch/models/abstract_variational_gp.py
- gpytorch/variational/variational_strategy.py
A few of the examples did not run correctly.  Specifically, the classification example expected at least a 2D input (batch x features) and the Kroenecker Classification seems to use an older import nomenclature.
> bug fixes for examples

- gpytorch/functions/__init__.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- test/lazy/test_batch_repeat_lazy_tensor.py
- BatchRepeatLazyTensor uses base_lazy_tensor's root decompositions
- DiagLazyTensor implements custom (faster) `inv_quad_log_det` and `inv_matmul`
- DiagLazyTensor (optionally) implements an exact root decomposition (with the `exact_root_decomposition=True` kwarg passed into the constructor)
- `gpytorch.add_diag` now works on regular torch.tensors
> Various LazyTensor fixes/improvements

- gpytorch/beta_features.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/utils/qr.py
- gpytorch/utils/svd.py
This adds optional default preconditioning for `LazyTensor.inv_matmul` (doesn't work for log dets) based on a fast randomized SVD algorithm. In other words: a preconditioner that can function even for non `AddedDiagLazyTensors`. It works quite well on a variety of matrices we end up with in practice. For example:
```python 
cov = GridInterpolationKernel(RBFKernel(), grid_size=100, num_dims=1)
n_x = 500
x = torch.randn(2, n_x, 1)
K = cov(x).evaluate_kernel()
b = torch.randn(2, n_x, 1)
sv1 = K.inv_matmul(b)
with gpytorch.beta_features.default_preconditioner():
sv2 = K.inv_matmul(b)
print(torch.norm(K.matmul(sv1) - b) / b.norm()) # 146.1651
print(torch.norm(K.matmul(sv2) - b) / b.norm()) # 0.9936
```
I don't think this will have much of an impact on our actual models in GPyTorch, because we …
> Optional default preconditioner for LazyTensors

- gpytorch/distributions/multivariate_normal.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/variational/variational_strategy.py
- test/examples/test_batch_svgp_gp_regression.py
- test/functions/test_root_decomposition.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_root_lazy_tensor.py
- test/lazy/test_toeplitz_lazy_tensor.py
- test/priors/test_multivariate_normal_prior.py
This builds off of #352 to make `root_decomposition` return a `RootLazyTensor` instead of an evaluated root directly. This has the advantage that lazy tensors with efficient root decompositions can build their own. 
Right now this improves the efficiency of `DiagLazyTensor` and `BatchRepeatLazyTensor`, and the stability of `DiagLazyTensor`.
In addition, `MulLazyTensor` special cases `DiagLazyTensor` roots to not evaluate the root.
@gpleiss
> root_decomposition returns a RootLazyTensor

- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/added_diag_lazy_tensor.py
This PR makes the GPyTorch internals handle NaNs that occur due to round-off from terrible hyperparameter values more gracefully. In particular:
- If the preconditioner contains NaNs, we throw a warning and attempt to continue without preconditioning. 
- In testing these NaNs appear somewhat intermittently such that even if one iteration fails due to it the next will often succeed. In @bletham's notebook this avoids crashing with learning rates well up in to the thousands (when combined with `param_transform=softplus` of course).
- If NaNs are encountered from CG outputs, these are handled more gracefully. 
- The linear solves already handle these gracefully in the sense that we don't try to do anything more than basic operations, so the inv quad term will already show up as NaN. All that …
> Handle NaN gracefully in loss computation.

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/mlls/variational_elbo.py
- gpytorch/module.py
- gpytorch/utils/transforms.py
This adds the ability to specify inverse parameter transforms, which allows setting parameters in the transformed space. 
This is also needed for sampling parameter values from their associated priors (see #381).
Main changes:
- many constructors take an (optional) arg `inv_param_transform`. For the basic ones like `torch.exp` and `torch.nn.functional.softplus`, there is a mapping the looks up the inverse transform if not specified. This can easily be extended to other common transforms. The inverse transform can always be passed in manually
- modules such as kernels and likelihoods now also have setters for their respective properties that take in a parameter value in transformed space, apply the inverse transform, and set the internal parameter represenation
- `register_prior` now also …
> Track inverse parameter transforms

- docs/source/conf.py
- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/module.py
- test/examples/test_batch_gp_regression.py
- test/examples/test_grid_gp_regression.py
- test/examples/test_kissgp_dkl_regression.py
- test/examples/test_kissgp_gp_regression.py
- test/examples/test_kissgp_white_noise_regression.py
- test/examples/test_simple_gp_regression.py
- test/examples/test_white_noise_regression.py
- test/kernels/test_additive_kernel.py
- test/kernels/test_rbf_kernel.py
This PR is intended to soft deprecate the use of `log_*` parameters in favor of `softplus` in as painless a way as possible, while preserving the ability to load models and use `Module.initialize`. Closes #386.
- All internal parameters named `log_*` are now `raw_*` to signify that they are just untransformed and not necessarily in log space.
- The default value for `param_transform` has been changed to `softplus` everywhere.
- Accessing `module.log_*` (e.g. `model.covar_module.log_outputscale`). This returns the log of the outputscale and raises a deprecation warning.
- Initializing via `model.covar_module.initialize(log_outputscale=-3)`. This still works. In general, I think we should transition to initializing the actual parameter value (e.g. `.initialize(outputscale=...)`).
- Loading …
> Deprecate log parameters, use softplus as default transform to ensure positive parameters

- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/likelihoods/gaussian_likelihood.py
My attempt at addressing #398, plus adding a check in AddedDiagLazyTensor that will fail if this ever happens again.
I think the issue is multi-task vs not: in Multitask the mean is `b x n x t` but in standard GP regression the mean is `b x n`.
cc/ @Balandat if you have a better solution, feel free to close this or add on to it.
> Fix shaping of noise_covar in GaussianLikelihood

- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/models/pyro_variational_gp.py
- gpytorch/variational/cholesky_variational_distribution.py
There is a better fix for batch VGP models with Pyro, but this is a simple solution for right now.
All batch Gaussian distributions touched by Pyro (`p_u`, `q_u`, `q_f`) are all converted into non-batch variational distributions using a BlockDiagLazyTensor. This has no effect on the `log_prob` or `kl_divergence` terms in the equations.
> Pyro can handle batch models

- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/matmul_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_batch_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/lazy/toeplitz_lazy_tensor.py
`_get_indices` now (in theory) supports an arbitrary number of batch dimensions. This PR uses `_get_indices` everywhere now, and remove the `_batch_get_indices` method from LazyTensors.
In practice, most LazyTensors only support 0 or 1 batch dimensions. However, this sets the infrastructure up for future LazyTensors that use multiple batch dimensions.
A step towards achieving #369
> Remove _batch_get_indices function from LazyTensors

- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/matmul_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_batch_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/lazy/toeplitz_lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/variational/variational_strategy.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_zero_lazy_tensor.py
**MERGE #394 FIRST**
We can now write calls like `lazy_tensor[..., 4:, 3]`. This reduces the amount of casing we do checking for batch dimensions. It will also make it much easier to write multi-batch functions for LazyTensors.
A step towards #369
> LazyTensor.__getitem__ supports ellipsis

- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- test/lazy/test_zero_lazy_tensor.py
A more stable version of yesterday's hotfix.
`LazyTensor.__getitem__` now calls a `LazyTensor._getitem` helper (similar to how `LazyTensor.size` calls `LazyTensor._size`). When `LazyTensor._getitem` is called, there is:
- One index per dimension (unsupplied indices are filled with `slice(None, None, None)`.
- Each index is an int, a slice, or a LongTensor (all lists, Ellipsis have been processed out).
LTs that had custom `__getitem__`s now have custom `_getitem`s. This is a pure refactor - no new functionality (except for `ConstantMulLazyTensor`, which is now a bit more stable). This significantly reduces repeated code.
> Improve LazyTensor.__getitem__

- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/settings.py
- test/functions/test_inv_quad_log_det.py
This is going to be a not-highly-advertised feature.
This PR introduces `gpytorch.settings.skip_logdet_forward`. Setting this to True makes `LazyTensor.logdet` return a zero tensor, but one that does the correct thing on the backward pass.
This allows advanced users (like us 😁) to get much faster performance for hyperparameter optimization. If we're using a single-order method - we don't actually care about the logdet value - we just care about its derivatives. This settings will allow us to skip unnecessary forward-pass computation.
Fixes #396
> Option to skip LazyTensor.logdet forward pass

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
- gpytorch/module.py
- test/kernels/test_rbf_kernel.py
- test/kernels/test_scale_kernel.py
Fixes #405 
You can now initialize transformed model parameters with their actual values. For example:
```python
kernel = RBFKernel()
kernel.initialize(lengthscale=3.14)
print(kernel.lengthscale)  # 3.14
```
More generally, in addition to parameters, `Module.initialize` now works with any keyword argument specifying a named `@property` with a defined setter.
cc/ @gpleiss
> Module.initialize can now initialize real parameter values

- gpytorch/distributions/multivariate_normal.py
The high-level goal of this PR is to allow using deterministic optimization algorithms on a MC-sampled objective in BayesOpt. Our acquisition functions just depend on calls to `rsample` of a posterior that is a function of varying `X`. By utilizing a fixed base_samples this function can be made deterministic with respect to `X`.  Since the `root_decomposition` generated is a low-rank approximation with dynamic rank, we need to make sure matrix dimensions agree when we correlate the samples. This is what this PR does.
With this change things are deterministic w.r.t. `X` conditional on the initial draw of `base_samples`, but may not be truly differentiable with respect to `X` since the covariance root rank is determined dynamically. This might be acceptable though since if the covariance …
> Subset base_samples if required by rank of root_decompisition

- gpytorch/lazy/lazy_tensor.py
This fixes an edge case in which the sequence of operations `batch eval -> non-batch eval` on a non-batch model failed (the reverse sequence succeeded).
This special casing is starting to get a little hairy... Not sure if there is a good way of simplifying this. Maybe one way would be to factor out all these check into some utility that takes the `precomputed_cache` and does the appropriate things to it, so the rest of the code can remain relatively clean? 
cc @sdaulton, @bkarrer
> Catch an edge case with batch-> non-batch eval

- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/matmul_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/utils/__init__.py
- gpytorch/utils/memoize.py
Useful for things like `evaluate()` etc.
See discussion here: https://github.com/cornellius-gp/gpytorch/commit/7570ee1d758c93dd4054009fc12be6cc31b54031#r31576790
We can extend this to other cases where want to do caching, we just need to be careful about not messing with autograd by doing that.
> Simple decorator for caching instance methods w/o args

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
This fixes an issue if `MultitaskGaussianLikelihoodKronecker` is used with `torch.double` dtype
> Fix dtype bug in MultitaskGaussianLikelihoodKronecker

- README.md
- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/utils/memoize.py
Step two towards handling fantasy observations.
- `mean_cache` and `covar_cache` are now properties of `PredictionStrategies`, and `ExactGP` caches a prediction strategy rather than the mean and covariance caches.
- Introduces a new `named_cached` decorator that allows us to specify string names for the cache storage, which lets us modify the cache later. Right now, this is used once in `InterpolatedLazyTensor` to delete the covar cache if the beta features (`fast_pred_var` / `fast_pred_samples` have changed). 
- `PredictionStrategy` objects are now created using all relevant test independent items, simplifying the interface of `exact_predictive_mean` and `exact_predictive_covar`.
- `train_train_covar` is now also cached, avoiding computing the train-train covariance matrix a second time. …
> Refactor caches to live in PredictionStrategy

- gpytorch/models/exact_gp.py
Fixes a minor issue @keawang was having where if you make `train_x` and `train_y` parameters of a module before passing them in to the GP, doing `self.train_targets = train_targets` would also register them with the GP.
This doesn't happen for `train_inputs` because `train_inputs` is always a tuple, so doesn't trigger the special `torch.nn.Module.__setattr__` behavior.
I fixed this by creating a custom setter and getter for `train_targets`
cc/ @gpleiss
> If train_targets is a parameter, dont register it with Model

- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
- test/examples/test_batch_gp_regression.py
- test/models/_model_test_case.py
- test/models/test_exact_gp.py
- test/models/test_variational_gp.py
This PR dramatically simplifies the batch + multitask checks we did in `ExactGP.__call__` to three lines of code. In addition, it makes progress on handling arbitrary batch dimensions by not explicitly assuming only the first dimension is a batch dimension.
This also fixes a bug where we need to update the PredictiveStrategy objects if we expand the train objects to match batch mode test data. We also now use a BatchRepeatLazyTensor to expand `train_train_covar` if needed.
I also added unit test coverage to `test_batch_gp_regerssion` to make sure this doesn't happen again.
> Simplify and fix batch mode checks

- gpytorch/models/exact_prediction_strategies.py
- gpytorch/settings.py
On master, if you ever need derivatives with respect to *training* inputs at test time, that will not work properly because we detach the training dependent caches we use for predictions. Derivatives with respect to test inputs work just fine.
On the other hand, not detaching the caches by default can lead to performance issues and issues with needing to retain the graph unnecessarily.
To solve this, I've introduced a `detach_test_caches` option that is enabled by default. By disabling this, it is possible to get derivatives with respect to training inputs.
To allow derivatives with respect to the training inputs, just do:
```python
with gpytorch.settings.detach_test_caches(False):
...
```
@Balandat This was actually broken before the predictions got moved out: we still detached the …
> Add option to not detach test caches

- gpytorch/utils/pivoted_cholesky.py
Prevents pivoted Cholesky from terminating too soon on matrices with very small diagonals.
> Normalize error for pivoted Cholesky

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- test/kernels/test_grid_kernel.py
We were trying to be too clean with recent changes to kernel computations for our own good with using `create_input_grid`, and ended up using `O(dn^2)` memory accidentally. This makes our kernels correctly use `O(n^2)` memory (for exact GPs).
An example of the difference this makes is that exact GPs can be run on the `elevators` dataset after the fix but not before it.
> Fix kernel memory usage

- gpytorch/functions/_matmul.py
- gpytorch/functions/_root_decomposition.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/settings.py
- gpytorch/utils/memoize.py
- test/examples/test_simple_gp_regression.py
At long last!
Adds official support for updating an `ExactGP` with fantasy observations:
```python
test_x = torch.linspace(0, 1, 51)
observed_pred = likelihood(model(test_x))
...
fant_model = model.get_fantasy_model(fantasy_x, fantasy_y)
observed_pred = likelihood(fant_model(test_x))
```
The `get_fantasy_model` method returns a copy of `model` with `train_targets`, `train_inputs`, and `prediction_strategy` updated to account for the fantasy data being added to the training set. At the moment, the mean cache is using an efficient bordered linear system solve, rather than computed from scratch. Covariance cache updates are coming soon
- Add support for adding fantasies to multi-task GPs (really easy, just want to keep the PR small).
- Add support for models that use …
> Add interface for fantasy observations and efficient cache updates

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
Reverts cornellius-gp/gpytorch#434
Obviously correctness is more important than memory usage, so let's just revert the PR and re-open it until we're satisfied that it is numerically stable as well as memory efficient (#438).
> Revert "Fix kernel memory usage"

- gpytorch/lazy/lazy_tensor.py
Minor change, this just exploits the fact that indexing with torch scalars and ints have the same behavior (specifically, they both squeeze):
```python
foo = torch.randn(3, 3)
a = foo[torch.tensor(1), :]  # torch.Size([3])
b = foo[1, :]  # torch.Size([3])
c = foo[[1], :]  # torch.Size([1, 3])
```
Since they have the same behavior, I added a conversion from scalars to ints so we can process them the same way downstream. I don't think this is useful for any of the `_getitem` definitions we currently have, but it turns out to be very convenient for one we are working on.
> Convert scalar tensors to ints in __getitem__

- gpytorch/__init__.py
- gpytorch/distributions/multivariate_normal.py
- gpytorch/functions/__init__.py
- gpytorch/functions/_root_decomposition.py
- gpytorch/kernels/additive_structure_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/kernels/product_structure_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/matmul_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/settings.py
- gpytorch/utils/pivoted_cholesky.py
- gpytorch/variational/cholesky_variational_distribution.py
This PR does two things:
- Prevents nested kernels from creating nestings of `LazyEvaluatedKernelTensors`. Now only the outermost kernel wraps the output in one of these.
- Introduces `lazify` and `delazify` helper method. They do what they sound like they do, and can operate on regular Tensors and LazyTensors.
This doesn't change any behavior (kernels are lazily evaluated still). However, it prevents lots of bugs associated with nested kernels. In addition, it is now possible to turn off lazy kernel evaluation (for debugging) using the context manager `gpytorch.settings.lazily_evaluate_kernels(False)`.
> Make "lazify/delazify" helpers, better lazy kernel evaluation

- gpytorch/mlls/variational_elbo.py
- gpytorch/variational/variational_strategy.py
- test/examples/test_batch_svgp_gp_regression.py
Right now when using variational GPs with non-gridded inducing points in batch mode, we implicitly require that all GPs have independent inducing point locations by requiring the inducing points to be batch (`b x n x d`) when supplied to the model.
This PR allows the batch GPs to share inducing point locations by passing in a non-batched set of inducing points (see the unit test for an example). Note that the `VariationalDistribution` should still be made with `batch_size=b`, because unless the `b` functions are all identical the variational parameters `q(f)` should not be shared.
cc/ @martinjankowiak
> Inducing point locations can be non-batch for batch variational GPs

- gpytorch/distributions/multivariate_normal.py
- gpytorch/functions/__init__.py
- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/cached_cg_lazy_tensor.py
- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/variational/variational_strategy.py
- test/examples/test_batch_svgp_gp_regression.py
- test/examples/test_svgp_gp_regression.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_cached_cg_lazy_tensor.py
This PR introduces `CachedCGLazyTensor`, which caches the solves that are performed by CG. This improves the speed of variational models. Variational models now call CG 1 time per ELBO computation rather than 3 times.
> Cache solves for fast variational

- gpytorch/distributions/multivariate_normal.py
- gpytorch/settings.py
- test/examples/test_simple_gp_regression.py
Extension of #441 
Setting `gpytorch.settings.fast_computations(log_prob=False)` will use the Cholesky decomposition for computing the exact marginal log likelihood of GPs.
(Not recommended for performance, but useful for debugging).
> Setting for exact logprob computations

- meta.yaml
Addresses #460.
A couple notes on the conda build file:
- It gets package version info from `setup.py`, so most routine releases shouldn't require `meta.yaml` to be modified.
- It does not get dependencies from `setup.py`, so adding dependencies *will* require `meta.yaml` to be modified. This should happen only rarely.
- The testing is minimal; it only makes sure the package imports correctly. This speeds up the build and avoids duplicating the unit tests run on Travis. 
- The build only supports *NIX (to avoid `setup.bat` clutter) but the package is type "noarch" so it will work on all platforms. 
I didn't see any code to automatically deploy to PyPI, so I didn't add anything to automatically deploy to Anaconda Cloud. In any case the manual deployment process is easy--`conda-build` …
> Add meta.yaml for conda build

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
Prior to this, MTMVNs would return the event shape of the underlying MVN representation, which is not the shape that (r)sample would return.
> Add event_shape property to MTMVN

- gpytorch/distributions/multitask_multivariate_normal.py
Useful when combining posteriors for multiple models evaluated at the same points into a single `MultiTaskMultivariateNormal` from which it's easy to sample etc.
The current implementation is inefficient, a better way will be to combine the individual `lazy_covariance_matrix` `LazyTensors` into a `BlockDiagLazyTensor` without evaluating them. See #468
> Convenience method for creating a MTMVNs from independent MVNs

- gpytorch/lazy/block_diag_lazy_tensor.py
This will speed up things significantly when called with `settings.fast_computations(covar_root_decomposition=False)`
See #465
> Smarter root_decomposition for BlockDiagLazyTensor

- gpytorch/kernels/kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/utils/linear_cg.py
- test/kernels/test_grid_kernel.py
TL;DR: Reduces the memory overhead of kernels (and therefore exact GPs) by ~3x when using squared distances, reduces the memory usage of RBFKernel specifically by ~4x.
- `__slow_sq_dist` is now `__jit_sq_dist` and uses the torch JIT script functionality. This is around as fast as `torch.pdist(...).pow_(2)`, but (a) uses much less memory than `torch.pdist` surprisingly, and (b) uses around 3x less memory than `__slow_sq_dist`.
- Kernels can now pass a `jit_func` to `covar_dist`. If they do, this JIT function is called in non-diag mode instead of doing the distance computation at all. This is useful if the Kernel is just the distance plus a few steps, because the few extra steps can just be thrown in the JIT function which saves memory.
- Use torch.pdist in the `elif not square_dist` branch …
> JIT for distance computation, more efficient Matern kernel, JIT scripted linear CG

- gpytorch/kernels/inducing_point_kernel.py
- test/examples/test_sgpr_regression.py
Right now, InducingPointKernel unintentionally gets the diagonal correction by calling the kernel on the full data and then calling `diag` rather than calling the kernel with `diag=True`:
https://github.com/cornellius-gp/gpytorch/blob/4e30c948055e20c35b11e7435e8eba673a7f3401/gpytorch/kernels/inducing_point_kernel.py#L63
This has clearly unintended ramifications for memory usage and speed. While I was at it, I also changed `_inducing_inv_root` to take advantage of the fact that `torch.cholesky` now operates in batch mode.
> Fix InducingPointKernel memory usage and speed

- gpytorch/kernels/multi_device_kernel.py
- gpytorch/lazy/cat_lazy_tensor.py
Warm up MultiDeviceKernel to reduce first scatter time by 1000x.
Before we were taking 22 seconds to scatter a tensor of size `[1, 4882, 20]` in the first forward method. This offloads that 22 seconds to the initialization of MultiDeviceKernel by creating the CUDA context during initialization (can be turned off with a kwarg). 
With this change, the first time we call scatter in a forward pass takes only 0.02 seconds. This makes
GP training on 8 GPUs only twice as slow as GP training on 1 GPU if we don't measure the initialization time of MultiDeviceKernel
> Faster multidevicekernel

- gpytorch/distributions/multivariate_normal.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/psd_sum_lazy_tensor.py
- gpytorch/lazy/sum_batch_lazy_tensor.py
- test/lazy/_lazy_tensor_test_case.py
(Same thing as #480, but onto the batch lazy tensor PR WIP)
Makes this consistent with the torch interface, declutters some of the special casing by using shape arithmetic. This will be useful whenutilizing QMC base samples, in which case we can't just reshape
everyting into a big tensor but have to comply with batch / sample shape (because samples are not iid anymore).
It also enables sampling from multi-dimensional batch shapes in LazyTensors (once those are fully supported)
> Make zero_mean_mvn samples work with arbirary sample_shapes (onto batch_lazy_tensor PR)

- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/utils/cholesky.py
- test/utils/test_cholesky.py
`psd_safe_cholesky` is a simple wrapper around `torch.cholesky` that adds jitter if the matrix is not p.d.. If computing `torch.cholesky` on that still fails a `RuntimeError` is raised. This also hackfixes the  newly discovered pytorch bug: https://github.com/pytorch/pytorch/issues/16780
> Wrapper around cholesky to automatically add jitter if matrix is not p.d.

- gpytorch/kernels/kernel.py
- gpytorch/kernels/rbf_kernel.py
This commit (mostly) fixes issue #503. Now we cache the distance_module
the first time covar_dist is called. This way the JIT no longer
recompiles the module every time.
Unfortunately, it is still about 100us slower than what it was before
the breaking commit 0ff6416, with 0.0013s per forward pass instead of
0.0012s (about 8% slower).
> Fix slowdown of covar_dist

- gpytorch/kernels/kernel.py
We're no longer using `torch.pdist` anywhere in our kernel functions. I'm removing this function for now. We can re-open once the pdist bug is fixed.
> Remove unused __pdist_dist

- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/lazy_tensor.py
- test/examples/test_grid_gp_regression.py
For some reason, using the preconditioner in conjunction with the default _getitem causes an autograd error. We definitely should not be computing the backward pass of the preconditioner anyways.
This ensures that the preconditioner is detached and that we are not computing its backwards pass.
Closes #501
> Fix autograd bug with preconditioner, default _getitem

- docs/requirements.txt
- gpytorch/__init__.py
- setup.py
setup.py now does the following:
- Includes optional dependencies (for code formatting, examples, tests, doc building, Pyro integration) in `extra_requires`
- Reads requirements from appropriate `requirements.txt` (for less duplication)
- Does not require `torch` if `pytorch-nightly` is installed.
> Improve setup.py

- test/_utils.py
- test/examples/test_svgp_gp_regression.py
This is helpful for avoiding OOMs when running a bunch of cuda tests in parallel on a multi-GPU machine.
This is just a proof of concept, if this seems reasonable I'll add it to all of the cuda tests.
> Add context manager for selecting min mem cuda device

- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/utils/pivoted_cholesky.py
- gpytorch/utils/woodbury.py
- test/utils/test_pivoted_cholesky.py
This PR does several things:
- Use lower-level BLAS calls for the woodbury formula. This improves the speed slightly
- Use lower-level BLAS calls for AddedDiagLazyTensor._matmul (the matmul function we use the most out of any LazyTensor)
- Move all woodbury stuff into its own file (we'll probably be reusing it for some future preconditioners and stuff)
The big thing that this PR does:
- Scale the diagonal component of the woodbury formula by its' smallest number. When the diagonal component of woodbury is very small, it's possible that dividing by the diagonal could be numerically unstable. This PR should improve stability by scaling before applying the formula and undoing the scale after.
> Improve speed, stability of woodbury for preconditioner

- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/settings.py
- gpytorch/utils/linear_cg.py
- test/examples/test_simple_gp_regression.py
- test/lazy/_lazy_tensor_test_case.py
- Adds back CG tolerance checking (which somehow got removed by the JIT PR)
- Increases max CG iterations and preconditioner size, but lowers CG tolerance to more realistic values. This way, we terminate when we hit the tolerance, not when we hit the specified CG iterations.
- CG tolerance is now a setting
- In Lazy Tensor unit tests, test diff of inv_quad and logdet terms separately, logdet being large was masking some bad inv_quad results.
- Fix test that was "very nearly" failing.
> Improve linear CG stability via tolerance termination

- gpytorch/distributions/multitask_multivariate_normal.py
- gpytorch/distributions/multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
- test/distributions/test_multivariate_normal.py
This adds an `interleaved` flag to the MTMVN constructor (defaults to True).
- If True, covariance matrix is interpreted as block-diagonal w.r.t. inter-task covariances for each observation. This is the status quo behavior.
- If False, it is interpreted as block-diagonal w.r.t. inter-observation covariance for each task. This makes it much easier to construct a MTMVN from independent MVNs. It also potentially allows for more efficient computations by exploiting structure more effectively. For instance the internal covariance matrix generated by `from_independent_mvns` is now block-diagonal, so it can be efficiently cholesky-decomposed in batch mode (this is handled inside the LazyTensor implementation).
This also cleans up and streamlines some code, and improves test coverage (in …
> Add interleaved option to MTMVN

- gpytorch/kernels/kernel.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- Fixes #527: `ProductKernel` now evaluates to `NonLazyTensors` in the rectangular or nonsymmetric case, since the use of `MulLazyTensor` is not applicable.
- `NonLazyTensor` now overrides `__add__` and `mul` so that adding or elementwise multiplying against another `NonLazyTensor` produces another `NonLazyTensor`. Having a `SumLazyTensor` that consists only of `NonLazyTensors` is unnecessarily slow in CG.
The merger of `__mul__` and `mul` here in `LazyTensor` very minorly conflicts with the same operation done on #492, but I am strongly in favor of merging this before #492.
> Improve kernel compositions, fix ProductKernel for non-symmetric case.

- gpytorch/distributions/multitask_multivariate_normal.py
This was overlooked in the previous fix
> Fix index for get_base_samples in interleaved MTMVN

- gpytorch/utils/eig.py
`type_as` does not retain the cuda device index, so the output for small matrices (cpu computation) will be on the default cuda device rather than the one of the input matrix.
> Fix batch_symeig cuda index issue

- gpytorch/models/exact_gp.py
Right now if (for whatever reason) someone makes predictions with an exact GP before loading hyperparameters from a saved state dict, the test time caches will incorrectly have been computed with the wrong hyperparameters.
This PR makes exact GPs clear test time caches whenever hyperparameters are loaded.
> Clear test time caches when loading saved models.

- gpytorch/lazy/lazy_tensor.py
Versions:
python - 3.7.0
pytorch-nightly - 1.0.0.dev20190201
gpytorch - master (commit [b04c7e43293da18f630eb4ec483906a75ec72929](https://github.com/samuelstanton/gpytorch/commit/b04c7e43293da18f630eb4ec483906a75ec72929))
Motivation:
It's often desirable to preprocess training inputs and targets by mean subtracting and scaling by the standard deviation. Of course post-prediction you have to account for this by adding back the target mean to the rescaled predictive means and rescaling the predictive variances. In the batch setting this translates to multiplying the `[b x t x t]` test covariance lazy tensor by a `[b]` dimensional scaling tensor
Issue: 
To perform this multiplication on a tensor, you would have
```
import torch
a = torch.rand(2, 3, 3)
b = torch.rand(2, 1, 1)
prod = a.mul(b) …
```
> fix mul shape broadcasting in batch mode

- gpytorch/models/exact_gp.py
It appears valid for a GP to have its training inputs/labels set to `None`. However, if you call `set_train_data` when the current training inputs are `None`, you'll get an error at `for input, t_input in zip(inputs, self.train_inputs)` (because `None` is not iterable and thus can't be `zip`ped). This PR moves the check for `if strict` up so that, if `strict == False`, the entire checking section is skipped and it doesn't matter whether the training data was `None` or not.
When `strict == True`, the error messages have been improved a bit. Now they'll say both what the expected attribute (e.g. shape) was and what shape was found. To get a more informative error, I also ensured that if the training inputs/targets are `None`, the shape, etc. will be viewed as `None` so you'll still get the …
> Fix bug in setting training data for ExactGP if training inputs are None

- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
This fixes #554 by correctly detaching `train_train_covar` and ensuring that the pass through the likelihood happens in a `torch.no_grad` context if `gpytorch.settings.detach_test_caches` is on.
cc/ @Balandat @sdaulton
> Detach train_train_covar for slow variance computation if requested.

- gpytorch/beta_features.py
- gpytorch/kernels/kernel.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/lazy_tensor_representation_tree.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/utils/cholesky.py
- gpytorch/utils/memoize.py
- gpytorch/utils/pivoted_cholesky.py
- gpytorch/variational/variational_strategy.py
- gpytorch/variational/whitened_variational_strategy.py
- test/examples/test_simple_gp_regression.py
This PR enables implicitly computing kernel matrices through MVMs. It computes the kernel in batches, trading of time for memory.
This feature is activated by using `with gpytorch.beta_features.checkpoint_kernel(<value>)`
> Kernel checkpointing

- README.md
- gpytorch/functions/__init__.py
- gpytorch/functions/matern_covariance.py
- gpytorch/functions/rbf_covariance.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/rbf_kernel.py
- test/functions/test_matern_covariance.py
- test/functions/test_rbf_covariance.py
This pull request tries to reduce the memory requirements of a RBFKernel and a MaternKernel by introducing a custom backward function when the lengthscales require grad.
ARD is not yet implemented because I'm not sure if there's a better way to do it than to create a distance matrix for each dimension (resulting in a 3D Tensor) since we need gradients of a 2D Tensor with respect to each of the lengthscales.
> Custom RBF and Matern Functions

- gpytorch/models/exact_gp.py
- gpytorch/settings.py
- gpytorch/utils/linear_cg.py
This PR makes the following changes:
- Separate the CG tolerance used for predictions from the one used for training.
- Set CG tolerances for training and prediction based on performance using a battery of benchmark datasets.
- Increase the maximum number of CG iterations to 1000 so that we essentially never terminate due to reaching the maximum, which is not desirable.
- Linear CG now throws a warning whenever termination happened due to reaching the maximum number of iterations, and suggests a course of action (increasing it).
This had essentially 0 effect on the running times of our unit tests (<1s) compared to master, but should significantly improve the package's ability to automatically adjust to the poorly conditioned kernel matrix setting by spending more time where necessary. By …
> CG Improvements

- gpytorch/utils/linear_cg.py
Right now CG will warn the user if the tolerance is not reached. However the warning can be made more useful by also letting the user know how bad the residual is. 
Sometimes it's important to know if the residual is massive (like 100x the tolerance) or if the residual is only slightly above the tolerance.
> Make the CG termination warning more useful by showing residuals

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- test/kernels/_base_kernel_test_case.py
- test/kernels/test_linear_kernel.py
- test/kernels/test_matern_kernel.py
- test/kernels/test_rbf_kernel.py
Right now in certain cases we are trying to slice the data to restrict it to the `active_dims` argument twice for kernels: once when the kernel is first called, and again when the kernel is actually evaluated.
We should not do this.
Fixes #575 
cc/ @Duane321
> Dont apply active dims twice when doing lazy eval

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/rbf_kernel_grad.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/utils/broadcasting.py
- gpytorch/utils/deprecation.py
- test/kernels/_base_kernel_test_case.py
- test/kernels/test_linear_kernel.py
- test/kernels/test_matern_kernel.py
- test/kernels/test_rbf_kernel.py
First of a few PRs to support multiple batch dimensions throughout GPyTorch. This specifically adds support to most of the base kernels.
- Simplifies kernel constructors to not repeat work done in the Kernel constructor. This includes collapsing unused args in to **kwargs. The argument for doing this is that the kernels were extremely inconsistent about which super args they explicitly took in the first place. If we want them expanded back out, there should at least be consistency.
- Nearly all base kernels + ScaleKernel now support multiple batch dimension inputs.
- `batch_size` kernel argument has been deprecated in favor of `batch_shape`, which takes a `torch.Size` and is used to make multibatch lengthscales etc.
- Added a battery of unit tests for batch and multibatch kernel calling …
> Support for multiple batch dimensions in *base* kernels

- .travis.yml
- readthedocs.yml
I believe this is the minimal change necessary to get readthedocs to build on python 3.6. See http://blog.readthedocs.com/python-36-support/
> Update readthedocs to use python 3.6

- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/functions/_root_decomposition.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/cached_cg_lazy_tensor.py
- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/settings.py
- gpytorch/utils/memoize.py
- gpytorch/variational/variational_strategy.py
- gpytorch/variational/whitened_variational_strategy.py
- test/_base_test_case.py
- test/examples/test_svgp_gp_regression.py
- test/examples/test_whitened_svgp_gp_regression.py
- test/functions/test_inv_quad.py
- test/functions/test_inv_quad_log_det.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_cached_cg_lazy_tensor.py
- test/lazy/test_chol_lazy_tensor.py
- test/lazy/test_diag_lazy_tensor.py
- test/lazy/test_kronecker_product_lazy_tensor.py
- test/lazy/test_mul_lazy_tensor.py
- test/lazy/test_root_lazy_tensor.py
This PR does a few things:
Cholesky is faster and more efficient than CG with `n <= 300` (see #585)
> Better Cholesky methods for use in small data regimes and for debugging

- gpytorch/utils/cholesky.py
- gpytorch/variational/variational_strategy.py
- test/utils/test_cholesky.py
This PR makes two improvements:
1. If `psd_safe_cholesky` cant produce a positive definite matrix by adding jitter, it now tries to add increasing amounts of jitter for a few times to see if that will work.
2.  Our variational parameter initialization now uses `psd_safe_cholesky` instead of `torch.cholesky` by specifying `scale_tril`.
> Better psd_safe_cholesky, VI initialization

- docs/source/constraints.rst
- docs/source/index.rst
- examples/05_Scalable_GP_Regression_Multidimensional/SVDKL_Regression_GridInterp_CUDA.ipynb
- examples/05_Scalable_GP_Regression_Multidimensional/SVDKL_Regression_SVGP_CUDA.ipynb
- gpytorch/constraints/__init__.py
- gpytorch/constraints/constraints.py
- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/rbf_kernel_grad.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
- gpytorch/module.py
- gpytorch/utils/transforms.py
- test/constraints/test_constraints.py
- test/distributions/test_multivariate_normal.py
- test/examples/test_simple_gp_regression.py
- test/examples/test_svgp_gp_regression.py
- test/examples/test_white_noise_regression.py
- test/examples/test_whitened_svgp_gp_regression.py
- test/functions/test_inv_quad_log_det.py
- test/lazy/_lazy_tensor_test_case.py
This is a refactor of `param_transform` to be first class `Constraint` objects that get registered to GPyTorch modules. The idea is that `gpytorch.Module` exposes a `register_constraint` method so that the following all work:
```python
self.covar_module.register_constraint("raw_lengthscale", Positive())
self.covar_module.register_constraint("raw_lengthscale", GreaterThan(1.))
self.covar_module.register_constraint("raw_lengthscale", LessThan(5.))
self.covar_module.register_constraint("raw_lengthscale", Interval(1., 5.))
print(list(self.named_constraints()))
self.covar_module.register_constraint("raw_lengthscale", Positive(transform=torch.exp))
...
```
The idea is that the `param_transforms` are now handled by registering default `Positive` constraints on the parameters that need it, …
> Implement parameter constraints, default noise lower bound

- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/lazy_tensor.py
Two changes in this PR:
- InvMatmul, InvQuadLogDet, and InvQuad now use the PyTorch 1.0.0 style function definition instead of the legacy definition.
- InvMatmul now calls `InvMatmul.apply` in the backward pass solve rather than `_solve` directly so that in a second derivative call we don't back prop through CG.
As a result of these changes, all three functions are now twice differentiable with respect to the lazy tensor args.
cc/ @martinjankowiak
> Make InvMatmul, InvQuadLogDet, and InvQuad twice differentiable

- gpytorch/distributions/multivariate_normal.py
- gpytorch/kernels/additive_structure_kernel.py
- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/product_structure_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/rbf_kernel_grad.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/kernels/white_noise_kernel.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/utils/broadcasting.py
- test/examples/test_batch_gp_regression.py
- test/examples/test_batch_multitask_gp_regression.py
- test/examples/test_grid_gp_regression.py
- test/kernels/test_cosine_kernel.py
- test/kernels/test_linear_kernel.py
- test/kernels/test_matern_kernel.py
- test/kernels/test_rbf_kernel.py
- test/kernels/test_scale_kernel.py
- test/kernels/test_spectral_mixture_kernel.py
- test/kernels/test_white_noise_kernel.py
Right now the default batch shape for kernels is `torch.Size([1])`, with some squeezing if the data is not supplied as batch data.
This makes the default `batch_shape=torch.Size([])`. Saved models with the old default batch shape still load (with deprecation warning).
(Note that this speeds up evaluation quite a bit with small amounts of data).
> Remove default batch dimension from kernels

- gpytorch/lazy/added_diag_lazy_tensor.py
- test/utils/test_pivoted_cholesky.py
- Applying the pivoted Cholesky preconditioner is much more accurate via the QR factorization
- `torch.qr` doesn't support batch, so SMW is still used in the batch setting
> Replacing SMW solve in pivoted Cholesky with a more stable QR version

- gpytorch/constraints/constraints.py
- gpytorch/module.py
- test/kernels/_base_kernel_test_case.py
Right now, initializing a parameter to a value that is out of its constraint bounds silently initializes it to NaN. For example:
```python
likelihood = GaussianLikelihood(noise_constraint=GreaterThan(1e-4))  # This is the default
likelihood.noise = 1e-5  # Out of bounds! Noise value is now nan with no error.
```
We now throw an error with a suggestion for what to do in the likelihood case specifically, because that's the only default constraint we have that this would realistically happen for (since all other default constraints are simply `Positive()`.
Fixes #620
> Throw error when initializing parameter value to something out of bounds

- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
Previously, if a model was on cuda or using double, these setters would error out when trying to set a value using a python float. This fixes the issue by moving the constructed tensor to the right device/dtype.
> Fix setters for non-tensor initialization values

- gpytorch/kernels/rbf_kernel_grad.py
- test/kernels/test_rbf_kernel_grad.py
- RBFKernelGrad now uses JIT for kernel postprocessing
- RBFKernelGrad now supports multibatch
- Use base kernel test cases for RBFKernelGrad
- Fix an issue where RBFKernelGrad was modifying `self.lengthscale` in-place.
> RBFKernelGrad fixes and improvements

- gpytorch/kernels/kernel.py
I'm seeing very strange behavior using the JIT distance computations. In particular:
1. In the multidevice code, the pointer to our postprocess function is getting overwritten with random garbage, leading to segfaults.
2. Disabling the JIT makes kernel computations ~20% faster, seemingly without costing us memory.
> Disable JIT distance computations

- .gitignore
Avoids having the folder generated when doing `pip install -e .` be tracked.
> Add pip-wheel-metadata/ to .gitignore

- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- test/functions/test_inv_quad_log_det.py
- test/functions/test_root_decomposition.py
- test/utils/test_pivoted_cholesky.py
This PR fixes an issue where we weren't correctly accounting for the existence of a preconditioner when setting up probe vectors for the log determinant.
This somewhat affects the forward pass calculation of the marginal likelihood, but not the backward pass.
> Fix handling of preconditioned logdet calculation

- gpytorch/kernels/kernel.py
- test/examples/test_kissgp_white_noise_regression.py
We now use the new `torch.cdist` for distance computations (a) when it is available, and (b) in the non-batch setting.
> Use cdist for distance computations when available

- gpytorch/__init__.py
- gpytorch/beta_features.py
This is an old deprecation warning that should be removed for 0.3.0.
Closes #524
> Remove deprecated beta_features.fast_pred_*

- gpytorch/likelihoods/noise_models.py
- test/examples/test_kissgp_white_noise_regression.py
The current issue is the load_state_dict functionality does not work in the case when loading the state_dict from model A with `n` training points into model B with `m` training points where `m!=n` both use a likelihood with a FixedGaussianNoiseModel. This approach follows the pattern used by `ExactGP` to extend the `_apply` function to apply to `noise` as an attribute.
> Make noise an attribute in FixedGaussianNoise

- gpytorch/kernels/kernel.py
- test/kernels/test_additive_kernel.py
On master, the composition kernels (`AdditiveKernel`, `ProductKernel`) don't handle `diag` mode properly anymore with the kernel `__call__` changes in `0.3.1`. This PR fixes that, and adds unit tests to ensure that we catch this in the future.
Fixes #655
> Fix composition kernels in diag mode

- setup.py
Seems like this is unnecessary. Requiring `"torch>=1.0.1"` will not install stable if a dev version from the nightlies is present.
Addresses #662
> Remove version parsing for torch nightlies, req. >=1.0.1 instead

- gpytorch/__init__.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/cat_lazy_tensor.py
Adds a `gpytorch.cat` function that functions as `torch.cat` but is agnostic to whether the input list contains tensors or lazy tensors or a mix.
- When the list is all tensors, functions as `torch.cat`
- When the list is not all tensors, calls `lazify` on everything then constructs a `CatLazyTensor`.
Extremely useful for the next PR I am about to put up.
> Add gpytorch.cat function

- examples/00_Basic_Usage/Hyperparameters.ipynb
- examples/00_Basic_Usage/README.md
- examples/00_Basic_Usage/Saving_and_Loading_Models.ipynb
- examples/00_Basic_Usage/index.rst
This PR adds a `00_Basic_Usage` folder to our examples, with two examples currently filled in:
- A tutorial notebook on hyperparameters, including constraints, priors, the distinction between raw and actual parameters, and our custom setters / getters for initializing hyperparameter values.
- A tutorial on saving and loading models.
> Basic usage tutorials

- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
If `get_fantasize_model` is called with a `m x d` input tensor and a `b x m` target tensor, this change makes sure to not automatically expand the input and compute the fantasy updates for each batch (they are the same). Instead, the fantasy update is done only once, and the resulting updated covariance caches are copied (using a `BatchRepeatLazyTensor`).
This is an early draft and requires additional tests.
Addresses #667
To test, see attached notebook:
[test_same_input_fantasies.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3159647/test_same_input_fantasies.ipynb.txt)
> [RFC] Fantasizing repeatedly at the same input points

- gpytorch/kernels/spectral_mixture_kernel.py
Fixes some "dum_dims" "num_dums" typos in the `SpectralMixture` `kernel` documentation which might have caused #691
> fix SM kernel doc typos

- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
Updates #687 to work with batched inputs. 
`inputs` can now be `b1 x ... x bk x m x d` or `f x b1 x ... x bk x m x d`, and `targets` are `b1 x ... x bk x m` or `f x b1 x ... x bk x m`.
If the `f` dimension is present in the targets but not the inputs, this will assume all fantasies are evaluated at the same inputs (in the respective batch), and computation happens more (time, memory) efficiently by only doing the update once.
Test:
[test_same_input_fantasies_batched.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3164081/test_same_input_fantasies_batched.ipynb.txt)
> Fast fantasies in batch (batch evaluation, not batch model) mode.

- gpytorch/models/exact_gp.py
- gpytorch/models/exact_prediction_strategies.py
Allows to fantasize on a model that is already in batch mode.
Also supports
- batch-fantasizing on a batched model, following proper broadcasting semantics
- efficient fantasizing for repeated points
What is still missing is support for multi-task models.
Test nb: [test_batch_model_fantasies.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3168443/test_batch_model_fantasies.ipynb.txt)
> Support for fantasizing batched models

- gpytorch/models/exact_prediction_strategies.py
Previously, `get_fantasy_strategy` would overwrite `model.prediction_strategy.likelihood`. This is change preserves the original `prediction_strategy.likelihood`.
Before change:
[test_get_fantasy_model_without_fant_likelihood.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3217576/test_get_fantasy_model_without_fant_likelihood.ipynb.txt)
After change:
[test_get_fantasy_fantasies_with_fant_likelihood.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/3217577/test_get_fantasy_fantasies_with_fant_likelihood.ipynb.txt)
> preserve the original model's likelihood in get_fantasy_strategy

- gpytorch/kernels/kernel.py
- test/functions/test_matern_covariance.py
- test/functions/test_rbf_covariance.py
Use only ones padding and matmul to compute pairwise distances. Also clean up all the different case considerations. 
This is about 3x faster on large tensors. `torch.cdist` is still fastest on small tensors. We should check speed again once this PR https://github.com/pytorch/pytorch/pull/20605 lands.
> use padding and matmul to compute pairwise distance

- gpytorch/models/exact_gp.py
- gpytorch/settings.py
- test/models/test_exact_gp.py
Implements #696.
Usage:
```
with gpytorch.settings.prior_mode(True):
model(test_input)
```
> Add prior_mode context manager for Exact GP models

- gpytorch/functions/_inv_quad_log_det.py
> Fix TypeError when calling `backward` on `gpytorch.functions.logdet`

- gpytorch/models/exact_prediction_strategies.py
Dynamically (dynsum, get it?) generates the formula depending on the dimensions of the involved tensors. Workaround for the issue reported here: https://github.com/pytorch/pytorch/issues/15671
> Proper einsum broadcasting (hackfix)

- gpytorch/distributions/multivariate_normal.py
Fixes a small bug where adding two multivariate normals was broken because of a reference to self._mean rather than self.mean
> Fix for bug when adding multivariate normals

- gpytorch/priors/__init__.py
- gpytorch/priors/horseshoe_prior.py
- test/priors/test_horseshoe_prior.py
Unlike spearmint or cornell-moe, which use `log(log(1 + 3.0 * (self.scale / X)) ** 2))`,  this implementation takes the average of the lower and upper bound on the pdf provided in the following reference:
C. M. Carvalho, N. G. Polson, and J. G. Scott. The horseshoe estimator for sparse signals. Biometrika, 2010.
> Add horseshoe prior

- gpytorch/variational/variational_strategy.py
When running variational model predictions with `skip_posterior_variances` on, we now compute and cache `K_{uu}^{-1}m` instead of `K_{uu}^{-1}K_{ux}` because we don't need the latter term at all. This is around 60 times faster.
> Add skip_posterior_variances support to VariationalStrategy

- gpytorch/kernels/rbf_kernel.py
This attempts to clarify https://github.com/cornellius-gp/gpytorch/issues/752
> Changed to  lengthscale squared in RBF kernel equation

- gpytorch/constraints/constraints.py
- test/constraints/test_constraints.py
Fix Interval class upper bound transform for bug #744. The new code multiplies the tensor by (upper_bound - lower_bound) before adding lower_bound, thus keeping the tensor between bounds.
> Fix Interval class upper bound transform for bug #744

- gpytorch/kernels/periodic_kernel.py
`PeriodicKernel` wasn't correctly handling diag mode, as it needs to squeeze out the `-2` dimension.
Fixes #749
> Fix diag mode for periodic kernel

- gpytorch/lazy/sum_lazy_tensor.py
Looks like we were trying to be too smart here, the current implementation causes RuntimeErrors when having base lazy tensors of different dimension. Instead we can simply rely on torch tensor broadcasting here.
> Fix issue with .diag() when broadcasting SumLazyTensors

- gpytorch/kernels/kernel.py
This makes kernel computations more stable in the regime where feature values have very large magnitude but distances are still on the order of the lengthscale init.
In general, it is still best practice for us to recommend users to normalize their data because this does *not* solve the problem where the lengthscale initialization is probably wrong on very large data (e.g., this solves the issue when the data is between [500, 501] instead of [0, 1], but not when the data is between [500, 600] and the lengthscale is still initialized to `softplus(0)`.
Fixes #780
> Subtract mean of x1 from x1 and x2 in distance computation.

- gpytorch/kernels/inducing_point_kernel.py
Since `_cached_kernel_mat` and `_cached_kernel_inv_root` require grad, we can't deepcopy them, which is a required op for creating fantasy models. Since these caches only exist for inference efficiency, (e.g., they are explicitly only used at test time when we won't want derivatives w.r.t kernel hypers), the original `InducingPointKernel` and the copy can just share these tensors.
Fixes #784
> Custom __deepcopy__ for InducingPointKernel

- gpytorch/constraints/constraints.py
- gpytorch/utils/transforms.py
- test/constraints/test_constraints.py
- Importing sigmoid from ```torch``` instead of ```torch.nn.functional``` as the latter is deprecated
- Fixing a dtype error in ```PolynomialKernelGrad```
> Fix sigmoid deprecation

- gpytorch/lazy/lazy_tensor.py
Minor fix; these backslashes should be doubled. As is, it's putting a tab character in mathjax, so not rendering correctly. (Could instead make it a raw string, of course.)
> fix tex syntax in a non-raw docstring for LazyTensor

- gpytorch/lazy/__init__.py
- gpytorch/lazy/cached_cg_lazy_tensor.py
- gpytorch/variational/whitened_variational_strategy.py
- test/examples/test_svgp_gp_regression.py
- test/examples/test_whitened_svgp_gp_regression.py
- test/lazy/test_cached_cg_lazy_tensor.py
- test/utils/test_cholesky.py
Mitigates #824.
A proper solution should not count warnings, but check for presence/non-presence of the specific warning, see e.g. change in test_cholesky.py here.
> Make tests less brittle w.r.t. upstream changes to warnings

- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/utils/deprecation.py
- gpytorch/utils/linear_cg.py
PyTorch does not allow (any more, for addcmul operator) to resize the input tensor. To allow the output shaped differently from the input, we have to save it in the temporary tensor. We cannot do `res = torch.addcmul(res, -1, a, c)` because functions are supposed to modify res in-place.
Addresses #822
Fixed by @VitalyFedyunin
> Fix addcmul broadcasting

- gpytorch/kernels/__init__.py
- gpytorch/kernels/newton_girard_additive_kernel.py
- test/kernels/test_newton_girard_additive_kernel.py
Paper: https://arxiv.org/abs/1112.4394
This branch implements the "Additive Gaussian Process" kernel from the link above which uses the Newton-Girard formulae to efficiently compute higher-order additive kernels. The implementation is simple, just wrapping a base kernel, similar to AdditiveStructureKernel and in the forward computes the higher-order terms using the Newton-Girard formulae. This branch also implements some fairly basic tests for it.
Since this kernel can achieve state-of-the-art regression performance, it might be nice to include this kernel in GPyTorch.
> Add a "Newton-Girard additive kernel" of Duvenaud et al 2011

- examples/14_KeOps_Integration/KeOps_GP_Regression.ipynb
- examples/14_KeOps_Integration/README.md
- examples/14_KeOps_Integration/index.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/keops/__init__.py
- gpytorch/kernels/keops/keops_kernel.py
- gpytorch/kernels/keops/matern_kernel.py
- gpytorch/kernels/keops/rbf_kernel.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/keops_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- setup.py
- test/kernels/keops/test_matern_kernel.py
- test/kernels/keops/test_rbf_kernel.py
This PR implements two new kernels `kernels.keops.RBFKernel` and `kernels.keops.MaternKernel`, that when swapped in for our default ones use KeOps to drive kernel matmuls.
Initial results suggest that the efficient matmuls of KeOps combined with the GPyTorch bells and whistles like preconditioning allow for training on datasets like 3droad (`n=~400k`) in minutes.
> Implement KeOps Integration

- gpytorch/models/exact_prediction_strategies.py
Right now, our code for the predictive mean explicitly delazifies `test_train_covar` in the non batch case so that we can use a fused `addmv` call rather than `a + m.matmul(v)`.
This is all well and good as a minor optimization when `test_train_covar` has no lazy components, but is a complete disaster if it is lazy. For example, predictions with the new `KeOpsLazyTensor` ended up being a factor of 20 slower than they ought to be as a result of this.
This fixes #832 cc/ @stanbiryukov
> Fix performance bug in predictions when test_train_covar is lazy.

- gpytorch/models/model_list.py
Allows to pass kwargs to the individual likeilihoods of a ModelList. This is useful e.g. for passing noise to models with FixedNoiseGaussianLikelihood.
> Add **kwargs to likelihood_i of ModelList

- gpytorch/lazy/lazy_tensor.py
This can help avoid calling cholesky unnecessarily. This also adds clamping to avoid issues caused by numerical imprecision..
> Special case cholesky for scalars (1x1 matrices)

- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/mlls/inducing_point_kernel_added_loss_term.py
The “added_loss” term of type `InducingPointKernelAddedLossTerm` that is added for inducing point kernels hard-codes the assumption that the likelihood has a noise attribute:
https://github.com/cornellius-gp/gpytorch/blob/14c043754540351fb024f20746ddc66b434642ed/gpytorch/mlls/inducing_point_kernel_added_loss_term.py#L15
Likelihoods that use a general noise model do not have this attribute.
Essentially, this added loos term is the trace term in eq (9) of http://proceedings.mlr.press/v5/titsias09a/titsias09a.pdf
Looking at (14) in https://pdfs.semanticscholar.org/db7b/e492a629a98db7f9d77d552fd3568ff42189.pdf, it seems that this term should generalize to heteroskedastic noise models if we use `0.5 * Tr(Sigma^-1 (K_nn – Q_nn))` instead of `0.5 / sigma^2 Tr(K_nn – Q_nn)`, where `Sigma` is the …
> Support heteroskedastic likelihoods for IP added loss term

- gpytorch/lazy/sum_batch_lazy_tensor.py
Fixes #866 
As far as I can tell, there are still some lingering edge cases involving using the default `_getitem` for KroneckerProductLazyTensor. However, in my opinion, the "right" way to fix this is probably to add an overridden `_getitem` for Kronecker products, since it's one of the more commonly used LTs.
Since this will involve refactoring KPLT so that it only represents KPs of 2 tensors at a time (e.g., `KPLT(lt1, lt2, lt3) -> KPLT(KPLT(lt1, lt2), lt3)`), this is a much larger project.
For now, This fixes this specific instance of the problem in a reasonable way, since `SumBatchLazyTensor` as it is currently written will materialize a matrix the size of the base lazy tensor before summing anyways when calling `evaluate()` (see `BlockLazyTensor`'s `_matmul` method).
> Override evaluate for SumBatchLazyTensor

- gpytorch/likelihoods/likelihood_list.py
- gpytorch/likelihoods/noise_models.py
Adds the following functionality:
1. All noise models now pass through a noise kwarg -- that is, if noise is specified it will override the nosie regardless of the noise model. This is useful in that it provides a consistent interface regardless of the particular likelihoodused
2. `Likelihoodlist` now also supports a `noise` kwarg - in this case it is expected to be an iterable of tensors. specifying the noise level for each element of the likelihood list.
> Support `noise` kwarg for more likelihoods

- docs/source/batch_gps.rst
The `expand` method call was ill-specified.
> Fix expand tensor shape

- gpytorch/likelihoods/noise_models.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/mlls/noise_model_added_loss_term.py
Previously, when using a heteroskedastic noise model with a separate model providing the noise, joint training would not work properly because
1. the noise model would be evaluated in prior mode (wheras we need the noise model's posterior predictions for the noise in the actual model)
2. the MLL did not account for the MLL of the noise model.
For 1. the fix is to simply ensure that the noise model is in eval mode when called inside `HeteroskedasticNoise`'s `forward` method. Note that this also requires ensuring to not detach the test caches of the main model during evaluation, since o/w some of the noise model's parameters are chopped off from the compute graph.
For 2. this PR introduces the `NoiseModelAddedLossTerm`.
> Fix MLL computation for heteroskedastic noise models

- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/lazy/toeplitz_lazy_tensor.py
- gpytorch/utils/grid.py
- gpytorch/utils/interpolation.py
- test/kernels/test_grid_kernel.py
This PR finishes #861 and implements independent grid sizes per dimension for GridKernel and GridInterpolationKernel. The changes are mostly the same, except that this PR makes additional changes to pass all the tests and ensure correctness. That PR had a few merges from other branches, which clutters the git log a bit, so I'm opening this new PR.
One thing that will have to be done in the future is to fully deprecate the old method of passing in a `G x D` grid into `GridKernel` where `G` is the number of grid points for every dimension. For now, we use a function that converts this old grid into the new expected format of `List[Tensor]` with each Tensor possibly having different lengths.
In addition, it's important to note that this change causes the computations for each dimension to be …
> Independent grid sizes per dimension for GridKernel and GridInterpolationKernel

- .travis.yml
Since 1.3.0 is out, I thought it would be better to test against the latest stable version.
cc @gpleiss @Balandat
> Roll PyTorch in CI to 1.3.0

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
This uses a lower triangular (w/ columns restricted up to the specified rank) parameterization of the to-be-inferred correlation matrix in `MultitaskGaussianLikelihood`.
This parameterization uses
```
rank * (num_tasks - 0.5 * (rank - 1)) - 1
```
instead of
```
num_tasks * (1 + rank)
``` 
parameters for the set of rank `rank` correlation matrices. As the plot below shows the lower the rank the smaller the fraction of parameters (relative to the current parameterization) this uses. 
The black line is the case when `rank=num_tasks`, in which the fraction can be found to be
```0.5 - 1 / (num_tasks * (1 + num_tasks))```. 
Asymptotically (as `num_tasks` -> infinity), the fraction approaches `rank / (1 + rank)` 
Disclaimer: Haven't tested this in a model yet.
> Improved parameterization for correlation matrices

- gpytorch/models/exact_prediction_strategies.py
Right now, if you backward through GP predictions to the training data or GP hyperparameters and update either one, the caches don't get cleared but are dirty (the stuff they depend on has changed).
This PR adds hooks to the grad functions of the mean and covariance caches so that if they are backwarded through they get cleared.
Importantly, if you backward through predictions but NOT the caches because `settings.detach_test_caches` is True by default (e.g., you want derivatives w.r.t. test inputs only), the caches will not be cleared because they don't need to be.
In practice, what this does is eliminate the need to manually toggle back and forth between train mode and test mode in models that are trained with a GP component in prediction mode.
Fixes #891
> Register backward hooks to grad functions for cache clearing.

- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- test/lazy/test_added_diag_lazy_tensor.py
Adding a `preconditioner_override` option that allows specification of arbitrary preconditioners for `AddedDiagLazyTensor`. Example usage is given in the associated unit test but broadly looks like:
```
overrode_lt = AddedDiagLazyTensor(
RootLazyTensor(tensor),
DiagLazyTensor(diag),
preconditioner_override=nonstandard_preconditioner,
)
```
The original preconditioner is still left in the class, but renamed as `_default_preconditioner`
Potential use cases include easier testing of new preconditioners as well as data driven preconditioners such as recycled subspaces from old solves.
> Add preconditioner override option for AddedDiagLazyTensor

- test/examples/test_svgp_gp_regression.py
The current test is broken if run in other test environments that may not run it from the examples directory. This fixes the loading to be agnostic to that.
> Fix relative location of old model file in test

- gpytorch/settings.py
Current benchmarking against our new default tolerances + various code changes suggests that CG overtakes Cholesky around n=800-n=1000. Therefore, we should not use CG until then.
> max_cholesky_size -> 800

- gpytorch/models/exact_prediction_strategies.py
In some cases, due to numerical accuracy `torch.cholesky` may fail in the call sites in `exact_prediction_strategies.py`. This uses `psd_safe_cholesky` instead to avoid this issue.
> Use psd_safe_cholesky in exact_prediction_strategies

- .isort.cfg
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/settings.py
This adds a flag that causes us to not resample probe vectors for our log det estimates each iterations. This will result in some mild bias in our derivatives, but reduced stochasticity in the MLL value. Using this flag should improve the convergence of methods like L-BFGS that don't deal well with even mild amounts of stochasticity in a loss function.
> Add deterministic_probes setting to improve L-BFGS convergence

- gpytorch/distributions/multivariate_normal.py
- test/distributions/test_multivariate_normal.py
if `dist` is a `MultivariateNormal` object, now it is possible to write `dist[index]` and create a new distribution with the appropriate marginalized mean and covariance.
The test provides examples of usage.
This is helpful in my research and it might also be helpful to upstream it?
> Indexing MultivariateNormals

- .isort.cfg
- gpytorch/lazy/lazy_tensor.py
Pretty sure this is the right way to handle this check and error.
> Raise error if Cholesky is used with KeOps.

- gpytorch/distributions/multivariate_normal.py
I've resolved the TODO item to add validation for the sizes of the mean and variance.
I had also implemented a `__repr__` method that would show you the shape of the MultivariateNormal instead of the values of the tensors. But I think it's best not to upstream that. The `__repr_sizes` method was sharing code with it.
> Validation code for MultivariateNormal

- gpytorch/priors/horseshoe_prior.py
- gpytorch/priors/torch_priors.py
Inheriting the behavior of `expand` from the base torch distributions was causing really strange behavior, I think because our priors also inherit from Module. In addition to the bug in #976, calling `prior.expand(some_torch_size)` was actually modifying `prior` in place in addition to returning a new Module with the correct size.
These issues were easily fixed by just defining our own `expand` methods for the various priors. I also think that this is a rare setting where overriding and defining our own expand behavior will actually make things easier to debug, because the upstream behavior is extremely weird: https://github.com/pytorch/pytorch/blob/dd52f50fc85e6710f020936c1fc5f14673508350/torch/distributions/gamma.py#L50-L57
Fixes #976
> Custom expand methods for priors

- README.md
I tried to use `pip install git+https://github.com/cornellius-gp/gpytorch.git` to install the latest version. However, under the circumstance of already installed `gpytorch-0.3.6`, the provided installation command will not upgrade to the latest version. In order to install the latest version, `--upgrade` command should be explicitly added.
> upgrade to the latest version

- gpytorch/lazy/matmul_lazy_tensor.py
`(DA)_ii = D_ii * A_ii` if `D_ij = 0` for all `i!=j`. This mitigates #989 (though we should think more generally about indexing performance...)
> Special case diag call on MatmulLazyTensor

- gpytorch/models/model_list.py
This did the right thing before, but it's not obvious why (return of the return value of the last line...). This makes this explicit.
> Use explicit return in model list forward

- gpytorch/__init__.py
- gpytorch/functions/__init__.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/likelihoods/bernoulli_likelihood.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/softmax_likelihood.py
- gpytorch/means/constant_mean.py
- gpytorch/means/constant_mean_grad.py
- gpytorch/means/mean.py
- gpytorch/mlls/__init__.py
- gpytorch/models/__init__.py
- gpytorch/utils/deprecation.py
- gpytorch/variational/_variational_distribution.py
- gpytorch/variational/whitened_variational_strategy.py
- test/examples/test_spectral_mixture_gp_regression.py
Removes:
- `batch_size`
- `*log_det`
Marks all other deprecation as "Remove after 1.0" to remind us!
> Remove old deprecations

- gpytorch/kernels/periodic_kernel.py
On master, the following breaks:
```python
from gpytorch.kernels import PeriodicKernel
kern = PeriodicKernel()
x1 = torch.randn(1, 1)  # Code works if x1 is any n x d other than 1 x d
x2 = torch.randn(5, 1)
K = kern(x1, x2).evaluate()
```
Clearly, this should not break :-). In our defense, GPyTorch returns exactly the error you'd hope:
```python
RuntimeError: The expected shape of the kernel was torch.Size([1, 5]), but got torch.Size([5]). This is likely a bug in GPyTorch.
```
but clearly we should add some unit tests for edge cases like this. 
Fixes #1011
> Dont squeeze kernel vector outputs in PeriodicKernel

- gpytorch/module.py
Currently, attaching non-gpytorch torch modules as submodules to gpytorch modules causes issues with the constraint functionality. Specifically, `constraint_for_parameter_name ` assumes that all the submodules are GPyTorch modules and have a `_constraints` dictionary (as initialized here: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/module.py#L19). 
This catches the `AttributeError` that is raised if that is not the case and returns `None`.
> Handle non-gpytorch submodules in constraint_for_parameter_name

- .isort.cfg
- .pre-commit-config.yaml
- gpytorch/module.py
- gpytorch/priors/torch_priors.py
Fixes an issue where the built in expand method was deleting our prior buffers (see #977).
cc/ @idelbrid
> Custom expand method for MultivariateNormalPrior

- gpytorch/mlls/gamma_robust_variational_elbo.py
- gpytorch/mlls/predictive_log_likelihood.py
- gpytorch/mlls/variational_elbo.py
diffs limited to /mlls/ => rendered [here](https://gpytorch.readthedocs.io/en/docfix/marginal_log_likelihoods.html)
> fix some math/latex typos in doc strings

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/utils/broadcasting.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
Fixed two small bugs I found today.
First, a `ValueError(None)` used to be thrown because of an incorrect `if` statement.
Then, a failure to replace `row`->`col` everywhere led to wrong behaviour for indexing kernel matrices. Test is also attached.
> Bugfixes: lazy kernel with batch dimensions indexed correctly, error message

- examples/01_Exact_GPs/Simple_GP_Regression.ipynb
The function stated in the Simple GP example (https://gpytorch.readthedocs.io/en/latest/examples/01_Exact_GPs/Simple_GP_Regression.html#Introduction)
has noise from a Gaussian with variance 0.2. 
However, the following code block samples from a Gaussian with _standard deviation_ 0.2. This makes the code snippet/sample consistent with the definition stated in the introduction.
> [Examples] Fix Simple GP function noise

- README.md
Hey guys, thank you for your work on this amazing project. I use GPyTorch on ArchLinux and thought I would create a package for this so users can easily install it. With the advent of the first stable version, this would be the perfect time to include it with the installation instructions.
> add instructions for archlinux package installation

- gpytorch/kernels/cylindrical_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
Fixes two small math render errors due to missing '\' for SpectralMixtureKernel and CylindricalKernel at
https://gpytorch.readthedocs.io/en/latest/kernels.html
> Fix docstring for SpectralMixtureKernel and CylindricalKernel: mathbf -> \mathbf

- gpytorch/kernels/spectral_mixture_kernel.py
Includes a fancier option for initializing the SM kernel based on the empirical spectrum of the data. Fixes #1049 by virtue of the fact that this initialization method works when the min distance between points in a feature dim is 0, where as the vanilla `initialize_from_data` method does not.
> Fancier init for SM kernel

- gpytorch/lazy/batch_repeat_lazy_tensor.py
- test/lazy/test_batch_repeat_lazy_tensor.py
Provides a fix to https://github.com/cornellius-gp/gpytorch/issues/1064 by adding in flags to the `_matmul` and `_quad_form_derivative` methods of `BatchRepeatLazyTensor` when the repeated lazy tensor is not square (as happens when trying to batch expand prediction strategy covariance matrices).
I also added a unit test for the non-square case in the test file for `BatchRepeatLazyTensor`.
> Add support to BatchRepeatLazyTensorfor nonsquare Matrices

- gpytorch/lazy/block_lazy_tensor.py
If the `left_vec` was passed in with an explicit batch dimension but no explicit trailing dimension things ended up breaking in adding batch dimensions (and broke in much less obvious cases if some implicit broadcasting was happening). See the discussion on https://github.com/pytorch/botorch/issues/396 for details.
> Make _quad_form_derivative for BlockDiagLazy batch-compatible

- gpytorch/kernels/index_kernel.py
The expand calls in IndexKernel are currently wrong, as they expand even if the batch shapes of `i1` and `i2` match the batch shapes of the kernel.
cc/ @grishabhg
Fixes #1082
> Fix batch expanding in IndexKernel

- gpytorch/kernels/index_kernel.py
The recent change ##1087 fixed one thing but broke batch evaluation of non-batched models. This fixes it by broadcasting the different batch shapes involved.
> Fix batch evaluation of index kernel

- .travis.yml
- setup.py
I think m2r is broken on the new release of sphinx, so pinning to <3.0.0 so Travis can build our docs.
> Pin sphinx<3.0.0

- gpytorch/likelihoods/gaussian_likelihood.py
In Gaussian likelihoods, I can't see any reason why we would ever not want the noise diagonal we add to be equivalent to the shape we can resolve from the input distribution's mean. In particular, if `p(f | D)` has a mean of size ` b1 x ... x bk x n`, then shouldn't our noise be `b1 x ... x bk x n x n` always?
Right now, we try to get the shape from the input data if we have it available, but that is definitely wrong because the raw input data might not have been passed through a feature extractor that impacts the shape.
Fixes #1084  (hopefully)
> Always use output shape instead of input shape for noise shape

- docs/source/kernels.rst
- gpytorch/kernels/cosine_kernel.py
Very simple PR that adds the RQ kernel to the docs.
Also fixing the position of the body for AdditiveStructureKernel, which went for walk elsewhere.
> Adding RQ kernel to documentation

- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/settings.py
- gpytorch/variational/unwhitened_variational_strategy.py
- gpytorch/variational/variational_strategy.py
Currently it's not easily possible to customize the jitter value in the cholesky computations inside the lazy tensors. This adds a setting so that we can now do
```
with settings.cholesky_jitter(1e-5):
lt.cholesky()
```
Naturally, this will also apply this to the solves (when performing posterior inference). This also adds this setting to other uses of `psd_safe_cholesky` in the code.
Note that this PR does not change current behavior as the default setting value is `None`, which is the default argval of `psd_safe_cholesky`.
> Add cholesky_jitter to settings.

- .travis.yml
The latest version of flake8 (3.8) causes our linting to fail. This is a hotfix so that travis works.
> Lock down flake8

- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/rff_kernel.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/models/pyro/_pyro_mixin.py
- test/kernels/test_rff_kernel.py
This is a PR for `RFFKernel` which implements random Fourier features for the RBFKernel as described by https://papers.nips.cc/paper/3182-random-features-for-large-scale-kernel-machines.
Note that I use sine and cosine features which has lower variance as shown in https://arxiv.org/abs/1506.02785. 
I also did [some profiling](https://github.com/cornellius-gp/gpytorch/files/4749309/alexwang-rff-profiling.pdf) of the RFF Kernel on UCI datasets for a course project last semester, showing
1. the speedups as a function of number of data points versus an exact GP
2. the computation time as a linear function of the number of features, as expected
3. the quality of kernel approximation error as a function of number of features
4. the speedups per optimization iteration
5. the regression …
> Random Fourier Features Kernel (RBF)

- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/rbf_kernel.py
- test/examples/test_kissgp_additive_regression.py
- test/examples/test_kissgp_kronecker_product_regression.py
- test/examples/test_simple_gp_regression.py
- test/kernels/test_grid_interpolation_kernel.py
- test/kernels/test_grid_kernel.py
Closes #1054 
GridKernel and GridInterpKernel sometimes worked with ard (depending on the scale kernel ordering). This change makes GridKernel much more stable (and parallel) - and makes it so that ARD works with or without a scale kernel.
> Make grid kernel work better with ARD

- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
There were a few bugs in various `LT#_expand_batch` methods, which would cause failures when adding two LTs. This PR addresses those errors and adds a unit test.
[Closes #1133]
> Fix errors with LazyTensor#__add__

- gpytorch/lazy/kronecker_product_lazy_tensor.py
This is quite a bit faster. Not a big deal in the grand scheme of things, but let's take what we can get.
Will add unit tests.
```
ns = list(range(10, 60, 10))
data = []
for n in ns:
A = torch.rand(2, n, n)
B = torch.rand(2, n, n)
C = torch.rand(2, n, n)
K = KroneckerProductLazyTensor(A, B, C)
res = %timeit -o K.diag()
res_master = %timeit -o LazyTensor.diag(K)
assert torch.allclose(K.diag(), LazyTensor.diag(K))
data.append({
"n": n,
"this_diff": 1000 * res.average,
"master": 1000 * res_master.average,
})
```
> Add special-cased diag operation for KroneckerProductLazyTensor

- gpytorch/lazy/kronecker_product_lazy_tensor.py
The in-place version of `clamp_min_` fails to have a correct backwards call, so this replaces that with a non-in place version. I don't know why the unit tests didn't catch this issue.
> [Bug] In place _symeig clamping fails to have correct backwards.

- gpytorch/lazy/kronecker_product_added_diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
This PR should fix any possible bugs with the logdet backwards in KPAddedDiagLazyTensor --- that I would have introduced.
Basically, the gradients aren't well defined for the log det if there are repeated eigenvalues and backpropagating through `symeig` is known to be unstable. Instead, we can use stochastic trace estimation to estimate the gradient, which is easy in this case because solves are cheap and can be done in batch with the original solve.
The trick I used here is to skip the logdet forward Lanczos call in the `inv_quad_logdet` function while detaching the `_logdet()` so that we add zero to the correctly computed forwards pass in the logdet while also propagating the gradients.
> Use trace estimation for logdet backwards in KPAddedDiagLT

- gpytorch/lazy/__init__.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- test/lazy/test_mul_lazy_tensor.py
Adds a `ConstantDiagLazyTensor` to deal with some of the gradient issues that came up in #1105. 
This fails miserably b/c of how the args are handled in the representation tree, but I'm not sure how to fix that. I tried tensorizing the n arg, but then the lazies are trying to compute gradients w.r.t. n. Any thoughts how to properly deal with this?
cc @wjmaddox
> Add ConstantDiagLazyTensor

- gpytorch/models/exact_prediction_strategies.py
Fixes (temporarily) #1157, until pytorch/pytorch#22573 is addressed
> Perform QR composition in exact prediction strategy on the CPU

- gpytorch/models/exact_prediction_strategies.py
Fixes #1232 . 
That being said, I'm not entirely confident the other specialized prediction strategies even have this option so might want to expand the scope.
> Skip Posterior Variances under skip_posterior_vars settings for RFFPredStrat

- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_interleaved_lazy_tensor.py
- gpytorch/lazy/cached_cg_lazy_tensor.py
- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/triangular_lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/priors/lkj_prior.py
- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/utils/cholesky.py
- gpytorch/utils/errors.py
- gpytorch/utils/memoize.py
- gpytorch/variational/_variational_strategy.py
- gpytorch/variational/batch_decoupled_variational_strategy.py
- gpytorch/variational/cholesky_variational_distribution.py
- gpytorch/variational/orthogonally_decoupled_variational_strategy.py
- gpytorch/variational/unwhitened_variational_strategy.py
- gpytorch/variational/variational_strategy.py
- gpytorch/variational/whitened_variational_strategy.py
- test/lazy/test_chol_lazy_tensor.py
- test/lazy/test_interpolated_lazy_tensor.py
- test/lazy/test_kronecker_product_added_diag_lazy_tensor.py
Adds a new `TriangularLazyTensor` abstraction. This tensor can be upper or lower (default) triangular. This simplifies a bunch of stuff with solves, dets, logprobs etc.
1. `CholLazyTensor` now takes in a `TriangularLazyTensor`
2. The `_cholesky` method is expected to return a `TriangularLazyTensor`
3. The `_cholesky` method now takes an `upper` kwarg (allows to work with both lower and upper variants of `TriangularLazyTensor`)
4. `DiagLazyTensor` is not subclassed from `TriangularLazyTensor`
5. The memoization functionality is updated to allow caching results depending on args/kwargs (required for dealing with the upper/lower kwargs). By setting `ignore_args=False` in the `@cached` decorator, the existing behavior can be replicated.
1. `CholLazyTensor` now has a more efficient …
> Add TriangularLazyTensor

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
Right now, MultitaskGaussianLikelihood creates a BlockDiagLazyTensor regardless of whether the noise covariance is fully diagonal. This is bad, because it will always result in `full_covar` (e.g., from a `likelihood(model(X))` call) being a `SumLazyTensor` instead of an `AddedDiagLazyTensor`.
One issue this doesn't fix: since `covar` is usually still a `LazyEvaluatedKernelTensor` by the time it gets to the likelihood, if it would be a `KroneckerProductLazyTensor` after evaluation, we will end up with an `AddedDiagLazyTensor` from the likelihood instead of the new `KroneckerProductPlusDiagLazyTensor`.
> Fix issue in Multitask likelihood

- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/triangular_lazy_tensor.py
I'm not entirely sure what's going on here. Motivated by upstream Ax test failures caused by TriangularLT, https://github.com/pytorch/botorch/issues/513, and #1247.
Removing the explicit `_quad_form_derivative` method from `TriangularLazyTensor` seems to resolve those issues, but creates some test failures in `CholLazyTensor` that are resolved by removing the `_quad_form_derivative` method from `RootLazyTensor`.
> [WIP] Remove _quad_form_deriv methods from TriangularLT and RootLt

- gpytorch/distributions/multivariate_normal.py
- gpytorch/settings.py
- test/distributions/test_multitask_multivariate_normal.py
Ideally we'd be able to check than any MVN covariance is positive definite, but that's too expensive. In practice, negative posterior/variational variances are the more common issue. This ensures that all variances are at least 1e-6 (value determined by a context manager). It fixes any negative variance values, but raises a warning.
@Balandat @jacobrgardner thoughts?
> Make sure MVN variances are positive (raise warning if not)

- gpytorch/utils/memoize.py
- gpytorch/variational/batch_decoupled_variational_strategy.py
- gpytorch/variational/variational_strategy.py
This got overlooked in #1102. This fix is not the most elegant one, we really should use some kind of hook (as the code states). This only occurred when batch-evaluating with different batch sizes. That logic generally could be improved..
> Fix bad cache invalidation in variational strategies

- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
This fixes two issues:
1. calling `symeig` with `eigenvectors=False` after calling it with `eigenvectors=True` would return the eigenvectors (because we avoid recomputing the evals). This now propertly returns `None` instead.
2. calling `symeig` of any `BlockLazyTensor` with `eigenvectors=False` woudl raise a `RuntimeError` (#1281)
This PR also adds a unit test testing the behavior.
> Fix issues with eigenvectors=False in symeig

- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/models/exact_gp.py
- gpytorch/module.py
- gpytorch/variational/_variational_strategy.py
There are a few modules that use precomputed caches (ExactGPs, _VariatianalStrategy, GridKernel, etc.). We should be clearing these caches in two scenarios:
1. Entering `train` mode after being in `eval` mode
2. When calling `load_state_dict`
This introduces a `_clear_cache()` method to the `gpytorch.Module` super class, which is overwritten by any modules with caches. `Module#train` and `Module#_load_from_state_dict` both call `_clear_cache`.
[Fixes #1308]
> Clear precomputed caches when training or loading from state dict

- test/kernels/keops/test_matern_kernel.py
It looks like the Matern KeOps tests are currently broken on master and return the error:
```
======================================================================
ERROR: test_forward_nu25_x1_neq_x2 (kernels.keops.test_matern_kernel.TestMaternKeOpsKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/deriksson/Documents/GitHub/gpytorch/test/kernels/keops/test_matern_kernel.py", line 55, in test_forward_nu25_x1_neq_x2
return self.test_forward_nu05_x1_neq_x2(nu=2.5)
TypeError: test_forward_nu05_x1_neq_x2() got an unexpected keyword argument 'nu'
```
The following PR fixes the naming so the helper functions aren't being called as independent tests.
> Fix Matern KeOps tests

- gpytorch/mlls/__init__.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/mlls/leave_one_out_likelihood.py
- gpytorch/mlls/leave_one_out_pseudo_likelihood.py
- test/mlls/__init__.py
- test/mlls/test_leave_one_out_pseudo_likelihood.py
This is an implementation of the leave one out cross-validation (pseudo likelihood), from RW 5.4.2.  The objective is to maximize the sum of the leave-one-out log probabilities, which we can do in `O(n^3)` via a bordered system formulation. I explicitly use Cholesky as I think this is mostly interesting in the small-data regime, where incorrect model assumptions may influence the resulting model a lot. 
The two computationally expensive pieces are:
1) Computing `diag(inv(K))`, which we can do `O(n^3)` via Cholesky.  We can potentially do diagonal estimation, see, e.g., https://www-users.cs.umn.edu/~saad/PDF/umsi-2005-082.pdf, but it requires working with inv(K) rather than K, so we probably need a pretty large number of points to beat Cholesky as we have a CG step in the inner loop.
2) …
> Leave one out cross-validation 

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
If I have a MMVN with `mean.shape = [1 x d]` and `cover.shape = `[nd x nd]`, I would expect the singleton dimension in the mean to broadcast. Similarly for `mean.shape = [n x 1]` and `cover.shape = `[nd x nd]`.
This PR fixes a small bug and allows for this broadcasting.
> Fix shape issue for MMVN with broadcasted means

- gpytorch/constraints/constraints.py
Fixes #1305 
Note that `.float` is the correct cast and not a half baked decision on my part -- all of the `Constraint` methods use operations that can mix dtypes, but we only want the output tensors of each method to be fp64 if the input tensor was, not because the bounds are (also note that in the current implementation on master, `Interval(4., 5.)` would result in fp32 bound tensors).
> Explicitly cast constraint bounds to float

- gpytorch/kernels/keops/matern_kernel.py
- gpytorch/kernels/keops/rbf_kernel.py
For CIQ BayesOpt sampling, it makes sense to use Cholesky to compute the GP marginal log likelihood and the posterior. Unfortunately, this causes multiple KeOps compilation steps - each time Cholesky is called on a new matrix with a different size, or when the `k_Xx` term changes size.
This PR bypasses KeOps when a KeOps kernel is called with a small or rectangular kernel. Here, a small/rectangular kernel is one where `n` or `m` is smaller than `gpytorch.settings.max_cholesky_size`.
For the BayesOpt experiment in [this repo](https://github.com/gpleiss/ciq_experiments/tree/main/bayesopt/Hartmann6.ipynb) - KeOps is now only used to perform matmuls with (large) prior covariance matrix when performing Thompson sampling.
(We could also include a different context manager to control the KeOps …
> Bypass keops for small/rectangular kernels

- docs/source/optim.rst
The section title is supposed to be `NGD` rather than `LazyTensor`, so I fix it.
> Fix section title

- gpytorch/models/approximate_gp.py
- gpytorch/variational/_variational_strategy.py
- gpytorch/variational/batch_decoupled_variational_strategy.py
- gpytorch/variational/independent_multitask_variational_strategy.py
- gpytorch/variational/lmc_variational_strategy.py
- gpytorch/variational/orthogonally_decoupled_variational_strategy.py
- gpytorch/variational/variational_strategy.py
Right now, approximate GPs don't get extra kwargs to the user defined `forward` method. In most other places in the package, this works.
> VariationalStrategy objects take **kwargs

- gpytorch/lazy/kronecker_product_added_diag_lazy_tensor.py
See #1331 for more details but this changes `KroneckerProductAddedDiagLazyTensor` to use pytorch's symeig backwards through the logdeterminant rather than gpytorch's stochastic trace estimation.
I don't think that there's a better structure exploiting version of this right now than what's in here, but am open to discussions about it.
> Change KroneckerProductAddedDiagLazyTensor log det to pytorch logdet

- gpytorch/constraints/constraints.py
- gpytorch/test/base_kernel_test_case.py
This solves issue #907 by using an instance of the module `torch.nn.Softplus` instead of `torch.nn.functional.softplus` because the functional version can't be pickled. Also added a test case for this.
> Make kernels pickleable

- gpytorch/lazy/kronecker_product_lazy_tensor.py
- test/lazy/test_kronecker_product_lazy_tensor.py
The current "symeig" root decomposition for `KroneckerProductLazyTensor` uses a Hadamard product of a KPLT and a dense vector https://github.com/cornellius-gp/gpytorch/blob/8f9b44fc57dbb0a13b568946f07a37e9332f92c4/gpytorch/lazy/lazy_tensor.py#L1366, which is quite memory intensive for large kronecker products. This PR adds in a lazy option for returning the eigenvalues (maybe this should be done throughout the LT framework instead of returning solely the vector?), which allows writing the KPLT root decomposition as a Kronecker product of the product of the eigenvectors and eigenvalues of the components of the KP.
Example usage that should now be possible:
```python
kernels = [MaternKernel()] * 4
xlist = [torch.randn(x, 1) for x in [10, 30, 50, 100]]
kplt = …
```
> add lazy evals option to kplt symeig + root

- gpytorch/models/exact_prediction_strategies.py
> use `reshape` instead of `view` to fix multi-output prediction

- gpytorch/distributions/multivariate_normal.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py
- gpytorch/lazy/low_rank_root_lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
Adds two new LTs that allow for the use of Woodbury on matrices of the form `UV + diag(a)` for which `U` and `V` are low rank enough that we believe this will be faster. 
SGPR is an obvious use case here, where `U = V^{T} = K_{XU}K_{UU}^{-1/2}`.
The motivation for this PR is to solve #1349, and it does so pretty well. The example code that @monabf included in that issue now trains 5 times faster on the GPU and now has prediction times on the CPU that are in line with GPy.
@gpleiss -- this PR also fixes one other GPyTorch bug in a slightly hacky way (see the new `AddedDiagLazyTensor.evaluate_kernel` where I describe the problem), but in a way that will go away when we switch over to linear operators that don't use representation trees. If you're not happy with this fix as a temporary one, …
> Add LowRankRootLazyTensor / LowRankRootAddedDiagLazyTensor, refactor SGPR

- gpytorch/means/zero_mean.py
Right now, ZeroMean doesn't work at all for batch / multitask GPs if the input data doesn't have the batch dimension (e.g., I have multiple GPs I am evaluating on the same data `x`).
`ZeroMean` now takes a `batch_shape` upon initialization like our other means / kernels to fix this.
Fixes #1364 by allowing one to define `self.mean_module = gpytorch.means.ZeroMean(batch_shape=torch.Size([2]))` in the standard `BatchIndependentMultitaskGPModel` from the example notebook, which is not currently possible.
cc/ @adamhall
> ZeroMean can now take batch_shape

- gpytorch/kernels/distributional_input_kernel.py
- gpytorch/kernels/polynomial_kernel_grad.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/test/base_kernel_test_case.py
- test/examples/test_spectral_mixture_gp_regression.py
- test/kernels/test_matern_kernel.py
- test/kernels/test_spectral_mixture_kernel.py
[Fixes #1329]
The SpectralMixtureKernel was woefully incompatible with multi batch / broadcasted operations. This PR fixes that.
It also adds missing unit tests for kernel diagonals.
> Improve batching/unit testing of SpectralMixtureKernel

- gpytorch/models/exact_prediction_strategies.py
The inner term in the RFF Prediction strategy can become singular when `n >> num_features` (https://github.com/cornellius-gp/gpytorch/blob/57fa992e2bb3292b27a08c419ea6af9ad139ff1e/gpytorch/models/exact_prediction_strategies.py#L628).
Enforcing that the `psd_safe_cholesky` can use the gpytorch cholesky_jitter setting makes it more stable.
This example currently fails, but passes in the PR.
```
import torch
from botorch.optim.fit import fit_gpytorch_torch
class ExactGPModel(gpytorch.models.ExactGP):
def __init__(self, train_x, train_y, likelihood):
super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
self.mean_module = gpytorch.means.ConstantMean()
self.covar_module = gpytorch.kernels.RFFKernel(num_samples=100, num_dims=3)
def forward(self, x):
mean_x = …
```
> Add jitter option to psd_safe_cholesky in RFFPredictionStrategy

- gpytorch/kernels/rbf_kernel_grad.py
This fixes the issue in #1389 that breaks backward on the RBFKernelGrad when `diag=True` by replacing the inplace operation with a not-in-place operation. The code snippet in the issue runs without error after this change.
> Remove inplace operation on lengthscale from RBFKernelGrad (Fixes #1389)

- gpytorch/test/utils.py
This happens if cuda has not yet been initialized. In that case I changed the logic to just pick a random device.
> Catch RuntimeError inleast_used_cuda_device

- gpytorch/distributions/delta.py
Some of the tests in `test/examples` are failing after https://github.com/pytorch/pytorch/pull/48743 was merged turned on distributions validation. This adds the `arg_constraints` attribute that was missing in `distributions.Delta` which is needed for generic parameter support validation. Note that this failure only happens if Pyro isn't installed (since Pyro's implementation has this attribute). 
cc. @Balandat
> Add arg_constraints attribute to Delta distribution

- gpytorch/variational/variational_strategy.py
The whitened inducing points `\tilde u` are given by the following deterministic transformation of the unwhitened inducing points `u`:
`\tilde u = K^{-1/2} ( u - \mu )`
where `K` and `\mu` are the prior covariance/mean of `u`.
The (predictive) posterior mean of an SVGP model evaluated at `x` is given by:
` k_x^T K^{-1} (m - \mu) + \mean_x `
where `k_x` is the cross-covariance between `x` and the inducing points, `\mean_x` is the GP prior mean evaluated at `x`, and `m` is the *unwhitened* inducing variational mean. By the deterministic transformation above, the whitened variational mean is equal to `\tilde m = K^{-1/2} (m - \mu)`. Therefore, we have that the (predictive) posterior mean is:
` k_x^T K^{-1/2} \tilde m + \mean_x `
In variational_strategy.py, `interp_term` is equal to `K^{-1/2} …
> Fix whitened SVGP for non-zero prior means.

- gpytorch/optim/ngd.py
NGD example has `momentum` argument while this is not supported. It also lacks the required `num_data` argument. This PR fixes both.
Also fix incorrect type hint on the `step()` function.
> Fix docstring of NGD

- gpytorch/kernels/spectral_mixture_kernel.py
I added two sentences indicating how to deal with unevenly spaced observations in the SM kernel
> Clarify that initialize_from_data_empspect assumes evenly spaced inputs

- gpytorch/kernels/rff_kernel.py
- gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py
- gpytorch/lazy/low_rank_root_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
- test/examples/test_sgpr_regression.py
- test/kernels/test_rff_kernel.py
- test/lazy/test_low_rank_root_added_diag_lazy_tensor.py
- test/lazy/test_low_rank_root_lazy_tensor.py
There were no unit tests for LowRankRootLazyTensor (or its added diag variant), and there were a number of issues. Most notably, `inv_quad_logdet` was not returning the right `inv_quad` term, which caused errors when using this LazyTensor on a batched GP model.
This PR fixes these issues, and also uses `LowRankRootLazyTensor` for RFF kernels.
> Bug fixes to LowRank lazy tensors

- gpytorch/lazy/__init__.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_added_diag_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/kronecker_sum_lazy_tensor.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
- test/lazy/test_kronecker_product_added_diag_lazy_tensor.py
- test/lazy/test_kronecker_product_lazy_tensor.py
- test/lazy/test_kronecker_sum_lazy_tensor.py
This is a sub pull request into #1430 separating out the unit tests for the separate cases when `D` is a Kronecker product of constant diagonals and when `D` is a Kronecker product of non-constant diagonal cases. 
edit: This will not pass the failing unit test wrt the quad_form_derivative in the constant diagonal case.
> Improvements to Unit Tests for KroneckerProductAddedDiagLazyTensor

- gpytorch/lazy/__init__.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/sum_kronecker_lazy_tensor.py
- gpytorch/likelihoods/__init__.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/examples/test_batch_multitask_gp_regression.py
- test/lazy/test_sum_kronecker_lazy_tensor.py
- test/likelihoods/test_general_multitask_gaussian_likelihood.py
Renames and fixes the comment in the documentation. Also removes MultitaskGaussianLikelihoodKronecker.
> Rename KroneckerSumLT to be SumKroneckerLT

- gpytorch/kernels/kernel.py
- test/kernels/test_additive_and_product_kernels.py
Current behavior:
```python
kernel_1 + kernel_2 + kernel_3
```
This PR flattens chained kernel addition and multiplication:
```python
kernel_1 + kernel_2 + kernel_3
kernel_1 * kernel_2 * kernel_3
```
[Fixes #1478]
> Better additive/product kernel composition

- gpytorch/lazy/lazy_tensor.py
- gpytorch/priors/lkj_prior.py
- gpytorch/settings.py
- gpytorch/utils/cholesky.py
- gpytorch/utils/contour_integral_quad.py
- gpytorch/utils/lanczos.py
- gpytorch/utils/linear_cg.py
- gpytorch/utils/minres.py
- gpytorch/utils/pivoted_cholesky.py
Whenever I debug, I'm always adding print statements to log CG/Cholesky/etc. calls. Seems like a useful tool to actually add to the library :)
```python
with gpytorch.settings.verbose(True):
```
Produces the following output:
```sh
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
Iter 1/10 - Loss: 4.051 in 0.06775569915771484
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
Iter 2/10 - Loss: 3.862 in 0.06846332550048828
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
DEBUG:root:Running Cholesky on a matrix of size torch.Size([5, 500, 500]).
Iter 3/10 - Loss: 3.637 …
```
> Verbose mode logs expensive linalg routines

- examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.ipynb
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/rff_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/models/__init__.py
- gpytorch/models/exact_prediction_strategies.py
- test/examples/test_rff_gp_regression.py
- test/kernels/test_additive_and_product_kernels.py
- test/kernels/test_inducing_point_kernel.py
- test/kernels/test_rff_kernel.py
- Add a SGPRPredictionStrategy to improve SGPR prediction speed [Fixes #1459]
- Ensure that we're not making any unnecessary preconditioner calls for LowRankRootAddedDiagLazyTensor
- Make sure RFFPredictionStrategy is used in conjunction with ScaleKernel (it was being ignored - now there's unit tests to make sure it's used)
- Improve SumPredictionStrategy, and ensure it is used in conjunction with ScaleKernel
> Faster SGPR predictions, PredictionStrategy bug fixes

- gpytorch/test/lazy_tensor_test_case.py
- test/lazy/test_kronecker_product_added_diag_lazy_tensor.py
Adds a dictionary of tolerances (rel, abs) for different test cases to `LazyTensorTestCase` (and `RectangularLazyTensorTestCase`). This allows over-writing specific tolerances for certain tests (e.g. solves for Kronecker LTs that rely on `symeig` and are less accurate) without having to rewrite the whole test.
I am using this to fix a number of flaky tests in the `TestKroneckerProductAddedDiagLazyTensor` suite (and inherited suites).
> Test-specific tolerances

- gpytorch/distributions/multitask_multivariate_normal.py
- gpytorch/distributions/multivariate_normal.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/models/exact_prediction_strategies.py
- test/distributions/test_multivariate_normal.py
Adds a base sample shape property to MultivariateNormal. I should have just added this in #1355 instead of the fix I did. I checked and it resolves the failing unit test in botorch (botorch/models/test_higher_order_gp.py), but botorch will need another PR to properly use the base_sample_shape property in its samplers.
> Add a base sample shape property to MultivariateNormal

- gpytorch/variational/lmc_variational_strategy.py
Currently the default value for `latent_dim` always crashes. This updates it to be in line with what the documentation promises.
> Update default value latent_dim in LMC

- gpytorch/utils/quadrature.py
Easy resolution to #1509, must have been something with the global state in the initialization.
```python
from gpytorch.utils.quadrature import GaussHermiteQuadrature1D
from gpytorch.settings import num_gauss_hermite_locs
with num_gauss_hermite_locs(25):
quadrature = GaussHermiteQuadrature1D()
print(num_gauss_hermite_locs._global_value) # 25
print(num_gauss_hermite_locs.value()) # 25
print(quadrature.num_locs) # 25
```
It's still sort of weird behavior to have to call the setting on the likelihood init but at least you can change it now.
```python
with num_gauss_hermite_locs(25):
likelihood = Likelihood()
```
> Use Gauss Hermite Locs value in init body

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/likelihoods/test_multitask_gaussian_likelihood.py
Resolution for #1516. I should have written better unit tests for these in the first place, but you can now do the following:
```python
from gpytorch.likelihoods import MultitaskGaussianLikelihood
likelihood = MultitaskGaussianLikelihood(rank=0, num_tasks=3)
likelihood.noise = 0.5
likelihood.task_noises = torch.tensor([0.04, 0.04, 0.04])
likelihood = MultitaskGaussianLikelihood(rank=2, num_tasks=5)
likelihood.noise = 0.5
a = torch.randn(5, 3)
m = a.matmul(a.transpose(-1, -2))
likelihood.task_noise_covar = m # does a pivoted cholesky of num_rank steps
```
> Fixes for MultitaskGaussianLikelihood setters

- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/utils/memoize.py
- test/lazy/test_low_rank_root_added_diag_lazy_tensor.py
Adds a check to see if the root decomposition has already been computed and if that returned a `TriangularLazyTensor` for `inv_quad_logdet`. 
Enables the internals to use the new root decompositions after rows/columns have been updated like in #1499, which correspondingly makes some BO acquisition functions easier to implement (like botorch #724).
> Add a Check for TriangularLazyTensors in inv_quad_logdet

- gpytorch/lazy/kronecker_product_lazy_tensor.py
- test/lazy/test_kronecker_product_added_diag_lazy_tensor.py
- test/lazy/test_kronecker_product_lazy_tensor.py
Latest GPyTorch master changed the default method from `symeig` to `lanczos` to compute diagonalization when data exceeds max_cholesky_size. However lanczos causes sizing mismatch for KroneckerProductLazyTensor, thus Higher-Order GP fitting fails.  Here I change the default method back to `symeig` for KroneckerProductLazyTensor.
> Set the default method as symeig for KroneckerProductLazyTensor to compute diag

- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/utils/__init__.py
- gpytorch/utils/pinverse.py
- gpytorch/utils/qr.py
- test/lazy/test_root_lazy_tensor.py
This fixes the issue discussed in https://github.com/cornellius-gp/gpytorch/pull/1499#discussion_r594720889: Prior to this PR things break if a batched set of additional rows/cols are added to a LazyTensors via `cat_rows`. This is required for batched fantasizing. This PR also adds unit tests to cover this setting.
The unit test for the batched version with a low-rank root currently fails due to what looks like numerical issues.
> Fix handling of batched tensors in cat_rows

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/lazy/lazy_tensor.py
Currently, LazyEvaluatedKernelTensor only checks the kernel inputs during a  call. This is not desired behavior, because the kernel object itself likely has parameters that require gradients.
By passing the kernel parameters into the LazyTensor super constructor, we ensure that these are included as part of the  call.
[Fixes #1511]
> Ensure LazyEvaluatedKernelTensor requires grad.

- examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb
Fix `self.num_samples` to `gpytorch.settings.num_likelihood_samples.value()`, as `DeepGPLayer` does not currently have attribute `num_samples`.
> Fix skip connection in DGP example

- gpytorch/mlls/exact_marginal_log_likelihood.py
When sampling, it's a bug to scale the MLL by n, because our acceptance probabilities change:
`exp(a - b) != exp(a/n - b/n)`.
> Fix MLL Calculation for Sampling

- gpytorch/models/deep_gps/dspp.py
- test/examples/test_dspp_regression.py
Make the interface more similar to that of DGP.
In particular, by expanding the output of the first layer to be num_quad x ... x n x d,
we remove the need to pass in the confusing  option.
[Fixes #1538]
> Simplify 3-layer DSPP implementation.

- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
It appears this old broken code has become an issue after some recent should-be fixes opened up new code paths.
I have verified that the test fails on master. See the issue https://github.com/cornellius-gp/gpytorch/issues/1577
> fix lazy low rank root addition bugs

- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/test/variational_test_case.py
- gpytorch/utils/cholesky.py
This can *significantly* speed up `psd_safe_cholesky` due to cutting out the pytorch error-handling middle man, achieving ~2,000 X reduction in wall time: https://github.com/pytorch/pytorch/pull/56724#issuecomment-825397299.
This also allows us to add jitter to the specific batch elements for which the decomp failed (rather than indiscriminately to all).
This requires https://github.com/pytorch/pytorch/pull/56724 that hasn't landed yet but will be part of 1.9. Either way, I implemented this in a backward-compatible fashion so this will work with older pytorch versions as well.
> Use torch.linalg.cholesky_ex instead of torch.cholesky

- gpytorch/kernels/lcm_kernel.py
Allows users to initalize base kernels with different ranks in the LCM kernel. See #1553. 
Previously, this was only possible via overwriting the base kernel list.
```python
from gpytorch.kernels import LCMKernel, RBFKernel
kernel = LCMKernel([RBFKernel()] * 4, num_tasks=4, rank = [2, 3, 1, 2])
[print(n, p) for n, p in kernel.named_parameters()]
kernel(torch.randn(100, 2)).evaluate()
```
I can't find a unit test for LCM kernel and/or Multitask Kernel otherwise I'd add this into the unit test.
> Add support on initialization for different ranks in LCM kernel

- gpytorch/kernels/index_kernel.py
1. Currently IndexKernel doesn't work if the two inputs (`i1` and `i2`) have mismatching index shapes, and this looks like a broadcasting bug to me, hopefully a minor fix. 
2. Currently IndexKernel is incompatible with using `ard_num_dims` and `active_dims` to split a single input into continuous and discrete kernels (via additive or multiplicative kernel, or some other wrapper). Not sure if this is intended functionality, but it'd be nice to have. The explicit cast fixes that.
> Fix IndexKernel for non-square cases and mixed discrete-continuous inputs

- gpytorch/kernels/keops/rbf_kernel.py
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
The KeOps bypass logic in the KeOps RBF kernel doesn't work if `diag=True` since the lambda function is explicitly created with `diag=False`. In fixing it I also moved the logic into `forward` since there's not much value in creating a KeOpsLazyTensor out of the result if we're not going to use KeOps as far as I can tell.
The Matern kernel is fine.
> Working keops bypass for RBF

- gpytorch/mlls/exact_marginal_log_likelihood.py
The code in ExactMLL divides by `targets.size(-1)`.
For multitask models, this is the number of outputs.
Instead, this code divides by `function_dist.event_shape.numel()`,
which will result in losses that are similar in size to univariate
ExactGP models.
[Fixes #1155]
[Fixes #1033]
[Fixes #1159]
[Addresses #1129]
[Addresses #1633]
> Fix erroneous loss for ExactGP multitask models

- gpytorch/mlls/inducing_point_kernel_added_loss_term.py
> Correct argument order for SGPR added loss term

- gpytorch/lazy/sum_kronecker_lazy_tensor.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/lazy/test_sum_kronecker_lazy_tensor.py
Fix for #1673. Had to do some weird things with the unit test because I think it's proper to allow `linear_cg` to be called in this situation (solve itself doesn't use cg, but the sub-solve does).
Edit: Also realized that previously rank > 1 multi-task gaussian likelihoods were not returning the specialized `SumKroneckerLazyTensor`, which is a pretty big performance hit (CG vs structured e-decomp solves / logdets).
> inv_quad_logdet method for sumKronecker

- gpytorch/kernels/kernel.py
- test/kernels/test_additive_and_product_kernels.py
To determine the batch size of an AdditiveKernel or a ProductKernel, we need to recurse through ModuleLists as well as stand-alone sub kernels. This PR addresses that.
[Fixes #1672]
> Kernel batch size recurses through module lists.

- gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py
- test/examples/test_sgpr_regression.py
With `fast_computations` off, our `InvMatmul` doesn't call `_solve` it calls `cholesky` regardless of the lazy tensor, so `LowRankRootAddedDiagLazyTensor` needs to override `inv_matmul` in addition to `inv_quad_logdet`
Addresses #1708
> Fix SGPR prediction speed with no fast_computations

- gpytorch/lazy/lazy_tensor.py
Resolves #1711 as that piece of code returns on the gpu now. The only issue I can see here is if `A` is None, but I think every lazy tensor has device listings at this point.
> Add device settings to cat_rows

- gpytorch/utils/qr.py
Resolution to #1713. 
Forcibly sets zero sign returned values and sets them to one so we can add jitter to them. This enforces a full rank `R`.
> Force add to zero sign in stable_qr

- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/settings.py
- test/kernels/test_inducing_point_kernel.py
Addresses #1715 by making diagonal correction optional.
> Add setting to turn off diagonal correction for InducingPointKernel.

- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
- test/lazy/test_interpolated_lazy_tensor.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
Adds half and float calls to lazy tensor, mimicking the `.double()` calls that were already implemented.
```python
lazy_tensor.half()
```
> Add half and float calls to lazy tensor

- gpytorch/likelihoods/gaussian_likelihood.py
Fixes a small bug on intialization where `num_classes` might not necessarily be an integer if the maximum returned by `train_y` was actually a tensor (which I think is in Pytorch >= 1.9).
> Enforce num_classes in DirichletLikelihood to be an integer

- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/utils/broadcasting.py
Refactors lazy_tensor.to's arguments to have both dtype and device arguments. Resolves the current failing error:
```python
import torch
from gpytorch.lazy import KroneckerProductLazyTensor, CatLazyTensor, lazify
cat_lt = CatLazyTensor(
lazify(torch.randn(50, 50)),
lazify(torch.randn(5, 50))
)
kplt = KroneckerProductLazyTensor(cat_lt, cat_lt)
kplt.half()
```
which has error message:
```
84 
85         # Helpers for _getitem
---> 86         cat_dim_sizes = torch.tensor([t.size(dim) for t in lazy_tensors], device=output_device)
87         cat_dim_cum_sizes = torch.zeros(len(lazy_tensors) + 1, dtype=torch.long, device=output_device)
88         torch.cumsum(cat_dim_sizes, dim=-1, out=cat_dim_cum_sizes[1:])
TypeError: tensor(): argument 'device' must be torch.device, not torch.dtype
``` …
> Refactor to Arguments to more closely match torch.tensor

- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
This allows for adding rows to the covariance and updating the root decomposition without updating the root inv decomposition, which can be relatively costly due to the required QR decomposition
> add generate_inv_roots option to cat_rows

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
Related to pytorch/botorch#971.
> Don't evaluate kernel in `LazyEvaluatedKernelTensor._unsqueeze_batch`

- .conda/meta.yaml
- .github/workflows/unittests.yml
- README.md
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/block_interleaved_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/utils/contour_integral_quad.py
- gpytorch/utils/linear_cg.py
- requirements.txt
- setup.py
- test/utils/test_grid.py
- test/utils/test_linear_cg.py
- test/variational/test_natural_variational_distribution.py
There are a number of new deprecation warnings due to PyTorch 1.10 (plus some other warnings that we've previously missed). This PR addresses all warnings that pop up in the test suite.
This should hopefully be an easy merge.
> Update min PyTorch version to 1.9, resolve deprecation warnings

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
This is in response to #1813, which caused some bugs as the indexing code in lazy tensors did not support `None` indexing.
Addresses:
- #1827
- pytorch/botorch#980
- pytorch/botorch#976
Tests are passing locally* for GPyTorch (with this patch) and BoTorch (with patch pytorch/botorch#976).
*Except for some CUDA tests that failed before, and are unrelated
> Fix `LazyEvaluatedKernelTensor._unsqueeze_batch`

- gpytorch/utils/cholesky.py
This was causing a test failure:
```python
_________________________________ TestPSDSafeCholesky.test_psd_safe_cholesky_pd_cuda __________________________________
self = <test.utils.test_cholesky.TestPSDSafeCholesky testMethod=test_psd_safe_cholesky_pd_cuda>, cuda = False
def test_psd_safe_cholesky_pd_cuda(self, cuda=False):
if torch.cuda.is_available():
with least_used_cuda_device():
>                       self.test_psd_safe_cholesky_pd(cuda=True)
test\utils\test_cholesky.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test\utils\test_cholesky.py:50: in test_psd_safe_cholesky_pd
psd_safe_cholesky(A, out=L_safe)
gpytorch\utils\cholesky.py:108: in psd_safe_cholesky
L = _psd_safe_cholesky(A, out=out, …
```
> Fix `_psd_safe_cholesky` on CUDA

- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/test/variational_test_case.py
- gpytorch/utils/cholesky.py
- test/examples/test_sgpr_regression.py
`torch>=1.9` since https://github.com/cornellius-gp/gpytorch/commit/452443a000c6e043c11618c49479a8bb37af3c80, so https://github.com/cornellius-gp/gpytorch/blob/7289e7d43fc74f8e8dcfc3325fb2871ef5e828a0/gpytorch/utils/cholesky.py#L51-L90 can be removed. `CHOLESKY_METHOD` can also be removed, since (AFAIK) it's not part of the public API (https://docs.gpytorch.ai/en/stable/search.html?q=CHOLESKY_METHOD).
> Remove `_psd_safe_cholesky` that uses `torch.linalg.cholesky`

- gpytorch/settings.py
- gpytorch/utils/cholesky.py
This will make it possible for us to use more than 3 retries in BoTorch where we don't want to fail because of Cholesky errors.
> Make Cholesky max_tries a setting

- test/examples/test_batch_svgp_gp_regression.py
Hi,
The test `test_regression_error_shared_inducing_locations` in `test_batch_svgp_gp_regression.py` has an assertion bound (`self.assertLess(mean_abs_error.item(), 1e-1)`) that is too loose. This means potential bug in the code could still pass the original test.
To quantify this I conducted some experiments where I generated multiple mutations of the source code under test and ran each mutant and the original code 100 times to build a distribution of their outputs. I used KS-test to find mutants that produced a different distribution from the original and use those mutants as a proxy for bugs that could be introduced. In the graph below I show the distribution of both the original code and also the mutants with a different distribution.
<p align="center">
</p>
Here we see that the bound …
> tighten test_regression_error_shared_inducing_locations bound

- test/examples/test_kissgp_multiplicative_regression.py
Hi,
The test `test_kissgp_gp_mean_abs_error` in `test_kissgp_multiplicative_regression.py` has an assertion bound (`self.assertLess(mean_abs_error.squeeze().item(), 0.15)`) that is too loose. This means potential bug in the code could still pass the original test.
To quantify this I conducted some experiments where I generated multiple mutations of the source code under test and ran each mutant and the original code 100 times to build a distribution of their outputs. I used KS-test to find mutants that produced a different distribution from the original and use those mutants as a proxy for bugs that could be introduced. In the graph below I show the distribution of both the original code and also the mutants with a different distribution.
<p align="center">
</p>
Here we see that the bound …
> tighten test_kissgp_gp_mean_abs_error bound

- gpytorch/kernels/keops/matern_kernel.py
- gpytorch/kernels/keops/rbf_kernel.py
Resolves #1885 .
This places the enable_grad flag in the top of the covar_func call for both keops RBF and Matern kernels. 
This behavior now is fine:
```python
import torch
from gpytorch.kernels.keops import RBFKernel
from gpytorch.kernels import ScaleKernel
train_x = torch.linspace(0, 1, 510).cuda().contiguous()
train_y = 3. * train_x
test_x = torch.linspace(0, 1, 52, requires_grad = True).cuda().contiguous()
kernel = ScaleKernel(RBFKernel()).cuda()
kxx = kernel(train_x)
solve = kxx.add_jitter(0.1).inv_matmul(train_y)
pred_mean = kernel(test_x, train_x).matmul(solve.detach())
print("fwds finished")
value = torch.autograd.grad(pred_mean.sum(), test_x)
```
> Enable Gradients for All keops forward calls

- gpytorch/models/exact_prediction_strategies.py
Followup to #1903 about leaving a more informative error message when the training prior distribution is incorrectly shaped.
MWE from that issue:
```
import numpy as np
import torch
from botorch.models import SingleTaskGP, FixedNoiseGP
from botorch.utils.transforms import standardize, normalize, unnormalize
from botorch.fit import fit_gpytorch_model
from botorch.sampling import SobolQMCNormalSampler
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood
import matplotlib.pyplot as plt
import math
from botorch.models.gpytorch import GPyTorchModel
from botorch.models.gp_regression import SingleTaskGP
class PriorMean(gpytorch.means.Mean): …
```
> Add more informative error message when train targets and the train prior distribution mismatch

- test/examples/test_unwhitened_svgp_regression.py
The test `test_regression_error` in `test_unwhitened_svgp_regression.py` has an assertion bound (`self.assertLess(mean_abs_error.item(), 1e-1)`) that is too loose. This means potential bug in the code could still pass the original test.
To quantify this I conducted some experiments where I generated multiple mutations of the source code under test and ran each mutant and the original code 100 times to build a distribution of their outputs. Each mutant is generated using simple mutation operators (e.g. > can become < ) on source code covered by the test. I used KS-test to find mutants that produced a different distribution from the original and use those mutants as a proxy for bugs that could be introduced. In the graph below I show the distribution of both the original code and also the …
> tighten test_unwhitened_svgp_regression.py::test_regression_error bound

- test/examples/test_batch_svgp_gp_regression.py
The test `test_regression_error` in `test_batch_svgp_gp_regression.py` has an assertion bound (`self.assertLess(mean_abs_error.item(), 1e-1)`) that is too loose. This means potential bug in the code could still pass the original test.
To quantify this I conducted some experiments where I generated multiple mutations of the source code under test and ran each mutant and the original code 100 times to build a distribution of their outputs. Each mutant is generated using simple mutation operators (e.g. > can become < ) on source code covered by the test. I used KS-test to find mutants that produced a different distribution from the original and use those mutants as a proxy for bugs that could be introduced. In the graph below I show the distribution of both the original code and also the …
> tigthen test_batch_svgp_gp_regression.py::test_regression_error bound

- .github/workflows/examples.yml
- .github/workflows/unittests.yml
Pyro 1.8.1 requires torch 1.11, which caused issues during install in the CI workflows.
> Pin pyro to <=1.8 in CI workflows

- docs/source/priors.rst
- gpytorch/priors/__init__.py
- gpytorch/priors/torch_priors.py
- test/priors/test_half_cauchy_prior.py
> Add a HalfCauchyPrior

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
When batch-evaluating the posterior of a model (i.e.when, in eval mode, passing in a tensor with a batch shape that has more dimensions than the batch shape of the training data), then, if the kernel is lazily evaluated, this leads to obscure indexing errors. The issue is that the raw parameters of the lazy evaluated kernel have different batch shapes than the batch shape of the covariance matrix.
Specifically, if train_batch_shape is the batch shape of the kernel (unbroadcasted, as used for computing the train-train covariance)` and the posterior is evaluated with some batch shape that has more dimensions, e.g. `eval_batch_shape = add_batch_shape + train_batch_shape`, then under the hood when the `LazyEvaluatedKernelTensor` is indexed, we use a batch index meant for the …
> Fix issues with indexing broadcasted LazyEvaluatedKernelTensors

- gpytorch/means/constant_mean.py
- test/means/test_constant_mean.py
If we try to pickle a constant mean with a prior we end up with an `AttributeError: Can't pickle local object 'Module.register_prior.<locals>.closure'` error. The issue is that pickle doesn't seem to play well with specifying parameters by name (string). This PR makes it possible to pickle a constant mean with a simple prior (related: #1876 which made similar changes to some of the kernels to make it possible to pickle them).
> Make it possible to pickle constant mean with prior

- gpytorch/utils/contour_integral_quad.py
- gpytorch/utils/linear_cg.py
The `tolerance` parameter of `linear_cg` was incorrectly documented as controlling the maximum residual, while the iteration stops when the average residual is below the `tolerance`. 
https://github.com/cornellius-gp/gpytorch/blob/306d7332d74b0d337552911d69d97d939991d031/gpytorch/utils/linear_cg.py#L285-L291
> Fixed documentation of CG's tolerance parameter

- test/kernels/test_additive_and_product_kernels.py
- test/kernels/test_inducing_point_kernel.py
This gets rid of warnings of the kind
```
PytestCollectionWarning: cannot collect test class 'TestModel' because it has a __init__ constructor (from: test/kernels/test_inducing_point_kernel.py)
class TestModel(gpytorch.models.ExactGP):
```
> Avoid unit test naming convention in non-test classes

- gpytorch/means/constant_mean.py
- test/means/test_constant_mean.py
The use of `fill_` doesn't play well with the shape of the priors.
> Fix sample from prior for ConstantMean

- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/utils/permutation.py
Explicitly move tensors to one device before calling torch.cat as torch.cat no longer moves tensors silently (https://github.com/pytorch/pytorch/pull/35407). This solves one of the issues in https://github.com/cornellius-gp/gpytorch/issues/2053 resulting when the partition size is set to 0.
> explicitly move tensors to one device

- .conda/meta.yaml
- .github/workflows/run_test_suite.yml
- environment.yml
- requirements.txt
- setup.py
Follows #2057 and fixes tests: https://github.com/ngam/gpytorch/runs/7271650629?check_suite_focus=true
Recommendation: expand testing matrix to include python versions:
```yaml
strategy:
matrix:
python-version: ["3.7", "3.8", "3.9", "3.10"]
...
...
with:
python-version: ${{ matrix.python-version }}
```
> fixing sklearn dep

- gpytorch/likelihoods/likelihood.py
- gpytorch/priors/horseshoe_prior.py
- gpytorch/priors/lkj_prior.py
- gpytorch/priors/smoothed_box_prior.py
- gpytorch/priors/wishart_prior.py
The tilde in "ε ~ 𝑁(...)" was missing. Solution is to use the `\sim` character in LaTeX. See [before](https://docs.gpytorch.ai/en/latest/likelihoods.html#gpytorch.likelihoods.Likelihood) vs. [after](https://gpytorch--2073.org.readthedocs.build/en/2073/likelihoods.html#gpytorch.likelihoods.Likelihood).
Many of these equations aren't wrapped in math mode so aren't being rendered at all...
> Fix missing tilde in docs

- gpytorch/distributions/multitask_multivariate_normal.py
I'm experimenting with a multitask modeling problem and encountered the following error message:
```
Traceback (most recent call last):
File "train.py", line 239, in multi
loss = -criterion(predict_y, train_y)
File "~/lib/python3.9/site-packages/gpytorch/module.py", line 30, in __call__
outputs = self.forward(*inputs, **kwargs)
File "~/lib/python3.9/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
res = output.log_prob(target)
File "~/lib/python3.9/site-packages/gpytorch/distributions/multitask_multivariate_normal.py", line 211, in log_prob
return super().log_prob(value.view(*value.shape[:-2], -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) …
```
> MultitaskMultivariateNormal: fix tensor reshape issue

- .readthedocs.yml
- docs/requirements.txt
- docs/source/conf.py
- setup.py
The docs are currently pinned to an ancient version of Sphinx from 2019. This PR updates the docs to support the latest version of Sphinx.
I'm working on a bunch of other doc fixes and this seemed like the best place to start so as to avoid tracking down known Sphinx issues that were fixed in a later release.
> Upgrade to modern Sphinx

- examples/02_Scalable_Exact_GPs/KISSGP_Regression.ipynb
- examples/03_Multitask_Exact_GPs/Hadamard_Multitask_GP_Regression.ipynb
- examples/06_PyTorch_NN_Integration_DKL/KISSGP_Deep_Kernel_Regression_CUDA.ipynb
- gpytorch/functions/_pivoted_cholesky.py
- gpytorch/lazy/lazy_tensor.py
Previously in PyTorch, calling  on a int/long matrix was a no-op.
At some point in the PyTorch releases, this line started throwing an error (since only
floating point operations can have gradients).
Our implementation of pivoted cholesky previously called
`matrix_arg.requires_grad_(True)` on all LazyTensor/LinearOperator
arguments, without first checking whether `matrix_arg` was a floating
point dtype.
KISS-GP makes use of InterpolatedLazyTensor (to become InterpolatedLinearOperator), which
has integer matrices (the index matrices for interpolation). This
therefore produced an error message when it was used in conjunction with
the pivoted cholesky preconditioner. A similar bug exists for
preconditioned Hadamard Multitask GPs.
(The reason this bug went undetected is because our tests for …
> Fix bug in preconditioned KISS-GP / Hadamard Multitask GPs

- .github/workflows/run_test_suite.yml
faiss is now an optional package for GPyTorch, to be used in conjunction with the
VNNGP model (#2026) and hopefully more nearest neighbor GP methods in the future.
This PR ensures that our test suite tests the functionality of GPyTorch with and
without the faiss library.
> Run unittests with and without the faiss library.

- gpytorch/means/constant_mean.py
- test/means/test_constant_mean.py
Previously, ConstantMean only supported a prior on the constant (not a constraint). This PR adds a `constant_constraint` kwarg to ConstantMean.
**Backwards compatibility**
There are two non-backwards compatible changes to ConstantMean, though there is a state_dict hook to ensure that previous state dicts can be loaded:
- The `constant` parameter is renamed to `raw_constant`.
- The shape of `raw_constant` is now `*batch_shape`, rather than `*batch_shape x 1`.
[Fixes #2074]
> Add constant_constraint to ConstantMean

- gpytorch/variational/lmc_variational_strategy.py
The first argument to `VariationalStrategy` should be the model, in this case `self`.
The `latent_dim` argument to `LMCVariationalStrategy` must be negative.
> Fix LMCVariationalStrategy example in docs

- gpytorch/optim/ngd.py
Make this consistent with the base optimizer class (this also allows using this optimizer with pytorch lightning)
> Accept closure argument in NGD optimizer `step`

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/likelihoods/test_multitask_gaussian_likelihood.py
The latent variances of multitask DeepGP models are stored in non-interleaved covariance matrices.
Previously, the MultitaskMultivariateNormal.marginal method implicitly assumed that the function
covariance matrices were interleaved.
In particular, this affects multitask DeepGP models which use a
non-interleaved latent covariance matrix.
With this PR, MultitaskMultivariateNormal.marginal now checks if the input covariance matrix is
interleaved, and makes sure that the returned predictive covariance matrix matches the
interleaved/non-interleaved pattern of the latent covariance matrix.
[Fixes #2702]
> Fix bug with Multitask DeepGP predictive variances.

- docs/requirements.txt
- docs/source/conf.py
- docs/source/distributions.rst
- docs/source/kernels.rst
- gpytorch/distributions/multivariate_normal.py
- gpytorch/kernels/kernel.py
For example: if the method is...
```python
def forward(self, x1: Tensor, x2: Optional[Tensor]) -> Union[Tensor, LinearOperator]:
r"""
Does the forward thing.
:param x1: The x1 arg
:param x2: The x2 arg
:return: The forward stuff.
"""
```
The resulting documentation will include the appropriate types:
```
Parameters:
- x1 (torch.Tensor) - The x1 arg
- x2 (torch.Tensor, optional) - The x2 arg
Return type: torch.Tensor or LinearOperator
Returns: The forward stuff.
```
This (hopefully) should prevent a lot of duplicate effort on our end.
This PR also refactors the gpytorch.kernels.Kernel and gpytorch.distributions.MultivariateNormal docs to utilize auto-typing.
> Autogenerate parameter types in documentation from python typehints

- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/priors/lkj_prior.py
- gpytorch/variational/natural_variational_distribution.py
- gpytorch/variational/nearest_neighbor_variational_strategy.py
- gpytorch/variational/unwhitened_variational_strategy.py
- gpytorch/variational/variational_strategy.py
- test/likelihoods/test_gaussian_likelihood.py
This PR retires
1) GPyTorch's `psd_safe_cholesky` in favor of the LinearOperator version
2) GPyTorch's `NotPSDError` in favor of the LinearOperator version
3) `torch.testing.assert_allclose` in favor of `torch.testing.assert_close`. `assert_close` has been in torch since 1.9 and since GPyTorch requires torch>=1.11, this should not cause any bad behavior, [see here for details](https://github.com/pytorch/pytorch/issues/61844).
> Retiring deprecated versions of`psd_safe_cholesky`, `NotPSDError`, and `assert_allclose`

- gpytorch/settings.py
- test/test_settings.py
Previously, setting custom values in `dtype_value_context` was broken because `dtype_value_context.value` requires a `dtype` argument and no `dtype` argument was provided in the calls in `dtype_value_context.__init__`.
> fix custom dtype_value_context setting

- gpytorch/priors/torch_priors.py
Using HalfCauchyPrior in https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/GP_Regression_Fully_Bayesian.html raises 
```
'HalfCauchyPrior' object has no attribute 'loc'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-79-6f8875ee8806> in <module>
15 nuts_kernel = NUTS(pyro_model)
16 mcmc_run = MCMC(nuts_kernel, num_samples=num_samples, warmup_steps=warmup_steps, disable_progbar=smoke_test)
---> 17 mcmc_run.run(train_X, train_Y)
/mnt/xarfuse/uid-227577/ac1f4bfb-seed-nspid4026531836_cgpid3197131-ns-4026531840/pyro/poutine/messenger.py in _context_wrap(context, fn, *args, **kwargs)
10 def _context_wrap(context, fn, *args, **kwargs):
11     with context:
---> 12 …
```
> Fixes HalfCauchyPrior

- gpytorch/priors/__init__.py
- gpytorch/priors/torch_priors.py
- test/priors/test_half_normal_prior.py
Halfnormal distribution could be useful for variables that are constrained to be non-negative.
> Add HalfNormal prior distribution for non-negative variables.

- docs/source/marginal_log_likelihoods.rst
- gpytorch/mlls/added_loss_term.py
- gpytorch/mlls/inducing_point_kernel_added_loss_term.py
- gpytorch/mlls/kl_gaussian_added_loss_term.py
- test/examples/test_kronecker_multitask_sgpr_regression.py
- test/mlls/test_inducing_point_kernel_added_loss_term.py
This PR addresses two bugs
1. **Enable InducingPoint kernel to work with multitask regression** (As pointed out by @GHU2021, there's currently an error when trying to use MultitaskKernel in conjunction with InducingPointKernel)
2. **Fix broadcasting for SGPR added loss term** (Previously, the added loss term was summing over data dimensions and batch dimensions, which would artificially inflate this term for batch SGPR models. This PR ensures that we are only summing over data dimensions and not batch dimensions.)
[Fixes #2113]
> Fix multitask/added_loss_term bugs in SGPR regression

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
This PR is critical to have correct variances for multi-output Deep GP models.
Previously, MMVN.to_data_independent_dist ewas written to only work with interleaved MMVN distributions. This PR makes MMVN.to_data_independent_dist work with non-interleaved distributions as well.
[Fixes #2072]
> MMVN.to_data_independent_dist returns correct variance for non-interleaved MMVN distributions.

- gpytorch/kernels/kernel.py
This commit moves the `adjustment` of `x2` into the `else` branch if `x1_eq_x2 == True`, since it is not necessary in this case.
> Improving `_sq_dist` when `x1_eq_x2`

- gpytorch/kernels/keops/rbf_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/rbf_kernel_grad.py
- gpytorch/kernels/rq_kernel.py
- test/functions/test_matern_covariance.py
- test/functions/test_rbf_covariance.py
The `postprocess` logic in `Distance` and `Kernel` adds a lot of lines of code, even though it is only used by three call sites (`RBFKernel`, `RBFKernelGrad`, and `RQKernel`) and can be very efficiently put at those call sites. This commit mostly removes the `postprocess` arguments, but keeps enough (e.g. the `Distance` class) to support legacy code, and adds `_sq_dist` and `_dist` as module level functions. If we decide to go fully deprecate `Distance` as well, a further 17 lines could be removed.
> Deprecating `postprocess`

- gpytorch/kernels/piecewise_polynomial_kernel.py
> Make PiecewisePolynomialKernel GPU compatible

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
If a `LazyEvaluatedKernelTensor` is created in a `no_grad` context, the grad state is not propagated to the point of tensor evaluation, which can lead to counter-intuitive behavior. See the following:
```python
import torch
from gpytorch.kernels import RBFKernel
d = 3
b = 2
X = torch.randn(b, d)
X.requires_grad = True
with torch.no_grad():
k = RBFKernel()
K = k(X)
M = K.to_dense()
print(M.requires_grad)  # this is true on master because the evaluation of k(X) is delayed 
```
This commit makes `LazyEvaluatedKernelTensor` recall the Torch's grad state upon instantiation using the newly introduced `recall_grad_state` decorator. As a consequence, the last line of the previous code snippet returns `requires_grad = False`, as expected.
> Let `LazyEvaluatedKernelTensor` recall the grad state at instantiation

- examples/08_Advanced_Usage/index.rst
I noticed a bunch of the links in https://docs.gpytorch.ai/en/latest/examples/08_Advanced_Usage/index.html were broken. I hope this might fix them (feel free to edit if I didn't get it quite right).
> Fix 08_Advanced_Usage links

- gpytorch/kernels/lcm_kernel.py
- gpytorch/likelihoods/likelihood_list.py
- gpytorch/mlls/sum_marginal_log_likelihood.py
- gpytorch/models/exact_gp.py
- gpytorch/models/model_list.py
- gpytorch/utils/__init__.py
- gpytorch/utils/generic.py
- test/models/test_model_list.py
Fixes https://github.com/cornellius-gp/gpytorch/issues/2211 by introducing a `_length_safe_zip` that checks that the arguments are of equal length.
> Fix silently ignored arguments in IndependentModelList

- gpytorch/constraints/constraints.py
- test/constraints/test_constraints.py
Addresses #2258, avoids repeatedly checking the same condition in each forward pass. Avoids forcing GPU synchronization.
> Move  infinite interval bounds check into Interval constructor

- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/mlls/leave_one_out_pseudo_likelihood.py
- gpytorch/priors/horseshoe_prior.py
- gpytorch/variational/ciq_variational_strategy.py
This currently produces the following warnings:
```
.../gpytorch/gpytorch/likelihoods/gaussian_likelihood.py:168: DeprecationWarning: invalid escape sequence \s
"""
.../gpytorch/gpytorch/mlls/leave_one_out_pseudo_likelihood.py:12: DeprecationWarning: invalid escape sequence \l
"""
.../gpytorch/gpytorch/priors/horseshoe_prior.py:14: DeprecationWarning: invalid escape sequence \s
"""Horseshoe prior.
.../gpytorch/gpytorch/variational/ciq_variational_strategy.py:257: DeprecationWarning: invalid escape sequence \m
```
> Use raw strings to avoid "DeprecationWarning: invalid escape sequence"

- gpytorch/module.py
Previously, we would use a `memo` set in `_extract_named_priors` that would cause issues / wrong results if the same prior instance was used on different modules. I don't actually understand the reason for having this `memo`, and removing it fies this issue.
Separately, we should probably audit similar behavior in `_extract_named_constraints` and `_extract_named_added_loss_terms`.
Addresses #2263
> Fix handling of re-used priors

- .pyre_configuration
- docs/source/conf.py
- docs/source/likelihoods.rst
- examples/04_Variational_and_Approximate_GPs/Non_Gaussian_Likelihoods.ipynb
- gpytorch/likelihoods/bernoulli_likelihood.py
- gpytorch/likelihoods/beta_likelihood.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/laplace_likelihood.py
- gpytorch/likelihoods/likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
- gpytorch/likelihoods/softmax_likelihood.py
- gpytorch/likelihoods/student_t_likelihood.py
- gpytorch/module.py
- Update documentation on non-Gaussian likelihoods to discuss analytic versus Monte Carlo marginal computations (addresses issues in #1955)
- Update docstrings/typehiknts for likelihoods
[Fixes #1955]
> Likelihood docs update

- gpytorch/metrics/__init__.py
- gpytorch/metrics/metrics.py
- test/metrics/test_metrics.py
This PR fixes the implementation of the mean standardized log loss to match its definition and adds some documentation.
The mean standardized log loss as defined by Rasmussen and Williams (2006) compares the average log loss to a trivial model based off of the training data summary statistics. This standardization was missing in the implementation.
Further I added the standardized mean squared error to allow for better comparison across experiments.
> Metrics fixes and cleanup

- gpytorch/likelihoods/bernoulli_likelihood.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
Cleans up several instances of `DeprecationWarning: invalid escape sequence \m`.
> Clean up deprecation warnings

- gpytorch/mlls/exact_marginal_log_likelihood.py
- test/mlls/test_exact_marginal_log_likelihood.py
There was an issue #2340 with the mll computation when using a noise prior. 
The `MarginalLogLikelihood` class contains the likelihood twice - once as a direct child and once as child of the model.
```python
class gpytorch.mlls.MarginalLogLikelihood(Module):
def __init__(self, likelihood, model):
self.likelihood = likelihood
self.model = model
```
Previously the `_add_other_terms()` method iterated over all submodules of the MarginalLogLikelihood class, resulting in the noise prior of the likelihood being added twice.
With the proposed fix the `_add_other_terms()` method now only iterates over the submodules of the model.
> Bugfix: double added log noise prior

- gpytorch/module.py
GPyTorch `Module` class defines a custom `__getattr__` method that used to serve a purpose, but now only calls `super().__getattr__`. This leads to deepening of stack trace and can cause mild confusion. Since it is a no-op, removing it seems like the right move to me.
Aside: First calling `__getattr__` then falling back to `__getattribute__` is a bit strange on its own. Python first calls `__getattribute__` and if an attribute is not found `__getattr__` is invoked, in case there's some custom logic. Looking at the changelog, it seems like `__getattribute__` was called using some `base_name` when this wasn't a no-op, so it's probably a relic from those times.
> Remove Module.__getattr__

- gpytorch/models/model_list.py
`IndependentModelList.num_outputs` makes a strong assumption that the underlying models are single-output, so it returns the # of sub-models. However, `IndependentModelList` works perfectly fine with multi-output sub-models, leading to the `num_outputs` attribute returning the wrong value. Since GPyTorch models do not define a consistent `num_outputs` attribute, I don't see an easy way of correcting this.
This becomes an issue in BoTorch where `ModelListGP` has `IndependentModelList` ahead of `ModelList` in its MRO, which correctly defines `num_outputs` as the sum of `num_outputs` of the sub-models. Removing the property from `IndependentModelList` should allow us to use the correct definition from `ModelList`.
> Remove num_outputs from IndependentModelList

- gpytorch/functions/matern_covariance.py
- gpytorch/kernels/matern_kernel.py
This PR is intended as a minor patch to ensure that `MaternCovariance` and `MaternKernel` both produce identical outputs in batched and non-batched settings. Currently, these methods produce slightly different batched vs non-batched outputs due to how a shift is handled internally. Examples are given below.
Pre-PR:
```
kernel = MaternKernel(nu=2.5)
X = torch.rand(2, 4, 2)
kernel(X).to_dense()[0] - kernel(X[0]).to_dense()
> tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.1102e-16],
[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
[ 1.1102e-16, -2.2204e-16,  0.0000e+00,  0.0000e+00]],
grad_fn=<SubBackward0>)
```
Post-PR:
```
kernel = MaternKernel(nu=2.5)
X = torch.rand(2, 4, 2)
kernel(X).to_dense()[0] - kernel(X[0]).to_dense()
> …
```
> Minor patch to Matern covariances

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
Fixes a bug when slicing a lazy kernel and the number of outputs per row or column is greater than one.
The master implementation incorrectly checks to see if x1 and x2 are both slices. This always fails and defaults to the super method.
This PR fixes that check to ensure that row_index and col_index are slices.
The changes on the other lines are necessary to catch situations where the start point or end point of the slicing is implicit.
> Fix lazy kernel slicing when there are multiple outputs

- gpytorch/likelihoods/noise_models.py
- test/likelihoods/test_noise_models.py
In the current implementation of `HeteroskedasticNoise.forward`, `self.noise_model.train(training)` is set after the output from `self.noise_model` is received. When an exception is thrown by `self.noise_model()`, this reset is not called, leaving `self.noise_model` in evaluation mode. This patch fixes this scenario by adding a try-finally block.
The following is a typical error example:
```python
import torch
class ExactGPModel(gpytorch.models.ExactGP):
def __init__(self, train_x, train_y, likelihood):
super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
self.mean_module = gpytorch.means.ConstantMean()
self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
def forward(self, x):
mean_x = self.mean_module(x)
covar_x = self.covar_module(x) …
```
> Fix training status of noise model of `HeteroskedasticNoise` after exceptions

- gpytorch/kernels/rbf_kernel_grad.py
- gpytorch/kernels/rbf_kernel_gradgrad.py
The master implementation creates a PyTorch tensor of zeros to store the full covariance matrix, even if only the diagonal elements are needed.
If diag=True then the (potentially very large) tensor K is created but never used. This can result in a GPU running out of memory in an avoidable situation.
I have moved the creation of the tensor to store the full covariance matrix into the if diag=False branch of the code.
> Stop rbf_kernel_grad and rbf_kernel_gradgrad creating the full covariance matrix unnecessarily

- gpytorch/means/constant_mean_gradgrad.py
- gpytorch/means/linear_mean_grad.py
- gpytorch/means/linear_mean_gradgrad.py
See https://docs.gpytorch.ai/en/stable/means.html#constantmeangradgrad etc. for the docs.   I think `\nabla` is appropriate?
> Fix latex of gradients in docs

- gpytorch/lazy/__init__.py
The current setup leads to the unittest `self.assertWarns...` to wrongly trigger a warning when entering `_AssertWarnsContext` (calls `getattr` on all modules: https://github.com/python/cpython/blob/main/Lib/unittest/case.py#L292-L294). Filtering out based on name starting with `_` eliminates the needless warning and keeps the correct behavior.
> Skip the warning in `gpytorch.lazy.__getattr__` if name starts with `_`

- examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.ipynb
- gpytorch/kernels/keops/__init__.py
- gpytorch/kernels/keops/keops_kernel.py
- gpytorch/kernels/keops/matern_kernel.py
- gpytorch/kernels/keops/periodic_kernel.py
- gpytorch/kernels/keops/rbf_kernel.py
- gpytorch/settings.py
- gpytorch/test/base_keops_test_case.py
KernelLinearOperator was throwing errors when computing the diagonal of a KeOps kernel. (This computation happens during preconditioning, which requires the diagonal of the already-formed kernel LinearOperator object.) This error was because KeopsLinearOperator.diagonal calls to_dense on the output of a batch kernel operation. However, to_dense is not defined for KeOps LazyTensors.
This PR is in some sense a hack fix to this bug (a less hack fix will require changes to KernelLinearOperator), but it is also a generally nice and helpful refactor that will improve KeOps kernels in general.
The fixes:
- KeOpsKernels now only define a forward function, that will be used both when we want to use KeOps and when we want to bypass it.
- KeOpsKernels now use a `_lazify_inputs` helper method, which …
> Fix KeOps regressions from #2296.

- examples/01_Exact_GPs/index.rst
fix a typo: cannonical -> canonical
> fix a typo: cannonical -> canonical

- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/constant_kernel.py
- gpytorch/test/base_kernel_test_case.py
- setup.py
- test/kernels/test_constant_kernel.py
This commit adds `ConstantKernel`, moving the inference of additive constants into the kernel. 
Status quo: By default both GPyTorch and BoTorch are currently using a `ConstantMean` that is inferred during the optimization of the marginal likelihood. Because the mean parameter does not show up in the log determinant, it is un-regularized, which can lead to some counter-intuitive values for the constant mean, especially when the other parameters are constrained or subject to a non-trivial prior.
The inference of the posterior mean of the constant using the kernel approach is carried out with the usual linear algebraic formulation, which is more robust. See the following for an illustrative example of what can go wrong with the current `ConstantMean` approach, and how the `RBF + Constant` …
> `ConstantKernel`

- gpytorch/models/exact_prediction_strategies.py
Hello :)
This PR is related to #2468 and cornellius-gp/linear_operator#93.
The `DefaultPredictionStrategy`'s `get_fantasy_model` updates the gram matrix with new datapoints and updates the `lik_train_train_covar`'s `root_decomposition` and `root_inv_decomposition` caches by passing them to the constructor. However by using `to_dense` in lines 214-215, the caches in the `__init__` on line 69 and 72 respectively are constructed with `root` and `inv_root` of type `torch.tensor` which in [`RootLinearOperator.__init__`](https://github.com/cornellius-gp/linear_operator/blob/a00c08e1b85b6eb8499a7b64083058df8d2a00ab/linear_operator/operators/root_linear_operator.py#L19) will assign a `DenseLinearOperator` to `self.root` since `to_linear_operator` defaults to `DenseLinearOperator` if provided with …
> Bug: Exploit Structure in get_fantasy_strategy

- gpytorch/mlls/exact_marginal_log_likelihood.py
Added optional `**kwargs` to `ExactMarginalLogLikelihood.forward` call, so that optional keyword arguments can be passed on to the likelihood model. This is required, for example, when using it with `FixedNoiseGaussianLikelihood` on data that are not part of the training set, as mentioned in this issue: #2516 .
> Added optional `kwargs` to `ExactMarginalLogLikelihood` call

- .pre-commit-config.yaml
**Description**
Currently the pre-commit configuration assumes glob matching in the [``exclude`` statements](https://pre-commit.com/#top_level-exclude), even though these are assumed to be regular expressions. This causes the exclude statements to match the wrong files and shows warnings when running ``pre-commit``.
```bash
[WARNING] The 'exclude' field in hook 'flake8' is a regex, not a glob -- matching '/*' probably isn't what you want here
```
This PR replaces the glob statements with regular expressions in the pre-commit configuration.
**Related Issues**
This seems to be a [common error](https://github.com/pre-commit/pre-commit/issues/1702) and similar PRs have been made to other libraries (e.g. https://github.com/openml/openml-python/pull/1129)
> Corrected configuration of ``exclude`` statements in ``pre-commit`` configuration

- gpytorch/kernels/spectral_delta_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- setup.py
`scipy.integrate.cumulative_trapezoid` was introduced in scipy 1.6.0 and `scipy.integrate.cumtrapz` was removed in scipy 1.14.0
https://scipy.github.io/devdocs/release/1.6.0-notes.html#scipy-integrate-improvements https://scipy.github.io/devdocs/release/1.14.0-notes.html#expired-deprecations
This PR will replace an obsolete method and allow us to keep up with the latest scipy.
Compatibility with scipy<1.6.0 will be lost, but I don't think it will be a problem even if we use python 3.8.
> fix: replace deprecated scipy.integrate.cumtrapz with cumulative_trapezoid

- examples/02_Scalable_Exact_GPs/Simple_GP_Regression_CUDA.ipynb
also make it consistent with https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/Simple_GP_Regression.html
> use common notation for normal distribution N(\mu, \sigma^2)

- .conda/meta.yaml
- .github/workflows/run_test_suite.yml
- README.md
- docs/source/utils.rst
- examples/00_Basic_Usage/index.rst
- examples/00_Basic_Usage/kernels_with_additive_or_product_structure.ipynb
- examples/02_Scalable_Exact_GPs/KISSGP_Regression.ipynb
- examples/02_Scalable_Exact_GPs/Scalable_Kernel_Interpolation_for_Products_CUDA.ipynb
- gpytorch/kernels/additive_structure_kernel.py
- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/newton_girard_additive_kernel.py
- gpytorch/kernels/product_structure_kernel.py
- gpytorch/utils/__init__.py
- gpytorch/utils/sum_interaction_terms.py
- setup.py
- test/utils/test_sum_interaction_terms.py
See conversation here: https://github.com/cornellius-gp/gpytorch/pull/2544#issuecomment-2207423974
#2544 will remove `last_dim_is_batch` for GPyTorch 2.0. This PR...
- Adds temporary deprecation warnings for our next (and final?) minor release.
- Adds a [new example notebook](https://gpytorch--2549.org.readthedocs.build/en/2549/examples/00_Basic_Usage/kernels_with_additive_or_product_structure.html) demonstrating how to do additive/product structure in the GPyTorch 2.0 ways (once we remove `AdditiveStructureKernel`, `ProductStructureKernel`, and `NewtonGirardAdditiveKernel`; the 3 kernels that relied on `last_dim_is_batch`.
- Adds `gpytorch.utils.sum_interaction_terms`, which replaces the core functionality of `NewtonGirardAdditiveKernel`.
The last change uses vmaps, so we can use this PR …
> Deprecate last_dim_is_batch (bump PyTorch version to >= 2.0)

- gpytorch/models/exact_prediction_strategies.py
- gpytorch/priors/prior.py
- gpytorch/priors/torch_priors.py
- gpytorch/priors/utils.py
- test/priors/test_prior.py
- test/priors/test_utils.py
**Problem**
Currently in the SGPR prediction strategy the downdate term in the predictive covariance (shape ``num_test x num_test``) is constructed densely in memory causing unnecessary memory overhead.
**Fix**
Replaced the downdate term with a ``linear_operator.MatmulLinearOperator``.
> Avoid unnecessary memory allocation for covariance downdate in SGPR prediction strategy

- gpytorch/variational/nearest_neighbor_variational_strategy.py
- test/variational/test_nearest_neighbor_variational_strategy.py
- Fix VNNGP in batch settings #2300 
- In addition, set default jitter value to 1e-3 and variational stddev init value to 1e-2. 
- Change initialization strategy
- Special-case behaviour when training_batch_size = M (ensure we only have one minibatch and that we compute the full KL)
- Remove the option to set `k == M`
> Fix VNNGP with batches

- examples/00_Basic_Usage/Implementing_a_custom_Kernel.ipynb
> fix a typo

- gpytorch/kernels/linear_kernel.py
- test/kernels/test_linear_kernel.py
This adds support for diagonal prior variances with heterogeneous variances across dimensions (rather than requiring that each dimension have the same variance).
This also removes offset and num_dimensions, which were deprecated before 1.0.
> Allow for dimension-specific variance in linear kernel

- gpytorch/likelihoods/softmax_likelihood.py
- test/likelihoods/test_softmax_likelihood.py
> Fix bug #2606: Setting mixing_weights=False in SoftmaxLikelihood still adds the learnable parameter W

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
Adds support for broadcasting batch shapes in `MTMVN.from_independent_mvns`, allowing the mix of MVNs coming from batched and non-batched models. This is useful in BoTorch's `ModelListGP`, where we want to support mixing batched / ensemble models with non-batched models.
> Support broadcasting batch shapes in MTMVN.from_independent_mvns

- gpytorch/distributions/multivariate_normal.py
- test/distributions/test_multivariate_normal.py
Implements an `unsqueeze` method for MVN, that constructs a new MVN with the underlying tensors / linear operators unsqueezed along the given batch dimension. The choice of unsqueezing along the batch dimensions is consistent with the definition of `expand`.
`MVN.expand` allows us to start with `MVN.batch_shape = b2 x b1` and add additional batch dimensions to the left, so that `new_MVN.batch_shape = b3 x b2 x b1`. `unsqueeze`, when combined with `expand` will allow us to add batch dimensions in the middle, so that `new_MVN.batch_shape = b2 x b3 x b1 or b2 x b1 x b3`.
The use case for this is to match MVNs produced by two models of different batch shapes. Assume that `m1.batch_shape = mb2 x mb1` and `m2.batch_shape = mb1`. If we evaluate these two models with `X = xb1 x q x d`, we get …
> Implement MVN.unsqueeze

- gpytorch/distributions/multivariate_normal.py
- test/distributions/test_multivariate_normal.py
The previous implementation of `MVN.expand()` would error out when MVN was not lazy (since `self._covar` is not defined) and would discard the `scale_tril`, requiring its re-computation down the line. This PR updates `MVN.expand()` to support both lazy and non-lazy MVN and to re-use `scale_tril` whenever possible.
Test Plan:
Added unittests for `MVN.expand()`.
> Update MVN.expand() to support non-lazy MVN & reuse scale_tril where possible

- setup.py
The required jaxtyping version conflicts with the requirements of other libraries. The code appears to be compatible with newer versions, so attempting to unpin to see if anything breaks.
> Unpin jaxtyping

- .conda/meta.yaml
- .github/workflows/deploy.yml
- .github/workflows/run_test_suite.yml
- .readthedocs.yml
- CONTRIBUTING.md
- README.md
- docs/source/conf.py
- setup.py
- Update Python to 3.10
- Make `.conda/meta.yaml` consistent with `setup.py`.
> Version bump (Python 3.10)

- gpytorch/__init__.py
Export "constraints" submodule from package root to help type checkers.
```python
constraint = gpytorch.constraints.Positive()
```
> Export "constraints" submodule from package root

- gpytorch/kernels/matern_kernel.py
The current Matern documentation incorrectly states:
$d = (\mathbf{x}_1 - \mathbf{x}_2)^T \Theta^{-2} (\mathbf{x}_1 - \mathbf{x}_2)$
Updated the formula to correctly show:
$d = \sqrt{(\mathbf{x}_1 - \mathbf{x}_2)^T \Theta^{-2} (\mathbf{x}_1 - \mathbf{x}_2)}$
This is consistent with the source code implementation and the docs for [Matern52KernelGrad](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/matern52_kernel_grad.py).
Also made some vector notation bold font for clarity ($x_1$, $x_2$)
- Documentation renders correctly
- No functional code changes (documentation only)
Fixes #2569
> [Docs] Fixes #2569: Incorrect Matern docs

- gpytorch/test/base_kernel_test_case.py
- test/kernels/test_periodic_kernel.py
I have seen flaky numerical test failures in Meta-internal runs of GPyTorch’s unit tests in the last few days. Unfortunately, I have not been able to reproduce or debug those failures. I suspect a hardware-specific PyTorch change. I have not been seeing other numerical checks (e.g. in BoTorch) fail, so I don't think there's a real increase in numerical imprecision.
The failures are:
* `TestMatern52KernelGrad.test_no_batch_kernel_double_batch_x_no_ard` – failing with atol values around 2e-4 (and large rtol values)
* `TestSpectralDeltaKernel.test_kernel_getitem_broadcast` –  failing with atol values around 2e-4
* `TestPeriodicKernel.test_multidimensional_inputs`: `self.assertTrue((eig > 0.0).all().item())` is failing with "AssertionError: False is not true." I changed this to an …
> Loosen numeric tolerances in certain unit tests
