cornellius-gp/gpytorch

- gpytorch/inference/inference.py
- gpytorch/parameters/categorical_mc_parameter_group.py
This interface most closely matches the interface for normal pytorch models.
For a pytorch neural network, you would do something like this:
```python
state = original_model.state_dict()
torch.save(state, filename)
state = torch.load(filename)
new_model = Model()
model.load_state_dict(state)
```
This won't work for gpytorch, because typically the `Model()` constructor constructs a *prior* model, but we are interested in restoring a *posterior* model.
The new interface looks something like this:
```python
state = original_model.state_dict()
torch.save(state, filename)
state = torch.load(filename)
new_model = Model()
infer = Inference(new_model)
infer.restore_from_state_dict(state)
```
This constructs the appropriate posterior model from the new prior model (`new_model`) and then copies …
> Save models

- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/utils/function_factory.py
- gpytorch/utils/kronecker_product.py
- gpytorch/utils/toeplitz.py
@gpleiss @jrg365 
In this branch, I modify those computations of trace. In detail, I write them into a batch operation rather than `for` loop. The training speed is improved a lot.
> Make the trace computation be a batch operation

- gpytorch/random_variables/gaussian_random_variable.py
- gpytorch/random_variables/random_variable.py
Adding two Gaussians is done by adding the means and covariances. Multiplying a Gaussian by a scalar results in a Gaussian with the mean multiplied by the scalar and the covariance matrix multiplied by the scalar squared.
Adding or multiplying random variables in general is not easily defined, and in general the sum of two random variables is not necessarily in the same family.
> Fix random variable scalar ops

- gpytorch/random_variables/__init__.py
- gpytorch/random_variables/mixture_random_variable.py
> Mixture random variable

- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/mul_lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/utils/kronecker_product.py
- test/lazy/mul_lazy_variable_test.py
The functions `SumLazyVariable` has are all implemented in MulLazyVariable except `add_diag()` and `add_jitter()`. If they are not needed, then this branch is ready for merge.
> MulLazyVariable

- examples/kissgp_gp_regression_cuda.ipynb
- gpytorch/__init__.py
- gpytorch/functions/log_normal_cdf.py
- gpytorch/gp_model.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/utils/__init__.py
- gpytorch/utils/circulant.py
- gpytorch/utils/function_factory.py
- gpytorch/utils/interpolation.py
- gpytorch/utils/kronecker_product.py
- gpytorch/utils/toeplitz.py
- test/examples/kissgp_gp_regression_test.py
- test/examples/simple_gp_classification_test.py
- test/lazy/sum_lazy_variable_test.py
- Simple GP classification and Kiss-gp regression (1d) are cuda compatible
> Improve cuda compatibility

- gpytorch/lazy/mul_lazy_variable.py
- gpytorch/utils/trace.py
- test/lazy/mul_lazy_variable_test.py
To implement it, I add a parameter `num_dim` in `trace.py`.
> MulLazyVariable for more than 2 LazyVariable

- gpytorch/functions/dsmm.py
- gpytorch/lazy/toeplitz_lazy_variable.py
- gpytorch/utils/__init__.py
- gpytorch/utils/toeplitz.py
- test/functions/dsmm_test.py
- test/lazy/toeplitz_lazy_variable_test.py
- test/util/toeplitz_test.py
Toeplitz lazy variables can now work in batch mode
> Batch toeplitz lazy variables

- gpytorch/functions/__init__.py
- gpytorch/lazy/mul_lazy_variable.py
- gpytorch/posterior/interpolated_posterior_strategy.py
- gpytorch/utils/lanczos_quadrature.py
- gpytorch/utils/lincg.py
- test/lazy/mul_lazy_variable_test.py
In this branch, a new stochastic matmul() and method under lanzcos decomposition are implemented.
> matmul() of MulLazyVariable

- README.md
- environment.yml
- environment_cuda.yml
This PR updates our installation instructions to be easier to install our dependencies and GPyTorch globally, as well as provide `environment.yml` and `environment_cuda.yml` files for people wanting to easily install in a conda environment (see #39).
> Better installation instructions. Add conda environment files.

- gpytorch/kernels/__init__.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/lazy/constant_mul_lazy_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/lazy/mul_lazy_variable.py
- gpytorch/utils/__init__.py
- test/examples/kissgp_multiplicative_regression_test.py
- test/lazy/mul_lazy_variable_test.py
`MulLazyVariable` has been updated, and now works properly.
There is also a `MultiplicativeGridInterpolationKernel`, which does an extremely fast batch version of `MulLazyVariable`.
This incorporates all the SKIP changes.
@jrg365
> MulLazyVariable refactor

- gpytorch/kernels/spectral_mixture_kernel.py
previous version would fail if there was a zero minimum distance. the new changes will handle this.
> Spectral Mixture Kernel: made changes to accomodate zero minimum distance

- gpytorch/lazy/added_diag_lazy_variable.py
- gpytorch/lazy/chol_lazy_variable.py
- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/module.py
- gpytorch/utils/lanczos.py
> Fix some outstanding linter issues

- gpytorch/utils/linear_cg.py
The modified check for convergence is a little cleaner and also slightly faster. The other change is just formatting.
> A few tiny tweaks to linear_cg

- gpytorch/lazy/lazy_evaluated_kernel_variable.py
This turned out to be really easy with the new `LazyEvaluatedKernelVariable` from #141. Our predictive covariance calculation already did __almost__ the right thing, in the sense that it handled the `covar_correction` part of the variance calculations correctly with a MatmulLazyVariable, we just were computing the full `test_test_covar` before computing the variances:
https://github.com/cornellius-gp/gpytorch/blob/56d18a4a93acbc68b3b2cc4f382ebc0c212a5062/gpytorch/lazy/lazy_variable.py#L392-L394
Now, `test_test_covar` is a `LazyEvaluatedKernelVariable` even in the exact GP setting, so all I had to do was implement the smarter `diag` function for it.
- `LazyEvaluatedKernelVariable` now implements an intelligent `diag()` method that directly calls the kernel with transposed data to get only …
> Implement variance only predictions for exact GPs

- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/kernels/multiplicative_grid_interpolation_kernel.py
- gpytorch/lazy/lazy_evaluated_kernel_variable.py
- gpytorch/lazy/lazy_variable.py
- gpytorch/utils/cholesky.py
- test/examples/test_simple_gp_classification.py
With the Kernels being lazy variables a small change is needed to make the test_simple_gp_classification example work.
> Fix test_simple_gp_classification. Please linter.

- test/examples/test_kissgp_variational_regression.py
We currently have test failures on pytorch master (#146). This fixes those for me.
> Fix seed for TestKissGPVariationalRegression

- gpytorch/means/constant_mean.py
- gpytorch/means/mean.py
- gpytorch/means/zero_mean.py
Removes some code that was redundant as it is already handled in Module.
> Clean up Mean. Absolute imports.

- .travis.yml
- gpytorch/kernels/white_noise_kernel.py
- gpytorch/lazy/interpolated_lazy_variable.py
- gpytorch/lazy/zero_lazy_variable.py
This gets everything back up to Python 2.7 compatability, and should also fix the problem where Travis wasn't running our unit tests.
> Fix python2.7 compatability, Travis now runs 2.7 tests (Fixes #142)

- gpytorch/models/exact_gp.py
- gpytorch/random_variables/gaussian_random_variable.py
This doesn't seem to be used anywhere. It also confusing and does some undocumented magic that we should avoid.
> Don't allow mean of GaussianRandomVariable to be None

- test/functions/test_inv_quad_log_det.py
Fixes #170 and removes reference to `Variable` in `test_inv_quad_log_det`
> Update test_inv_quad_log_det to PyTorch 0.4-0.5

- gpytorch/utils/linear_cg.py
Our internals are occasionally having trouble when there is little enough data that the preconditioner already gives exact solves and log dets to machine precision. This PR fixes this by adding back in convergence criteria for both the linear CG and Lanczos part of our CG implementation.
> Improve log det stability when preconditioner is exact (fixes #179)

- gpytorch/module.py
- test/lazy/test_interpolated_lazy_variable.py
Fixes #195 plus general compatability between priors and torch Modules.
Assuming the tests pass, I'm going to merge this immediately and anyone can take up issue with it in the morning :-).
> Fix prior lookup to behave nicely with torch.nn.Modules 

- gpytorch/module.py
Fixes #204 by moving to functional recursion instead of object method recursion.
> Get priors/variational strategies also for children of torch Modules

- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
I'm making my way through some of the package and adding docstrings.
> Add docstrings for Kernel and LinearKernel

- gpytorch/functions/_root_decomposition.py
Our root decomposition function was keeping around batch dimensions even when the underlying base lazy variable had none, which was causing issues when backpropagating through samples.
@Balandat
> Fix root decomposition handling of batch dimensions when none exist.

- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/lazy/kronecker_product_lazy_variable.py
- gpytorch/lazy/lazy_evaluated_kernel_variable.py
- gpytorch/likelihoods/softmax_likelihood.py
- gpytorch/utils/linear_cg.py
- test/lazy/test_kronecker_product_lazy_variable.py
- test/util/test_linear_cg.py
> Fix KroneckerProductLazyVariable to work with rectangular matrices

- gpytorch/kernels/white_noise_kernel.py
- gpytorch/lazy/zero_lazy_variable.py
- test/kernels/test_white_noise_kernel.py
- test/lazy/test_zero_lazy_variable.py
This also fixes some issues that turned up with them in writing the unit tests for the batch setting. 
This PR begins work on #224. I think it is best to make PRs for unit tests as I make them rather than trying to do a big push for them all in one PR, since I may also be able to fix minor issues as I make them as in this PR.
cc/ @gpleiss @Balandat
> Add suite of unit tests for WhiteNoiseKernel and ZeroLazyVariable

- gpytorch/means/zero_mean.py
- test/examples/test_kissgp_additive_regression.py
- test/means/test_constant_mean.py
- test/means/test_multitask_mean.py
- test/means/test_zero_mean.py
This addresses an issue pointed out in #218 
cc/ @Balandat @jacobrgardner
> Zero mean should produce a 1D output

- gpytorch/lazy/lazy_variable.py
Just a tiny change useful for something I'm working on.
> add_jitter optionally takes an amount of jitter to add

- docs/source/conf.py
> Please linter in docs/source/conf.py

- .travis.yml
- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/kernels/spectral_mixture_kernel.py
- gpytorch/kernels/white_noise_kernel.py
- test/examples/test_kissgp_additive_regression.py
- test/examples/test_kronecker_multitask_gp_regression.py
- test/examples/test_spectral_mixture_gp_regression.py
- test/kernels/test_cosine_kernel.py
- test/kernels/test_matern_kernel.py
- test/kernels/test_spectral_mixture_kernel.py
- Introduce `_create_input_grid` method for kernels, which automatically
creates the grid for pairwise computations
- Update docs for all base kernels
- Backfill unit tests for base kernels
- Refactor SM kernel
- Introduce Cosine kernel
This is a start to fixing #249. It doesn't solve the error, but the next PR/refactor will
> Updates to Kernels

- test/examples/test_simple_gp_regression.py
This was failing with Lapack errors on pytorch master (see #271)
> Change seed for TestSimpleGPRegression

- test/functions/test_dsmm.py
- test/functions/test_inv_matmul.py
- test/functions/test_inv_quad_log_det.py
- test/functions/test_matmul.py
- test/functions/test_root_decomposition.py
- test/lazy/test_block_diag_lazy_tensor.py
- test/lazy/test_chol_lazy_tensor.py
- test/lazy/test_constant_mul_lazy_tensor.py
- test/lazy/test_diag_lazy_tensor.py
- test/lazy/test_kronecker_product_lazy_tensor.py
- test/lazy/test_mul_lazy_tensor.py
- test/lazy/test_sum_batch_lazy_tensor.py
> Proper tensor cloning

- gpytorch/priors/wishart_prior.py
To get feature parity with pre-distribution priors. Still need to add unit tests.
> Implement Wishart and InverseWishart priors

- gpytorch/kernels/kernel.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/rbf_kernel.py
> Make active_dims a buffer to simplify cudaification

- examples/05_Scalable_GP_Regression_Multidimensional/KISSGP_Deep_Kernel_Regression_With_Stochastic_Variational_Inference_CUDA.ipynb
Change train test split to 80 / 20 as given in the description (was 90 / 10 in the code)
> Fix train test split

- gpytorch/functions/__init__.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/__init__.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/non_lazy_tensor.py
- gpytorch/lazy/root_lazy_tensor.py
- gpytorch/lazy/sum_lazy_tensor.py
- gpytorch/lazy/toeplitz_lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_batch_repeat_lazy_tensor.py
This adds a default repeat to LazyTensors
> Repeat lazy tensor

- gpytorch/kernels/kernel.py
- test/examples/test_kissgp_additive_classification.py
> Throw error if ard_num_dims doesn't match the dimensionality

- gpytorch/utils/cholesky.py
- gpytorch/utils/pivoted_cholesky.py
- test/utils/test_linear_cg.py
Just as specified in the title.
> Replace batch_potrs with native batched potrs

- gpytorch/lazy/lazy_tensor.py
Fixes an issue @sdaulton raised in #340  where testing first in batch mode and then in non batch mode would fail. Also fixes an issue raised by @Balandat in #342 where running a backward pass after switching modes would fail. 
This was caused by the mean cache being a different size (`n` vs `n x 1`) depending on whether the model was first called on batch test data or non-batch test data. This PR simplifies things by just always having the mean cache not have the trailing `1` in the size to match how we handle means and labels.
I will codify this (and all related batch vs non-batch settings) working in unit tests by the end of next week when I tackle #378.
> Simplify batch handling, fix batch -> non_batch evaluation and backward calls

- examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D_With_Stochastic_Variational_Inference.ipynb
- examples/07_Scalable_GP_Classification_Multidimensional/KISSGP_Kronecker_Classification.ipynb
- examples/08_Deep_Kernel_Learning/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.ipynb
- examples/09_Pyro_Integration/Pyro_SVDKL_GridInterp.ipynb
This PR broke a lot of the examples, including DKL: https://github.com/cornellius-gp/gpytorch/pull/376
This PR fixes the issue in the same way that was done in that PR, as in https://github.com/cornellius-gp/gpytorch/pull/376/files#diff-d7c2cf3e486598ffaf365fcf5b61a2b0L44
> Fixed uses of log_transform

- gpytorch/kernels/inducing_point_kernel.py
> Diagonal correction for SGPR

- gpytorch/likelihoods/softmax_likelihood.py
SoftmaxLikelihood forward handles single feature.
> SoftmaxLikelihood forward handles single feature

- gpytorch/kernels/grid_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- test/lazy/test_kronecker_product_lazy_tensor.py
`KroneckerProductLazyTensor(a, b, c)` was computing `c \kron b \kron a`, not `a \kron b \kron c`. This PR fixes that.
> Correct order of Kronecker Product

- gpytorch/models/exact_prediction_strategies.py
Previously, deepcopying a model that was evaluated on an input that required gradients would fail with a RuntimeError b/c of the non-leaf tensors in the prediction strategies.
Implementing the dummy `__deepcopy__` method makes sure that any (subclass of) `DefaultPredictionStrategy` is not deep-copied, so that deepcopying models now works correctly (though if the copied model is evaluated, the prediction strategy will have to be regenerated.
> Do not deepcopy DefaultPredictionStrategy

- setup.py
> Add torch to install_requires in setup.py

- docs/source/functions.rst
- gpytorch/__init__.py
- gpytorch/distributions/multivariate_normal.py
- gpytorch/functions/__init__.py
- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad_log_det.py
- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/lazy/batch_repeat_lazy_tensor.py
- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/lazy/zero_lazy_tensor.py
- gpytorch/utils/deprecation.py
- test/functions/test_inv_quad_log_det.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_cached_cg_lazy_tensor.py
- log_det -> logdet
- inv_quad_log_det -> inv_quad_logdet
- Add some new deprecation helpers
> log_det -> logdet (with appropriate deprecation warnings

- gpytorch/models/exact_prediction_strategies.py
Using `torch.zeros(m, n).type_as(T)` is an antipattern. Use `torch.zeros(m, n, device=T.device, dtype=T.dtype)` instead, since this is faster and, more importantly, doesn't unnecessarily allocate memory. Not really as much of an issue for small tensors.
There's probably a lot of this kind stuff throughout the codebase that can be optimized -
> Tiny cleanup in exact_prediction_strategies

- gpytorch/functions/_dsmm.py
- gpytorch/functions/_matmul.py
- gpytorch/lazy/constant_mul_lazy_tensor.py
- gpytorch/lazy/interpolated_lazy_tensor.py
- gpytorch/lazy/kronecker_product_lazy_tensor.py
- gpytorch/lazy/mul_lazy_tensor.py
- gpytorch/lazy/toeplitz_lazy_tensor.py
- gpytorch/utils/__init__.py
- gpytorch/utils/batch.py
- gpytorch/utils/interpolation.py
- gpytorch/utils/sparse.py
- gpytorch/utils/toeplitz.py
- test/functions/test_dsmm.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_batch_repeat_lazy_tensor.py
- test/lazy/test_block_diag_lazy_tensor.py
- test/lazy/test_cached_cg_lazy_tensor.py
- test/lazy/test_cat_lazy_tensor.py
- test/lazy/test_constant_mul_lazy_tensor.py
- test/lazy/test_sum_batch_lazy_tensor.py
- test/utils/test_sparse.py
This applies to all LazyTensors except: `BatchRepeatLazyTensor`, `BlockDiagonalLazyTensor`,`SumBatchLazyTensor`.
>  LazyTensors can broadcast matmuls

- gpytorch/module.py
- test/examples/test_simple_gp_regression.py
> Support recursively initializing parameters

- test/examples/test_batch_whitened_svgp_gp_regression.py
- test/examples/test_whitened_svgp_gp_regression.py
The issue was that different number of optimization iterations were done in the cuda test. That's why there shouldn't be a bunch of copy-pasted code that makes it hard to spot issues - instead let's stick to the pattern where as much code as possible is reused.
> Fix cuda test in test_batch_whitened_svgp_gp_regression

- gpytorch/lazy/block_diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/utils/cholesky.py
- test/utils/test_cholesky.py
Fx rebasing issue. Never perform Choleksy for MulLazyTensor.
> Add psd_safe_cholesky back in

- gpytorch/models/exact_prediction_strategies.py
- gpytorch/settings.py
- test/examples/test_simple_gp_regression.py
Attempt at implementing skipping posterior covariance. 
This would close #477
> add feature flag to skip posterior covar computation

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
These were uncaught b/c the number of data points and number of tasks was the same. Adjusted the test to have different dimensions.
Fixes the fix, i.e. addresses the reopened #537
> Fix bugs in interleaved MTVN

- gpytorch/utils/linear_cg.py
- test/utils/test_linear_cg.py
- Normalize the vectors before performing solves
- Rather than adding epsilon to all the divisions, does masking to prevent division by zero errors.
> More CG improvements

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
Now that the Lazies support it, the MTMVN should as well.
> Allow arbitrary batch shapes in MTMVN

- gpytorch/settings.py
- gpytorch/utils/pivoted_cholesky.py
Adds a setting for controlling the preconditioner convergence tolerance.
> Preconditioner tolerance setting

- gpytorch/lazy/lazy_tensor.py
- test/examples/test_simple_gp_regression.py
Fixes #548, adds a smoke test so we see this if it ever comes up again.
> Fix fast_pred_var for single training input

- test/kernels/test_grid_kernel.py
Fixes #572 
I looked in to this, and I'm pretty sure it's just too tight of a tolerance.
> Fix flaky test tolerance

- gpytorch/kernels/linear_kernel.py
- test/kernels/test_linear_kernel.py
Fix call to `register_prior` and clean up unused arguments. Fixes #582
> Fix linear kernel parameters

- gpytorch/distributions/multivariate_normal.py
- gpytorch/variational/variational_strategy.py
This causes issues with Pyro models
> Don't cache prior_dist for VI

- gpytorch/functions/_inv_matmul.py
- gpytorch/functions/_inv_quad.py
- gpytorch/lazy/cached_cg_lazy_tensor.py
> Don't run preconditioner for cholesky solves

- gpytorch/utils/broadcasting.py
> [WIP] Efficiency improvements for predictions

- gpytorch/utils/cholesky.py
- test/utils/test_cholesky.py
This was never reachable due to recent changes. This makes sure it is and adds the appropriate test.
> Fix warning in psd_safe_cholesky

- gpytorch/functions/_inv_matmul.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/utils/gradients.py
- gpytorch/variational/variational_strategy.py
- gpytorch/variational/whitened_variational_strategy.py
- test/functions/test_inv_matmul.py
- test/functions/test_root_decomposition.py
- test/lazy/_lazy_tensor_test_case.py
- test/lazy/test_cached_cg_lazy_tensor.py
Fix to make `get_fantasy_model` work in small data regime
> Root inv decomp cholesky

- gpytorch/lazy/diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
The recent Cholesky fix would result in issues caused by this.
> Fix an issue with zero-dim base in DiagLazyTensor

- gpytorch/constraints/constraints.py
- gpytorch/module.py
- test/constraints/test_constraints.py
This simplifies intializing parameters from a constraint object. Addresses #629
> [RFC] Add initial_value property to constraints.

- gpytorch/beta_features.py
- gpytorch/variational/variational_strategy.py
- gpytorch/variational/whitened_variational_strategy.py
This PR makes us use the variational variances for training, but the covariance for testing.
> Non diagonal variational eval

- examples/03_Multitask_GP_Regression/Hadamard_Multitask_GP_Regression.ipynb
- examples/03_Multitask_GP_Regression/Multitask_GP_Regression.ipynb
This latex typo causes rendering problems.
> Fix improper latex

- gpytorch/utils/cholesky.py
fix the bug of jitter multiply(*1)(*10)(*100), should multply the original jitter
> fix the bug of jitter multiply(*1)(*10)(*100), should multply the ori

- setup.py
Addresses #662. Note that this does currently not work on pip 19.0.1 due to a bug: https://github.com/pypa/pip/issues/6163
> Add parsing for torch nightlies/dev back in

- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/cylindrical_kernel.py
- test/kernels/_base_kernel_test_case.py
- test/kernels/test_cylindrical_kernel.py
Implement the Cylindrical Kernel as defined in http://proceedings.mlr.press/v80/oh18a.html. Addresses issue #189.
> [WIP] implement cylindrical kernel

- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/polynomial_kernel.py
- test/kernels/test_polynomial_kernel.py
Implements the polynomial kernel + unit tests
@dme65
> Implement Polynomial Kernel

- gpytorch/lazy/added_diag_lazy_tensor.py
- gpytorch/likelihoods/likelihood.py
- gpytorch/models/pyro_variational_gp.py
- gpytorch/variational/variational_strategy.py
Several fixes:
- Fixes an issue with Pyro likelihoods
- Fix issue with preconditioner=0
- Cache prior distribution so we're not recomputing it
> Variational fixes

- .travis.yml
> Use PyTorch 1.1 as the stable version in travis

- gpytorch/priors/wishart_prior.py
- test/utils/test_pivoted_cholesky.py
> gesv -> solve

- gpytorch/means/__init__.py
- gpytorch/means/linear_mean.py
- test/means/test_linear_mean.py
Seems like a reasonably simple parametric `Mean` for users to try out?
> Add LinearMean

- gpytorch/models/model_list.py
- test/models/test_model_list.py
> Add support for get_fantasy_model to IndependentModelList

- gpytorch/kernels/inducing_point_kernel.py
> trtrs -> triangular_solve

- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/exact_prediction_strategies.py
- gpytorch/priors/lkj_prior.py
- gpytorch/utils/cholesky.py
- gpytorch/utils/woodbury.py
- test/utils/test_linear_cg.py
Since PyTorch >= 1.1, I thought it would be appropriate to update / clear these.
> Remove Cholesky related TODO and cholesky_solve util function

- gpytorch/kernels/kernel.py
Resolves https://github.com/cornellius-gp/gpytorch/issues/766, while issue is going in PyTorch upstream
> Only use torch.cdist on CPU

- gpytorch/utils/cholesky.py
- avoids re-cloning `A` during the jitter loop (to help perf)
- emits a "cholesky_cuda: singular U." RuntimeError (instead of an unnamed one) to be more consistent with the cpu cholesky failures (this really needs to be fixed upstream...)
- handle jitter variable in a more concise way
> Minor cleanup of psd_safe_cholesky

- gpytorch/utils/transforms.py
> Stabilize inv_softplus and inv_sigmoid

- gpytorch/models/exact_prediction_strategies.py
More numerically stable. Also adds jitter if the matrix is singular.
> Use QR decomposition for computing pseudoinverse in fantasy strategies

- .travis.yml
Not sure why the doc building is failing in travis, but reading online it looks like an `attrs` version issue, so I'm seeing if this fixes that.
> Fix travis doc building

- gpytorch/functions/_log_normal_cdf.py
- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/lazy/cat_lazy_tensor.py
- gpytorch/utils/eig.py
- gpytorch/utils/linear_cg.py
- gpytorch/utils/sparse.py
> Fix issues due to upstream change of tensor comparison behavior

- .travis.yml
Updates CI to use pytorch according to the updated installation instructions on https://pytorch.org/
> Update pytorch sources in travis.yml

- gpytorch/models/exact_prediction_strategies.py
Previously, if one back-propagated through the fantasy model after jitter was added to the post-QR solve, this would result in autograd failures because of in-place modification of variables. This fixes that.
> Fix in-place operation in get_fantasy_strategy

- gpytorch/means/linear_mean.py
> Fix LinearMean bias when bias=False

- gpytorch/mlls/__init__.py
new versions of botorch import NoiseModelAddedLossTerm
> Update mlls init for NoiseModelAddedLossTerm

- gpytorch/utils/interpolation.py
> Fix Bug#895

- gpytorch/kernels/__init__.py
- gpytorch/kernels/rational_quad_kernel.py
- gpytorch/kernels/rq_kernel.py
- test/kernels/test_rq_kernel.py
Implement rational quadratic kernel
add `log_alpha` hyperparameter, otherwise implement similarly to `RBFKernel`
> feature: add rational quadratic kernel

- gpytorch/kernels/index_kernel.py
There was a bug in the index kernel where things weren't being properly reshaped to support batches. For, example the suggestion for a  Hadamard LMC made on pull request #661 throws an error. This pull request should provide reshaping to avoid these issues.
> Fix support for batches in the index kernel

- gpytorch/kernels/kernel.py
> Kernel docstring typo

- gpytorch/functions/__init__.py
Assuming there should be a comma here.
> Typo in functions init

- examples/01_Simple_GP_Regression/Simple_GP_Regression.ipynb
- examples/02_Simple_GP_Classification/Simple_GP_Classification.ipynb
During reading through the tutorials, I found the description of a few parameters does not match with the code, mainly the number of training samples on both simple GP classification and regression tutorials.
> Update inaccurate tutorial description

- .isort.cfg
- gpytorch/utils/cholesky.py
- gpytorch/utils/errors.py
- test/utils/test_cholesky.py
> Cholesky gives a better error when there are NaNs

- gpytorch/lazy/chol_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
Just two small typos. Should be an easy merge. I don't want to waste your time.
> Two small typos

- gpytorch/lazy/diag_lazy_tensor.py
We don't need to have this be lazy we can just do element-wise multiplication of the underlying tensors (w/ broadcasting).
Also uses `diag_embed` instead of `eye` for `evaluate`.
> Special case NonLazyTensor matmul in DiagLazyTensor

- gpytorch/models/exact_prediction_strategies.py
> More diag embed

- gpytorch/kernels/grid_interpolation_kernel.py
- gpytorch/utils/grid.py
> Fix GridInterpolationKernel device issues

- docs/source/marginal_log_likelihoods.rst
- docs/source/models.rst
- examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb
- gpytorch/mlls/__init__.py
- gpytorch/mlls/deep_approximate_mll.py
- gpytorch/models/approximate_gp.py
- gpytorch/models/deep_gps/__init__.py
- gpytorch/models/deep_gps/deep_gp.py
- gpytorch/models/exact_gp.py
- gpytorch/models/pyro/pyro_gp.py
- Add docs for Deep GP objects
- AbstractDeep_ -> Deep_
- Deprecate DeepLikelihood in favor of DeepApproximateMLL
> Update deep GP example

- gpytorch/variational/_variational_strategy.py
- gpytorch/variational/decoupled_variational_strategy.py
adds `_decoupled_inducing_points` flag to `_VariationalStrategy` so that inputs and inducing points are correctly reshaped in `_VariationalStrategy.__call__`.
> batch mode DecoupledVariationalStrategy bug fix

- gpytorch/lazy/added_diag_lazy_tensor.py
When we switched over to using exclusively QR to do our preconditioner calculations, we took in to account that torch.qr now worked in batch mode but neglected to actually make the rest of the preconditioner calculation work for batch GPs.
> Fix batch preconditioner

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
This fixes a recent change in the latest version of pytorch (see test failures [here](https://travis-ci.org/cornellius-gp/gpytorch/jobs/654636958?utm_medium=notification&utm_source=github_status))
> Fix issue in pytorch#master with tril_indices

- gpytorch/distributions/multivariate_normal.py
> Remove tuple() null-ops

- gpytorch/lazy/block_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/utils/getitem.py
- test/examples/test_independent_multitask_gp_regression.py
- Add custom _getitem method for BlockLazyTensors
- Add a test case
[Fixes #1024]
[Fixes #1065]
> Fix issues with `from_batch_mvn`

- .travis.yml
- gpytorch/variational/mean_field_variational_distribution.py
> New PyTorch version for travis

- gpytorch/kernels/index_kernel.py
fixes https://github.com/cornellius-gp/gpytorch/issues/1130
> Fix name of renamed attribute in docstring

- docs/source/means.rst
Address https://github.com/cornellius-gp/gpytorch/issues/1151#issuecomment-629811464 from #1151
> Add LinearMean to docs

- gpytorch/lazy/added_diag_lazy_tensor.py
Resolves #1177 
Code is modified to properly select the first element across all batches so that we can check if the diagonal is constant across all batches.
> Fix noise shaping for preconditioner. 

- .travis.yml
- environment.yml
- gpytorch/kernels/spectral_mixture_kernel.py
- requirements.txt
- setup.py
- test/examples/test_simple_gp_regression.py
- test/examples/test_spectral_mixture_gp_regression.py
> SM empspect init unsqueezes 1D inputs

- docs/source/variational.rst
- examples/04_Variational_and_Approximate_GPs/Approximate_GP_Objective_Functions.ipynb
- examples/04_Variational_and_Approximate_GPs/index.rst
- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
- gpytorch/mlls/predictive_log_likelihood.py
- gpytorch/variational/__init__.py
- gpytorch/variational/_variational_strategy.py
- gpytorch/variational/batch_decoupled_variational_strategy.py
- gpytorch/variational/orthogonally_decoupled_variational_strategy.py
- gpytorch/variational/variational_strategy.py
- test/examples/test_batch_decoupled_ppgpr_regression.py
- test/variational/test_batch_decoupled_variational_strategy.py
Implements MFD models from Parametric Gaussian Process Regressors.
Docs look like this:
> BatchDecoupledVariationalStrategy

- gpytorch/models/exact_prediction_strategies.py
> Lazify test_train_covar in SumPredictiveStrategy

- gpytorch/lazy/kronecker_product_lazy_tensor.py
See https://github.com/cornellius-gp/gpytorch/pull/1208/files#r453221921
> Avoid using in-place tensor modifications

- gpytorch/likelihoods/__init__.py
- gpytorch/likelihoods/beta_likelihood.py
- gpytorch/likelihoods/laplace_likelihood.py
- gpytorch/likelihoods/student_t_likelihood.py
- test/likelihoods/test_beta_likelihood.py
- test/likelihoods/test_laplace_likelihood.py
- test/likelihoods/test_student_t_likelihood.py
Quick implementation of three additional likelihoods, along with unit tests.
Fixes #1205 by way of providing the BetaLikelihood, which supports GP regression of data on a fixed interval (e.g., [0, 1]).
> Add Beta, StudentT, Laplace Likelihoods

- gpytorch/priors/lkj_prior.py
Perfect correlation -> singular, so we should allow psd here, not just pd.
> Make _is_valid_correlation_matrix pass on psd matrices

- test/variational/test_natural_variational_distribution.py
Would fail occasionally prior to adjusting tolerances
> Fix flaky TestNatVariational.test_invertible_init

- gpytorch/lazy/added_diag_lazy_tensor.py
- test/examples/test_white_noise_regression.py
(Also removes an unnecessary test in test/example/test_white_noise_gp.py; hopefully speeds up test suite)
[Fixes #1298]
> Fix bug in fixed-noise preconditioner

- gpytorch/functions/_inv_matmul.py
> Fix ctx.needs_input_grad in _inv_matmul()

- gpytorch/variational/batch_decoupled_variational_strategy.py
Fixes example - should address the error in #1330.
> Fix docs example for BatchDecoupledVariationalStrategy

- gpytorch/settings.py
- test/test_settings.py
> Add is_default method to feature flags.

- docs/source/conf.py
- docs/source/likelihoods.rst
- examples/01_Exact_GPs/Simple_GP_Regression.ipynb
- gpytorch/likelihoods/bernoulli_likelihood.py
- gpytorch/likelihoods/beta_likelihood.py
- gpytorch/likelihoods/gaussian_likelihood.py
- gpytorch/likelihoods/laplace_likelihood.py
- gpytorch/likelihoods/likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/softmax_likelihood.py
- gpytorch/likelihoods/student_t_likelihood.py
- gpytorch/priors/prior.py
> Fix likelihood documentation

- gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py
Fixes a small bug raised in #1376
> Fix ConstantDiagLT creation

- examples/00_Basic_Usage/Hyperparameters.ipynb
- gpytorch/kernels/arc_kernel.py
- gpytorch/kernels/cosine_kernel.py
- gpytorch/kernels/cylindrical_kernel.py
- gpytorch/kernels/index_kernel.py
- gpytorch/kernels/kernel.py
- gpytorch/kernels/linear_kernel.py
- gpytorch/kernels/multitask_kernel.py
- gpytorch/kernels/periodic_kernel.py
- gpytorch/kernels/polynomial_kernel.py
- gpytorch/kernels/scale_kernel.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/likelihoods/beta_likelihood.py
- gpytorch/likelihoods/laplace_likelihood.py
- gpytorch/likelihoods/likelihood.py
- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
- gpytorch/likelihoods/student_t_likelihood.py
- gpytorch/mlls/_approximate_mll.py
- gpytorch/mlls/exact_marginal_log_likelihood.py
- gpytorch/models/pyro/_pyro_mixin.py
- gpytorch/module.py
- test/test_module.py
This fixes #1360
Test Plan:
[test_deepcopy_fixed.ipynb.txt](https://github.com/cornellius-gp/gpytorch/files/5586510/test_deepcopy_fixed.ipynb.txt)
> Pass module to prior closures

- examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.ipynb
- examples/02_Scalable_Exact_GPs/Scalable_Kernel_Interpolation_for_Products_CUDA.ipynb
- examples/04_Variational_and_Approximate_GPs/GP_Regression_with_Uncertain_Inputs.ipynb
- examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.ipynb
- examples/04_Variational_and_Approximate_GPs/SVGP_Regression_CUDA.ipynb
> Remove references to SGD in example notebooks

- gpytorch/variational/natural_variational_distribution.py
- test/variational/test_variational_strategy.py
> Make NGD is compatible with batch-mode variational GPs

- examples/01_Exact_GPs/Simple_GP_Regression.ipynb
This is consistent with elsewhere in the docs and the definition given in context
> tutorial should read 'homoskedastic noise model'

- docs/source/utils.rst
- gpytorch/utils/grid.py
> Add grid.py to utils documentation

- gpytorch/likelihoods/multitask_gaussian_likelihood.py
- gpytorch/likelihoods/noise_models.py
Replaces MultitaskGaussianLikelihood with the extended MultitaskGaussianLikelihoodKronecker.
> Move MultitaskGaussianLikelihoodKronecker into MultitaskGaussianLikelihood

- examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb
Fixed the typo in the documentation (Deep GP) mentioned in #1447
> fixed a typo in the documentation (issue #1447)

- gpytorch/kernels/matern_kernel.py
> Buxfix and update to Matern docs.

- examples/00_Basic_Usage/Implementing_a_custom_Kernel.ipynb
- examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.ipynb
> Small edits to example notebooks

- gpytorch/functions/_inv_quad_log_det.py
> Avoid Lanczos decomposition with non-deterministic logdet probes

- test/kernels/test_rff_kernel.py
This failed occasionally causing issues in test infra.
> Fix flaky RFF test

- gpytorch/models/exact_prediction_strategies.py
- test/examples/test_sgpr_regression.py
[Fixes #1515]
This addresses a bug introduced by #1493
> Fix SGPR variance bug

- gpytorch/kernels/keops/keops_kernel.py
Hot fix for https://github.com/cornellius-gp/gpytorch/issues/1543
> Hot fix for keops zero gradients

- gpytorch/kernels/inducing_point_kernel.py
- gpytorch/models/exact_prediction_strategies.py
- test/examples/test_sgpr_regression.py
Addresses problem in #1515 . @monabf - can you check out the `faster_sgpr_covar` branch and make sure that this fix works for you? If so, then we'll cut a bug fix release that should hopefully fix these SGPR issues once and for all :)
> Speed up SGPR covariances

- gpytorch/settings.py
> Add default setting values to docs.

- gpytorch/functions/_root_decomposition.py
- gpytorch/utils/lanczos.py
- test/models/test_exact_gp.py
- test/utils/test_lanczos.py
See https://github.com/cornellius-gp/gpytorch/issues/1602 for details. The new tests currently fail on master. After much debugging, it turned out to be an off-by-one error.
> Fix lanczos bug and add tests

- gpytorch/models/exact_prediction_strategies.py
- test/examples/test_sgpr_regression.py
> Fix SGPR errors when testing on training data.

- gpytorch/kernels/kernel.py
- gpytorch/models/exact_prediction_strategies.py
- test/kernels/test_additive_and_product_kernels.py
- test/models/test_exact_gp.py
I verified the new test fails on master. See https://github.com/cornellius-gp/gpytorch/issues/1580 for more details
> Sum prediction strategy fix

- gpytorch/lazy/lazy_tensor.py
- gpytorch/models/pyro/_pyro_mixin.py
- gpytorch/test/lazy_tensor_test_case.py
See https://github.com/cornellius-gp/gpytorch/issues/1583 for more details
> simplify and fix root inverse decomposition logic

- gpytorch/functions/__init__.py
- gpytorch/kernels/matern_kernel.py
- gpytorch/kernels/rbf_kernel.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/variational/ciq_variational_strategy.py
- test/functions/test_matern_covariance.py
- test/functions/test_rbf_covariance.py
`apply` is a static method, let's use it as such. In anticipation of https://github.com/pytorch/pytorch/pull/57357
> Do not instantiate autograd functions

- gpytorch/kernels/periodic_kernel.py
- test/kernels/test_periodic_kernel.py
Periodic kernel now uses eq. 47 in David Mackay's Introduction to Gaussian Processes, found here: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.81.1927&rep=rep1&type=pdf
with one small difference: it doesn't do different period lengths or lengthscales for each feature. Fixes #835 
If I were to add in ARD, would this be a different PR or can I add it here? Sorry, new to this whole contributing to open source thing, so let me know what works best for everyone. Thanks for your patience :)
Fixes #1615
> Periodic kernel handles multi-dimensional inputs

- gpytorch/module.py
- test/kernels/test_additive_and_product_kernels.py
Addresses #1634. 
cc: @Balandat
> Fix initialize bug for additive kernels.

- gpytorch/lazy/root_lazy_tensor.py
> Swithed to tensor all method to avoid errors when using pyro samples.

- .gitignore
- docs/source/kernels.rst
- gpytorch/kernels/__init__.py
- gpytorch/kernels/piecewise_polynomial_kernel.py
- test/kernels/test_piecewise_polynomial_kernel.py
- test/kernels/test_polynomial_kernel.py
I added a Piecewise Polynomial Kernel as linked in Issue #607. Do give me any feedback you have and tell me about any changes that you would like to accept it to the repository
> Added Piecewise Polynomial Kernel

- gpytorch/lazy/kronecker_product_added_diag_lazy_tensor.py
- gpytorch/lazy/lazy_tensor.py
- gpytorch/settings.py
- gpytorch/test/lazy_tensor_test_case.py
- gpytorch/variational/variational_strategy.py
This PR adds a new setting for a dtype registry for symeig (not cholesky, but wouldn't be too difficult to set it there).
Resolves #1213. 
Relatedly, should we put up more unit tests for settings?
> Add dtype registry for symeig

- gpytorch/kernels/kernel.py
Should fix #1809 (can't test locally due to #1810)
> Fix in-place modification on kernel `__getitem__`

- gpytorch/lazy/lazy_evaluated_kernel_tensor.py
Seems to have been a copy&paste error
> Fix indexing bug in LazyEvaluatedKernelTensor

- setup.py
> Do not include tests in package

- gpytorch/lazy/lazy_tensor.py
- gpytorch/test/lazy_tensor_test_case.py
- test/lazy/test_identity_lazy_tensor.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
Add support for right multiplication by a lazy tensor; see #1911.
> LazyTensor.rmatmul

- docs/source/marginal_log_likelihoods.rst
Adds LeaveOneOutPseudoLikelihood into the docs.
> Add LeaveOneOutPseudoLikelihood into docs

- gpytorch/variational/_variational_distribution.py
> Clean up old deprecation warnings in variational distribution

- README.md
Since latest features may rely on latest features in linear operator.
> Include linear operator in installation instructions

- test/priors/test_half_cauchy_prior.py
#2155 this commit fix the visible bugs in HalfCauchy prior test.
> fix bugs in test half Cauchy prior.

- gpytorch/module.py
Follow up to https://github.com/cornellius-gp/gpytorch/issues/2154
[T134509183](https://www.internalfb.com/intern/tasks/?t=134509183)
> Generalize RandomModule

- gpytorch/metrics/metrics.py
According to issue #2174 , I fix the MSLL code. (Move 0.5 in the parentheses)
> Update MSLL in metrics.py

- gpytorch/variational/nearest_neighbor_variational_strategy.py
- fix a computation bug 
- add jitter setting in model initialization 
- fix format issue
> fix bug in nearest_neighbor_variational_strategy

- gpytorch/likelihoods/bernoulli_likelihood.py
> Fix BernoulliLikelihood documentation

- examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.ipynb
This update addresses some comments in #2302
> Update SGPR notebook

- gpytorch/variational/nearest_neighbor_variational_strategy.py
See https://github.com/cornellius-gp/linear_operator/issues/53.
> Fix solve_triangular(Tensor, LinearOperator) not supported in VNNGP

- gpytorch/distributions/multitask_multivariate_normal.py
- test/distributions/test_multitask_multivariate_normal.py
> More informative string representation of MultitaskMultivariateNormal distributions.

- examples/02_Scalable_Exact_GPs/Exact_GP_Posterior_Sampling_with_CIQ.ipynb
- examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.ipynb
- gpytorch/beta_features.py
- test/examples/test_simple_gp_regression.py
- test/lazy/test_lazy_evaluated_kernel_tensor.py
Checkpointing has been very buggy, and the KeOps integration does it better. We will remove the checkpointing feature in the next version.
> Deprecate checkpointing

- gpytorch/variational/_variational_strategy.py
- gpytorch/variational/nearest_neighbor_variational_strategy.py
- test/variational/test_ciq_variational_strategy.py
- test/variational/test_grid_interpolation_variational_strategy.py
- test/variational/test_independent_multitask_variational_strategy.py
- test/variational/test_lmc_variational_strategy.py
- test/variational/test_nearest_neighbor_variational_strategy.py
- test/variational/test_orthogonally_decoupled_variational_strategy.py
- test/variational/test_unwhitened_variational_strategy.py
- test/variational/test_variational_strategy.py
> Fix error messages for ApproximateGP.get_fantasy_model

- gpytorch/kernels/kernel.py
> DOC: Fix typo in docstring.

- gpytorch/kernels/rff_kernel.py
here is RFFKernel documentation https://docs.gpytorch.ai/en/stable/kernels.html#rffkernel
before the fix:
after the fix:
> DOC: fix formatting issue in RFFKernel documentation

- gpytorch/kernels/periodic_kernel.py
> DOC: fix broken URL in periodic_kernel.py

- .github/ISSUE_TEMPLATE/---documentation-examples.md
- .github/workflows/run_test_suite.yml
- README.md
- `master` -> `main`
- `develop` is now CI'd
> `main` and `develop` branches

- examples/01_Exact_GPs/Simple_GP_Regression.ipynb
fix broken link to FixedNoiseGaussianLikelihood in Simple_GP_Regression.ipynb
> fix broken link in Simple_GP_Regression.ipynb

- gpytorch/kernels/index_kernel.py
Fixes https://github.com/cornellius-gp/gpytorch/issues/2620
> Fix error in IndexKernel docstring

- gpytorch/kernels/linear_kernel.py
- test/kernels/test_linear_kernel.py
> Ensure LinaerKernel stores ard_num_dims property.
